### ISSUE TITLE
Skip Chaptermark

### ISSUE THREAD

**Issue by realredknight** [Automattic/pocket-casts-android#1032]
### What problem does this address?

I subscribed to shows, which begin their episodes with outtakes. Due to the nature of outtakes, this part of the show does not have a fixed length (sometimes it isn't even present). So "Skip XX Seconds on Beginning of Episodes" does not help. As I'm often listening to podcasts while driving, manually skipping isn't a solution, too

### What is your proposed solution?

I suggest a setting to Skip given chaptermarks, e.g. "Skip Intro"

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by CookieyedCodes** [comment]
I tend to calculate an 25% average in cases like this, Someone was actually developing this on iOS to skip chapters, I hope someone will take up the slack and do it on Android too tho (note: their was mumbling that the team wanted to make it a plus feature just so your aware tho)

**Comment by MiSikora** [comment]
This was added in `7.60`.
