### ISSUE TITLE
Sleep Timer option to end at chaptermark

### ISSUE THREAD

**Issue by realredknight** [Automattic/pocket-casts-android#1033]
### What problem does this address?

Fixed Sleep isn't always useful, especially on long-length Episodes (or Audio Books)

### What is your proposed solution?

Add an option to trigger the sleep timer on next chaptermark. To keep the Options short, a free INput for fixed sleeptimer length instead of preconfigured values could be used

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by CookieyedCodes** [comment]
+1, but I do also want a number of episodes sleep timer 😅

**Comment by mebarbosa** [comment]
Thank you for taking your time to report this! I am closing this one since we [added](https://github.com/Automattic/pocket-casts-android/pull/2115) the ability to set end of chapter since `7.64`
