### ISSUE TITLE
Watch email password entry field does not mask password

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1048]
### Description

When logging in with email/password on the watch, the password field does not get masked, so the password is entirely visible. We should mask this (or present the option to have it masked/unmasked

### Step-by-step reproduction instructions

1. Install the watch app
2. Log into an account by email
3. Observe that your password is visible as you type it

### Screenshots or screen recording

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/d57c7494-5efe-4675-bd93-622ab4899746)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pixel 3 Wear OS 3 watch, running 7.40 pre-release build

**Comment by atharv028** [comment]
Hey @mchowning, The app uses [Remote Input](https://developer.android.com/reference/androidx/wear/input/RemoteInputIntentHelper) which doesn't yet support input masking for Wear OS.

**Comment by mchowning** [comment]
Closing this because we have removed email/password login from the watch app to comply with Google Wear OS Guidelines, so this is no longer applicable.
