### ISSUE TITLE
Listening History updates when not Listening

### ISSUE THREAD

**Issue by realredknight** [Automattic/pocket-casts-android#1053]
### Description

"Listening History" shows Episodes, even if they are not not played. The List is updated with the top item of the "Up Next" queue, even if the player state is "paused". 

Semantically the list should only update if player state is "Playing" as neither the item was played nor it is "History"

### Step-by-step reproduction instructions

1. Add items to "Up Next"
2. Play an episode and tap "Pause"
3. Finish "now Playing" Episode by seeking to end or tap "mark as played" so the next item in Queue is selected
4. Go to "Listening History"

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pocket Casts 7.40-rc2 (9103) on multiple devices. (Fairphone 3 Plus, Samsung Galaxy Tab)

**Comment by geekygecko** [comment]
To change this would take more effort than it's worth. Closing this issue for now.
