### ISSUE TITLE
Unsubscribe button should not look like "done" button.

### ISSUE THREAD

**Issue by erebion** [Automattic/pocket-casts-android#1058]
### Description

The unsubscribe button looks like a button which means "done with this, mark as listened to".

I recommend changing this to a red "❌" **symbolising ending or cancelling something** instead of a ":heavy_check_mark:" , which seems to **symbolise "I've completed listening to this and moved on."**

The UI language of the app is somewhat confusing. If you then select an episode, the same symbol in blue means "mark as listened to".

So two symbols, both the same except for colour, mean something completely different.

I'm reporting this as a bug as this impacts the UX directly.

### Step-by-step reproduction instructions

1. Touch the button expecting to mark the podcast as "listened to"
2. getting confused why the app asks to confirm unsubscribing

### Screenshots or screen recording

![image](https://github.com/Automattic/pocket-casts-android/assets/104499031/c0034513-0ddb-4604-ac74-0d3326699545)

I've marked the similar looking buttons that have a very different meaning.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

irrelevant

**Comment by geekygecko** [comment]
Thanks for the feedback. I have let the design team know.
