### ISSUE TITLE
Users repeatedly getting logged out notification

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1087]
### Description

We have had multiple reports of users who are getting an error notification that they are being logged out multiple times. Interestingly, the users do not actually seem to be logged out (i.e., they can dismiss the notification and continue using the app, syncing, etc.). 

### Step-by-step reproduction instructions

Unknown

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by mchowning** [comment]
I went ahead and assigned you @geekygecko because I know you've got looked into this a bit.

**Comment by kenseii** [comment]
This also happened on a device having pocket casts version `7.41-rc-3 (9107)` running on android 12

**Comment by igotdes** [comment]
Reported in #6382503-zen. I've asked them to send us logs in the meantime.

**Comment by mchowning** [comment]
Closing this since we haven't had any reports of this since `7.42-rc-1`.
