### ISSUE TITLE
Files do not upload to cloud

### ISSUE THREAD

**Issue by reginabally** [Automattic/pocket-casts-android#1089]
### Description

Originally reported in 6413632-zd-woothemes.

When I uploaded a file on the Android app with the "Auto upload to cloud" setting enabled, the file wasn't uploaded to the cloud and was not accessible on the web app.

### Step-by-step reproduction instructions

1. On the Android app, go to Profile > Files
2. Tap the vertical ellipsis button > Files settings and enable the "Auto upload to cloud" option
3. Go back to the Files screen, tap the "+" button to upload a file
4. Notice the icon under the file doesn't show a "cloud" icon
5. Log in to the web app at https://play.pocketcasts.com
6. Go to Files and notice the file uploaded in Step 3 cannot be found

### Screenshots or screen recording

<table>
<td><img src="https://github.com/Automattic/pocket-casts-android/assets/40906847/cdb2ea96-3ad6-430f-a98a-a05b626c4d9f" width=300 /></td>
<td><img src="https://github.com/Automattic/pocket-casts-android/assets/40906847/6da51f31-4c52-4f9a-8f72-b0d013090ac0" width=300 /></td>
</table>

![CleanShot 2023-06-16 at 09 46 13@2x](https://github.com/Automattic/pocket-casts-android/assets/40906847/ffcff39f-369e-4f1a-94d8-75a7901b57f2)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 4 (emulated device), Android 12, app version 7.40

**Comment by geekygecko** [comment]
I just tried to repeat this issue and it uploaded to the cloud straight away. 🤔 It's not like it's waiting for WiFi as you have that option off and it would tell you in a message.

If you tap on one of the files not yet uploaded and tap "Upload to cloud" does it work?

**Comment by geekygecko** [comment]
https://github.com/Automattic/pocket-casts-android/assets/308331/7f4a5f7a-36bd-4670-ac1a-6130af9e42ee

**Comment by reginabally** [comment]
My bad! I was uploading .ogg files from the Android app, which seems unsupported. I then uploaded a .m4a file, and it worked.

I'm asking the user for the file type and if manual upload works. We'll report back when we hear back from the user.

**Comment by mchowning** [comment]
Closing this since we can't recreate and the user didn't respond when we asked for more information.
