### ISSUE TITLE
Incorrect text alignment in episode description and notes for RTL languages

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#109]
The text alignment for podcasts in RTL languages (e.g. Hebrew) is aligned to the left in episode details and notes. The user expects the text is aligned to the right like the podcast titles and description.

Sample podcast: https://pca.st/a8hgnlud

App version : 7.19.2 (7442)
Phone: Google - sunfish - Pixel 4a - sunfish
Android version: 12 SDK 31

Screenshot taken from the episode details screen

<img  width="300" src="https://user-images.githubusercontent.com/308331/178907925-f2f88a01-bbbe-4dd3-8fa0-caf4acae8bb6.png" />

**Comment by owenlejeune** [comment]
Taking a look at this
