### ISSUE TITLE
Watch Now Playing Screen does not have a proper empty state

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1094]
### Description

On the watch, the Now Playing screen does not have a good empty state. Some of the issues are:
1. There is no text prompting the user that they need to select an episode to play
2. 💥  If you tap on the area where the episode name would be, the app crashes
3. The fast-forward/rewind/play buttons are not disabled, so they provide a ripple effect if you tap them, but nothing happens.

### Step-by-step reproduction instructions

1. Open the app with an account that has no podcasts currently playing or in the up next queue. 
2. Swipe left to get to the Now Playing screen

### Screenshots or screen recording

![Screenshot 2023-06-16 at 11 50 29 AM](https://github.com/Automattic/pocket-casts-android/assets/4656348/8dba51ed-aeec-410e-b2af-88fa3a155e6d)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

7.41-rc-2

**Comment by mchowning** [comment]
👍 That makes perfect sense to me @atharv028 !

**Comment by atharv028** [comment]
Great, will raise a PR for this then
