### ISSUE TITLE
Address warning about missing permission check when PlaybackManager calls notify

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1126]
### Description

Android Studio is warning that we're posting a notification [here](https://github.com/Automattic/pocket-casts-android/blob/1bc7767bb1218b3cf50ce5cac091ff3fe756370c/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt#L1597) without checking that we have the (user-revokable) permission to do so.

### Step-by-step reproduction instructions

N/A

### Screenshots or screen recording

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/85844562-e847-4d8f-ad54-fde85166d8fb)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by atharv028** [comment]
Looks like the linter wants to add notification permission to the manifest of repositories module and add permission check using `ActivityCompat.checkSelfPermission()`. 

But I think adding a check before calling the `notify()` function and suppressing the false positive error would be more cleaner approach, what do you think?

<img width="909" alt="Screenshot 2023-07-16 at 8 44 15 PM" src="https://github.com/Automattic/pocket-casts-android/assets/89896473/0156b7c6-b644-4f36-b1a8-496921150e3f">

**Comment by mchowning** [comment]
It seems like either would work (I don't think the lack of a permission check is causing us any issues currently because the application modules take care of that), but I'd lean toward applying the fix suggested by the linter (manifest update and `checkSelfPermission`) unless we have specific reasons to do something different.

**Comment by vkundapur** [comment]
What's reported by the linter is not a false positive. The `repositories` is a separate module. Actually, it can be compiled as a separate aar(I maybe wrong here). I think that's why linter reports it as an error.

In my opinion, the correct fix would be to add the permission in the manifest and call the `checkSelfPermissions`.
