### ISSUE TITLE
Fix UI issues on Fold Devices

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#1148]
### Description

Some of the colors and UI does not seem to be working properly on Folding devices. 

### Step-by-step reproduction instructions

1. Access the Up Next Queue

### Screenshots or screen recording

An example, here is how the Up Next queue looks on the Google Pixel Fold: 
![image](https://github.com/Automattic/pocket-casts-android/assets/16253818/ff779f70-e559-437a-bc76-637a5b87eec1)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel Fold, Android 14, Pocket Casts v7.41

**Comment by mchowning** [comment]
Have you seen this on your device @geekygecko ?

**Comment by joashrajin** [comment]
I personally cannot replicate the original issues but something I've noticed on my Fold is that the podcasts page is cut off on the top when the device is horizontally used 
![Screenshot_20231218_185503_Pocket Casts](https://github.com/Automattic/pocket-casts-android/assets/16253818/d2966cb2-381c-42d2-a491-8d06c13a5d54)

**Comment by geekygecko** [comment]
I haven't been able to reproduce this issue on my fold
