### ISSUE TITLE
Watch: Filters screens are empty when there are no episodes in the filter

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1154]
### Description

The filters screens just present an empty screen when there are no episodes. We should present some kind of empty state (even if it is minimal like we have [for the files screen](https://github.com/Automattic/pocket-casts-android/pull/915)) or for the podcasts screen when there are no subscribers.

### Step-by-step reproduction instructions

1. Log into a new account with no podcast subscriptions
2. Check the filters screens for New Releases and In Progress and notice they are empty

### Screenshots or screen recording

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/a3ac7d9e-3004-4c3b-9e4b-138e355e819d)

By contrast, this is what the podcasts screen shows when there are no subscriptions:

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/8cbfde95-ecd7-482e-8c6c-58eb2bf1857c)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Wear OS 3 emulator, 7.42 pre-release build

**Comment by atharv028** [comment]
@mchowning would something like this suffice? 

![Screenshot_20230716_152508](https://github.com/Automattic/pocket-casts-android/assets/89896473/d7b7d7a0-d355-4718-b77e-40d8a64b8cb6)

**Comment by mchowning** [comment]
👍  That looks good to me @atharv028.
