### ISSUE TITLE
Theme selection UI can incorrectly indicate currently selected theme

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1228]
### Description

When using a free account, selecting a Plus "theme" can result in subsequently selected themes not reflecting the current state of the UI—the UI will have the just-selected theme active, but the UI will indicate that a previously selected theme is active.

This is related to https://github.com/Automattic/pocket-casts-android/issues/68

### Step-by-step reproduction instructions

1. With a Free account,
2. Go to "Profile" → ⚙️  → "Appearance"
3. Select a "Free" theme
4. ✅ Observe that the UI updates to that theme and indicates that theme is selected
5. Select a "Plus" theme
6. Dismiss the Plus promotion screen
7. 💥 Observe that the UI indicates that the Plus theme is selected, but the UI displays the previously selected theme
8. Select a "Free" theme
9. 💥 💥  Observe that the UI updates to the selected theme, but indicates that the previously selected Free theme is currently selected.

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/4656348/f1d1c875-e47a-4289-918f-5fdb3b7434de

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung A13, Android 13, Pocket Casts 7.44 pre-release build

**Comment by neeldoshii** [comment]
Can I get this issue assigned to me?

**Comment by mchowning** [comment]
All yours @neeldoshii ! 😄

**Comment by P-Burk** [comment]
I'm not trying to step on anyone's toes, but I've got a PR up for a fix to this issue. I don't know how to bring this up without sounding petty, but I just wouldn't want for someone to put time/effort into fixing something only to find the issue has already been closed when they submit their own PR.

**Comment by neeldoshii** [comment]
Sure @P-Burk, sure no problem it slipped of my mind. I didn't checked a PR has been merged.

**Comment by mchowning** [comment]
Thanks for chiming in @P-Burk ! Sorry I overlooked that.

**Comment by P-Burk** [comment]
No worries. Going forward, I can ask to get assigned to issues I'm working on if that's the standard practice/etiquette for this sort of thing (I'm still new to OSS contributions). I just usually don't do it since my fixes start out with me just being like "let's see if I can even figure out where this issue stems from" and I don't want to "claim" an issue while I'm literally just searching through the code base on where to even start trying to fix said issue.

**Comment by mchowning** [comment]
> I just usually don't do it since my fixes start out with me just being like "let's see if I can even figure out where this issue stems from" and I don't want to "claim" an issue while I'm literally just searching through the code base on where to even start trying to fix said issue.

I feel that way often too. No worries about feeling like you have to claim an issue. That's more of a thing to worry about if you're investing significant time into investigating/fixing something or if you know other people are also looking into an issue. In this case, I should have noticed your open PR. That was just a miss on my part.
