### ISSUE TITLE
Change support feedback to use the Zendesk API

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#127]
Switch the support feedback to use the Zendesk API rather than just sending an email. The iOS project has already made this change. It might be good to get some design feedback before implementing this as the screens don't match the rest of the app.

<img  width="300" src="https://user-images.githubusercontent.com/308331/179738986-51ce8e2f-0b05-45e8-b16b-c08d64b62ae7.png" />
<img  width="300" src="https://user-images.githubusercontent.com/308331/179739220-c77b612b-5e37-42c3-bf40-04963b5bab10.png" />
<img  width="300" src="https://user-images.githubusercontent.com/308331/179739270-8b0ca718-3ca7-43f8-8017-9b692a0b606c.png" />

**Comment by mchowning** [comment]
Apparently we don't want to use the Zendesk mobile SDK because that has caused problems for other apps. Woo Mobile has recently re-built the support interface they use though and that has been working well.

internal ref: p1683032572328739/1682870638.149889-slack-C02A333D8LQ

**Comment by joashrajin** [comment]
> P.S. if you search for support and click on your links "get support" or "leave feedback" from your profile -within- the app, it offers the popup which has you select the app you would like to open the link with.
I now realize I should have been using my email, but I was clicking the browser that I use and it sent me to the links in the images instead... Hilarious, actually, in hindsight, but I thought y'all were being cheeky at first.

^ user was clicking the web browser when trying to get support instead of the mail client

6282483-zd-woothemes

**Comment by geekygecko** [comment]
I'm closing this issue as we don't want to use the Zendesk API.
