### ISSUE TITLE
Bookmarks - Can't get to the end of the bookmark list

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1272]
Steps to reproduce

- Login using paid account
- Go to `Profile` tab ->  `Files` screen
- Add a file
- Play the file and a few bookmarks using the Player screen bottom toolbar "Add bookmark" option
- Return to `Files` screen
- Tap on the file 
- On the bottom sheet that appears, tap on `Bookmarks` menu
- On the bookmarks screen, scroll to bottom
- Notice that the last bookmark is not fully visible

<img  width="300" src="https://user-images.githubusercontent.com/308331/259757131-66ca8c46-7ad8-4b69-b3b3-ed01cbb4b319.png" />

**Comment by Mzazi25** [comment]
I have also changed my navigation type from buttons to swipe gestures and the issue persists on landscape only
