### ISSUE TITLE
Bookmarks: Final Touches

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/pocket-casts-android#1307]
### Player
- [x] Rename the Show Notes tab to 'Details' (https://github.com/Automattic/pocket-casts-android/pull/1311)
- [x] Show the Add Bookmark option even if bookmarks are not unlocked (https://github.com/Automattic/pocket-casts-android/pull/1332/commits/f2a946e1307516950cb08b4fc4e8d77b8bb3d35c)
    - Tapping it should show the upsell

### Upgrade View
- [x] Show the Pocket Casts logo image instead of text (https://github.com/Automattic/pocket-casts-android/pull/1311)
- [x] Change the upgrade button title to be: (https://github.com/Automattic/pocket-casts-android/pull/1331)
   - If the tier has a free trial: `Start Free Trial`
   - If not: `Upgrade to X`
      - Where X is name of the tier (Plus, or Patron)

### Empty State
- [x] The text color of the title appears too light (https://github.com/Automattic/pocket-casts-android/pull/1311)

### Bookmarks List
- Bookmarks may not display if the episode is archived
   - I'm not able to reproduce this one again but noting it here since it came up - (Unable to reproduce)
- [x] The oldest/newest sort options are reversed
    - When sorting Oldest to Newest displays the newest bookmark first, and newest to oldest shows the oldest bookmark first. (https://github.com/Automattic/pocket-casts-android/pull/1321)
- [x] Store the sort option on a "per list" basis where each bookmark lists option is saved separately (https://github.com/Automattic/pocket-casts-android/pull/1321)

### Player Bookmarks 
- [x] Select All Above/Below is not selecting any bookmarks (https://github.com/Automattic/pocket-casts-android/pull/1321/commits/e48dacf2ad3fcc660ac800472771597984012918)
- [x] Select All only selects the last item (https://github.com/Automattic/pocket-casts-android/pull/1321/commits/e48dacf2ad3fcc660ac800472771597984012918)

### Podcast Bookmarks
- [x] Display the episode title in the bookmark row (https://github.com/Automattic/pocket-casts-android/pull/1311)
- [x] When sorting by Episode, the bookmarks are sorted by oldest episode first, but should be sorted by newest. (https://github.com/Automattic/pocket-casts-android/pull/1311)
- [x] When searching (https://github.com/Automattic/pocket-casts-android/pull/1311)
    - [x] If there are no search results while typing the search field is replaced with the 'No Bookmarks yet' view
    - [x] If there are no results we should display the empty state with:
        - Title: `No bookmarks found`
        - Subtitle: `We couldn't find any bookmarks for that search.`
        - Button: `Clear Search` 

### Bookmark Indicator Icon
- [x] The icon doesn't appear in other episode lists (filters, starred, listening history, downloads) (https://github.com/Automattic/pocket-casts-android/pull/1328)
- [x] Change the icon to use the podcast tint color (https://github.com/Automattic/pocket-casts-android/pull/1432)

### Headphone Controls
- [x] Display the Add Bookmark option if the user does not have bookmarks unlocked (https://github.com/Automattic/pocket-casts-android/pull/1319)
   - Slack Ref: p1692812869174489-slack-1692162285.498199
- [x] Add the confirmation tone (https://github.com/Automattic/pocket-casts-android/pull/1433)

### What's New
- [ ] Add What's New for Bookmarks

**Comment by CookieyedCodes** [comment]
Renameing shownotes tab to Details seems a weird choice choice to me 😅, looking forward to this feature whenever it comes to plus 😉 ❤️❤️
