### ISSUE TITLE
Android using legacy login APIs

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#131]
We noticed when we were testing some other things that Android appears to be calling the `security/login` method instead of `user/login`. In the API server it treats those as "legacy calls":
```
// go through a body handler for the legacy calls.
router.routeWithRegex("\\/security\\/.*|\\/stats\\/summary|\\/sync\\/update")
```

We should look into why that is and change over if we can.

**Comment by geekygecko** [comment]
This has been fixed in this [pull request](https://github.com/Automattic/pocket-casts-android/pull/685/files).
