### ISSUE TITLE
Search Term Persists When Navigating to Different Podcast Page

### ISSUE THREAD

**Issue by thabotswana** [Automattic/pocket-casts-android#1320]
### Description

After searching for episodes on a podcast page, the same search term remains present after navigating to a new/different podcast feed's episode search section. 

It should not be necessary to manually delete the search words in order to view the next feed's full episode list.

### Step-by-step reproduction instructions

1. Go to a podcast page
2. Search for an episode using the "Search episodes" field
3. Navigate to a different podcast page

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/35628116/fb53830a-171c-434f-8f30-1f46bd5e88cd

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung SM-S918U wAndroid 13, Pocket Casts 7.45

**Comment by thabotswana** [comment]
Another report in 6810141-zd-a8c

>I've noticed recently that searching for something in a podcast feed reflects in other podcast feeds when opening them.
>
>To make it clear:
>
>1. I search for 'movie' in Podcast A's feed, on the discovery bottom tab 
>2. I open Podcast B's feed on the filter bottom tab and the word I searched for in Podcast A (movie) is now in the search box of Podcast B
>3. I open Podcast C's feed on the Podcasts bottom tab and the word I searched for in Podcast A (movie) is now in the search box of Podcast C

App version : 7.46.2 (9140)
Phone: samsung - Galaxy M62 - SM-M625F - m62
Android version: 13 SDK 33

**Comment by MtndaleRedneck** [comment]
Noticed this too. Super annoying. Didn't use to be this way.

**Comment by joashrajin** [comment]
+1 7654468-zd-a8c
