### ISSUE TITLE
In landscape, spacing of icons on Now Playing screen is inconsistent

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1330]
### Description

When viewing the now playing screen in landscape mode, the spacing of the icons is inconsistent on some devices.

### Step-by-step reproduction instructions

Open the Now Playing screen with your phone/tablet in landscape.

### Screenshots or screen recording

![1000063804](https://github.com/Automattic/pocket-casts-android/assets/4656348/f576db51-6199-45e2-a237-aa7d401d4515)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pixel 7 Pro, Pixel 6 Pro, Samsung M34
Android 13
7.45.1, 7.46-rc-2

I am _not_ observing the issue on my Samsung A13 running Android 13 and PC 7.45.0, so the issue does not seem consistent across all devices.

**Comment by mebarbosa** [comment]
I am not able to reproduce this issue in 7.54-rc-4. I tried with Pixel 7 Pro Android 13 emulator and Pixel Table Android 14
