### ISSUE TITLE
App freezing or not responsive starting in 7.45 or 7.46

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1378]
### Description

We have had a significant increase in the number of users reporting that the app is not responsive for them.

This issue was not immediately apparent because we had a seemingly-unrelated multiselect bug causing ANRs for many users starting in `7.45`. That the multiselect ANR bug has been fully fixed as of `7.46.2`, but we still have user reports of app freezing and not being responsive. This issue is to track that separate problem that still exists on `7.46.2`.

Here are some examples of the type of behavior our users are seeing:

>  seems if I choose a different podcast that I want to listen to it causes the freeze. It doesn't seem to happen by itself if I don't change things. A force close and reopen works.

>  I was able to see the badges but when I went into the podcast badge I was unable to see any episodes. I saw only a black lower half with icons for the “Podcasts grid, Filters, Discover and Profile” options. But now I can’t see even the podcast badges. I get an audible click that Pocketcasts is accepting the keystroke but the screen is mostly blank.

> The "freezing problem" is still there. Yesterday it worked for a moment but then the problem was back. 
> - I can't play/pause any podcast
> - I cannot edit (add, delete) my current playlist (one podcast is still displayed to be playing but it isn't)
> - infos about a podcast or one episode don't load in the "Podcast" and "filter" tab
> - force quitting the app and reopen doesn't do the trick

> **Note**
> We've had many reports that turning on airplane mode fixes the issue, but only temporarily.

### Step-by-step reproduction instructions

We have not been able to reproduce this issue.

**UPDATE** There's a new version 7.47 available on Google Play that addresses the issues. If they still persist,  you can connect with our support team as explained here: https://support.pocketcasts.com/contact-us/

**Comment by CookieyedCodes** [comment]
https://www.reddit.com/comments/16iojm6 some other examples, no issues personally for me on android 12 one plus Nord yet tho so hmmmm

**Comment by P-Burk** [comment]
Oh good (or not good), it's not only me. I had the same issue on the following specs:

App Version: 7.46.2
Phone: Samsung Galaxy S21 Ultra
Android Version: 13

I had originally thought this was a network/service issue, but I was having the freezes and hang ups on episodes that I had downloaded as well. I did go into the system app settings and clear the data + cache, which seems to have remedied the issue for me.

**Comment by mdrockwell** [comment]
App version : 7.46.2 (9140)
Phone: Samsung Galaxy s23

> Doesn't allow me to play, there are no updates for this bug

Asked for a screen recording and for Android version info.

**Comment by Bullish-Design** [comment]
Same issue here:

App version: 7.46.2 (9140)
Phone: Samsung Galaxy Note 20 Ultra
Android: 13

Can usually open my main homescreen (my podcasts are organized into 9 folders) but clicking on a folder fills the main UI box (under the header that says "Podcasts" and has the search and menu icons) with a blank black area. The minimized "now playing" UI bar at the bottom still exists, as does the 4 icons below that to access the different menu areas. The "now playing" UI is unresponsive. 

Searches also work, but similarly the app will not respond once you click on the podcast you've searched for. 

This happened a few weeks ago and I got around it by sideloading a previous release apk based on advice from another github issue at the time. I have not yet attempted the same fix but will update if/when I do so.

**Comment by lalunamel** [comment]
- Google pixel 4a
- Android 13
- 7.46.2

Can confirm this issue as well. Today it started working again after no changes, but when the issue appears I'll be sure to create a screen recording and post a logcat dump here.

Based on my experience with the issue so far, it doesn't appear that reproduction involves any interaction from the user - just start the app and it either will or won't work.

Here's what I notice when it's not working:
- On the Podcasts tab, all my podcasts are displayed properly
- Selecting a podcast by clicking on it opens the single podcast view, though no content loads - the background at the top is the correct color, but neither the podcast image nor the list of episodes displays.
- Clicking the play button on an in progress podcast does not cause the podcast to play
- PocketCast's persistent media control notification is still active when this problem occurs, though clicking on buttons on the media control notification has no effect.

**Comment by ashiagr** [comment]
All those coming to this thread, please watch out for v7.47 and report back if you still experience the issues.

**Comment by mchowning** [comment]
👋  @Inrumpo , that does sound really annoying. Could you access your logs in the app and email them to `support@pocketcasts.com`? You can access your logs from the "Help & feedback" screen in settings. There's a list icon at the top that will take you to your logs, and from there you can share them. Let me know when you do that, and I'll take a look.

**Comment by mchowning** [comment]
With the `7.47` the spike in ANRs was gone and the ANR rate was actually below the previous baseline, so closing this issue.  (internal ref: pdeCcb-3ku-p2)
