### ISSUE TITLE
App Crashes after Opening The Economist Podcasts Page

### ISSUE THREAD

**Issue by ezebecke** [Automattic/pocket-casts-android#138]
From Igotdes: 

User in [#5187327-zen](https://woothemes.zendesk.com/agent/tickets/5187327) reports that their app crashes daily when they open the page for The Economist Podcasts (https://nodeweb.pocketcasts.com/admin/podcasts/558366).

App version : 7.19.2 (7566)
Phone: Google - Pixel 4a (5G) - Pixel 4a (5G) - bramble
Kernel: 4.19.220-gadc60de00e3a-ab8172795 - abfarm-01373
Android version: 12 SDK 32
They have tried:

deleting all episodes from The Economist Podcasts
unsubscribing from The Economist Podcasts, restarting the app, and resubscribing
[App logs](https://github.com/shiftyjelly/pocketcasts-android/files/8617441/5187327-zen.txt) show:

> I 02/5 12:03:43 Observing podcast 262069e0-e7df-0132-0ef7-059c869cc4eb episode changes
> E 02/5 12:03:43 Fatal crash.
> java.lang.IllegalStateException: Couldn't read row 562, col 4 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
> User acknowledges the bug is minor, but would appreciate any support we can give.

**Comment by MiSikora** [comment]
This should be fixed by https://github.com/Automattic/pocket-casts-android/pull/1589

We should still migrate fetching our data in a paging manner but this is a bigger task and probably a project on its own.
