### ISSUE TITLE
pcandroid_filter_multi_select_exited is triggered even when not exiting multi select

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/pocket-casts-android#1380]
### Description

The `pcandroid_filter_multi_select_exited` event is always triggered when:
- Leaving dismissing the filter
- Closing the app
- Changing tabs

### Step-by-step reproduction instructions

1. Launch the app
2. Open any filter
3. Change tabs
4. 💥 You'll see `🔵 Tracked: filter_multi_select_exited ...` in the logs
5. Go back to the filter tab
6. 💥 You'll see `🔵 Tracked: filter_multi_select_exited ...` in the logs
7. Dismiss the filter
8. 💥 You'll see `🔵 Tracked: filter_multi_select_exited ...` in the logs
9. Open the filter
10. Close the app
11. 💥 You'll see `🔵 Tracked: filter_multi_select_exited ...` in the logs

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by geekygecko** [comment]
To make sure I'm understanding, you want the code to change so `filter_multi_select_exited` isn't reported when you navigate back to the filter tab? There should be no step 6, right?
