### ISSUE TITLE
Refresh Now button: Stuck on 'refreshing...'

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#139]
Originally reported by @joashrajin 

This is a very minor issue but may cause some users to think that the app is not refreshing. On our Android App, when you press 'Refresh Now', it sometimes gets stuck on 'Refreshing' and does not update that text unless you view another page (like Podcasts), then come back to the Profile Page. 

Android: 

https://user-images.githubusercontent.com/16253818/164415551-afb1ca17-2f7e-4ad3-8466-5c7fe1656077.mp4

iOS:

https://user-images.githubusercontent.com/16253818/164415590-ad27a328-6a8b-4f49-aff0-c85251000949.MP4

**Comment by MiSikora** [comment]
I believe this got fixed with https://github.com/Automattic/pocket-casts-android/pull/2164
