### ISSUE TITLE
Next chapter button ring not showing progress

### ISSUE THREAD

**Issue by b-aaron** [Automattic/pocket-casts-android#1424]
### Description

The next chapter button normally shows the progress within the chapter by filling the ring around it. This is not happening

### Step-by-step reproduction instructions

- Play a Podcast with chapters
- Advance within the chapter
- See that the next chapter button does not change
- Look in chapter tab, how far the chapter has advanced
- This does not get represented on the next chapter button

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/72910336/f2772b43-9eff-46e0-ba73-f15899fa9123

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Android 13
OneUI 5.1
Pocket Casts v7.48-rc-3

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `meduim priority` judging from the issue description. Please correct me if I'm wrong.
