### ISSUE TITLE
Unable to Select Text in Show Notes From Episode Details View

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#143]
Reported by @mdrockwell 

Steps to reproduce:

1. Navigate to an individual episode's show notes (not the currently playing show). Any episode in the Listening History or the Discover tab, for example.
2. Attempt to select text from the show notes.

This can be done from Now Playing's Notes view, but not from other episode details views on Android. Although, it can be done all of these locations from iOS.

**Comment by karacca** [comment]
I see that the WebView's `LongClickListener` has been turned of by @geekygecko on `EpisodeFragment:494`. When I removed these lines It works as you expected, but I don't completely understand why It turned off it the first place. 

@geekygecko If you recall the problem that made you to turned off this setting, maybe we can focus on solving that 🤔 

```kotlin
setOnLongClickListener { true }
isLongClickable = false
isHapticFeedbackEnabled = false
```

**Comment by geekygecko** [comment]
@karacca, I wonder if we had issues with long show notes and scrolling the page. But I have just tried this, and it doesn't affect it. Thanks so much for taking a look into this. I have raised a pull request https://github.com/Automattic/pocket-casts-android/pull/372.
