### ISSUE TITLE
Specific podcast will not play or download

### ISSUE THREAD

**Issue by StormtrooprDave** [Automattic/pocket-casts-android#1431]
### Description

https://www.blockedandreported.org/podcast

Since 2 weeks ago this podcast will not play or download on the android app.  It plays on the web player and also on spotify web player and Podcast Addict android app.

### Step-by-step reproduction instructions

Click to play an episode and it says queued for download but then says failed to download.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pixel 7 Pro
Android 13
V7.47 (9145)

**Comment by mchowning** [comment]
I'm able to stream and download episode 184 of the podcast on my Android phone, so I'm not sure what's going on here. 

Do you see anything noteworthy in the in-app logs when you try to play/download this podcast? You can see the in-app logs at Profile tab → ⚙️ → "Help & feedback", where there's an icon at the top of the screen that opens the in-app logs.

**Comment by StormtrooprDave** [comment]
[Log.txt](https://github.com/Automattic/pocket-casts-android/files/12785551/Log.txt)

I found this in the logs:

Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: java.net.UnknownHostException: Unable to resolve host "prfx.byspotify.com": No address associated with hostname

E 02/10 19:39:45 Download stopped, will retry with No restrictions. Run later. Episode 184: Oh God, No, Not This Again, Please Make It Stop 4d291c42-ae06-45a0-a4ac-7a539b2413c8 - java.lang.RuntimeException: au.com.shiftyjelly.pocketcasts.repositories.download.task.DownloadEpisodeTask$DownloadFailed: Unable to download podcast episode. Check your internet connection.

The internet connection was fine but I use Adguard to block ads on the phone. I disabled Adguard and the episode then played.

I checked the filter lists and didn't see anything I recognised but added Pockedcasts as an exception and it all works now. No other feeds were affected, only this one.
