### ISSUE TITLE
Upgrade to Premium freezes the app

### ISSUE THREAD

**Issue by neeldoshii** [Automattic/pocket-casts-android#1443]
### Description

Upgrade to Premium freezes the app this could be a high priority issues as this will affect people to convert to plus account, thus reducing plus members. 

I have testing this over debug, debug prod build not yet tested over release. 

### Step-by-step reproduction instructions

1. Have a non plus account (free) account. 
2. Go to Profile
3. Go to Settings 
4. Go to Pocket Casts Plus 
5. Click on any upgrade button

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/60827173/506b4f20-19ec-44b8-afd8-2ba9bbefe32a

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pixel 7

**Comment by CookieyedCodes** [comment]
From my understanding debug isn't connected to the servers so this is probably why 🤔

**Comment by neeldoshii** [comment]
Closing as the issue is irrelevant. Sorry for the inconvienience.

**Comment by CookieyedCodes** [comment]
@neeldoshii well I'd check or wait for a Dev to confirm but your call 😅

**Comment by mchowning** [comment]
The upgrade/purchase functionality isn't going to work on debug or debugProd builds because they can't communicate with Google about subscriptions, but the app shouldn't freeze like this even on debug builds, so this seems like a legitimate issue to me. Thanks for raising it @neeldoshii , I'll go ahead and reopen it.

I feel like this came up once before (and got fixed), but I can't seem to find the issue or PR now. 🤔

**Comment by neeldoshii** [comment]
Well, I closed the issue first because I was too naive to not test in towards release but did check over debug, debug-prod build. 

Well, it does makes sense that application should not freeze it completely on debug or debug-prod build.

Thanks for checking it Matt.

**Comment by neeldoshii** [comment]
@mchowning 

Can we do one thing, make the button non clickable only on debug builds so this will avoid calling the google subscription function and thus wont freeze the app. 

Dry run code
```
if debug build
    make button non clickable with toast (for new commers)
    
if release build
   call google subscription function
   ```

**Comment by neeldoshii** [comment]
also this issue is similar to #1158
