### ISSUE TITLE
Not requesting SCHEDULE_EXACT_ALARM permission

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1486]
### Description

Android now requires that user's explicitly grant permission for exact alarms and on an Android 14 emulator, I'm seeing that we are not able to sleep podcasts because of the missing permission.

We're currently catching the exception and asking the user to grant the alerms & reminders permission, but the way to do that is not at all obvious (to me at least). On stock Android you need to go to the Android system settings → `Apps` → `Special app access` → `Alarms & reminders` and then update the permission for Pocket Casts to "allowed".

It would be much better if we fired off the appropriate intent for the user to update this setting.

### Step-by-step reproduction instructions

1. Fresh install the app on an Android 14 device
2. Play a podcast
3. Try to set up a sleep timer
4. Observe the toast message
5. Observe the sleep timer does not start and a toast message is displayed saying "Unable to start timer. Please allow 'Alarms & Reminders' permission".

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 7 emulator running Android 14

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `meduim priority` judging from the issue description. Please correct me if I'm wrong.
