### ISSUE TITLE
Chapter Length Calculation Mismatch

### ISSUE THREAD

**Issue by azollafox** [Automattic/pocket-casts-android#1505]
### Description

When you look at a chapter length in the episode info versus when it is play it will show different times. See episode https://pca.st/ap314mdp for an example
![Screenshot_20231029-204141](https://github.com/Automattic/pocket-casts-android/assets/7907292/fc33b96f-2625-4879-873a-84ad65878fcc)
![Screenshot_20231029-204136~2](https://github.com/Automattic/pocket-casts-android/assets/7907292/b5a484d1-426d-41be-9ed9-7e0e7151897c)

### Step-by-step reproduction instructions

1. Play Episode https://pca.st/ap314mdp
2. In the now playing area open up the episode notes and check the chapter lengths
3. When playing the episode compare the play calculated chapter lengths to those from the episode info

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Phone: Google - Panther - Pixel 7 - panther
Kernel: 5.10.157-android13-4-00001-g5c7ff5dc7aac-ab10381520 - abfarm-release-rbe-64-2004-0044
Android version: 14 SDK 34
App version : 7.49 (9156)

**Comment by CookieyedCodes** [comment]
This has allready been fixed for 7.51 from my understanding

**Comment by mchowning** [comment]
> This has allready been fixed for 7.51 from my understanding

I'm guessing you're referring to https://github.com/Automattic/pocket-casts-android/pull/1461, but that was addressing some different issues. I can still reproduce this issue with a build from the most recent code (https://github.com/Automattic/pocket-casts-android/commit/399e3370e248eaa42e876b71262e4ffacd7db526).
