### ISSUE TITLE
Search treats punctuation as important for titles; but not for episodes

### ISSUE THREAD

**Issue by jamescridland** [Automattic/pocket-casts-android#1568]
### Description

A search for `eelerschoice` does not find the `Eeler's Choice` podcast. However, it does find episodes of the podcast (potentially because the episode description includes the Twitter handle of "eelerschoice").

A search for `eelers choice` does not find the `Eeler's Choice` podcast. However, it does find an episode entitles `Eeler's Choice` (potentially because the description includes a link with "eelers-choice" in it).

This was first reported [in this subreddit](https://www.reddit.com/r/pocketcasts/comments/183lbyy/another_request_to_fix_search/).

### Step-by-step reproduction instructions

1. Search for Eelerschoice or eelers choice
2. Watch as Eeler's Choice does not appear

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel running Android 14; but I'd suspect this is a search API issue.

**Comment by yaelirub** [comment]
Hey @jamescridland , We've just rolled out a fix to our search functionality, so now, apostrophes and spaces should no longer impact podcast search results.

**Comment by jamescridland** [comment]
Thank you! :)
