### ISSUE TITLE
Updating to target Android 14

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1569]
Android 14 has been fully released, so we want to update the Android app to target it. Google has not set a deadline yet for when we have to do that update yet, but based on past releases, it is likely that we won't have to do this update until sometime in the second half of 2024, but obviously we'd like to get it done sooner.

I started work on this a few weeks back, but I haven't been able to focus on this because I got pulled off to some other higher priority tasks. I did make some progress on that update, so this is to document where things stand so it will be easy for me or someone else to pick this up in the future.

Changes to verify and/or test

The necessary code changes so far [have been fairly minimal](https://github.com/Automattic/pocket-casts-android/commit/37416fb8952c64acca4437bfdffe2b609e089df9).

Interestingly, if you use the upgrade assistant in Android Studio Iguana there are some different items from the items that are listed in https://developer.android.com/about/versions/14/behavior-changes-14. I've included any item that appeared in either list below.

- [X] **Schedule exact alarms are [denied by default](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms).** Opened a PR adding the permission check and request (https://github.com/Automattic/pocket-casts-android/pull/1487).
- [x] **Foreground service types are required.** 
   - [X] Confirmed that all of our foreground services have a declared foreground service type in the manifest file
   - [x] Foreground service types added at runtime (https://github.com/Automattic/pocket-casts-android/pull/1684)
- [ ] Complete [Foreground Service Type declaration in Google Play Store](https://support.google.com/googleplay/android-developer/answer/13392821?sjid=16277240137512566862-NA#:~:text=When%20your%20apps%20target%20Android%2014%20and%20above%2C%20you%E2%80%99ll%20need%20to%20declare%20any%20foreground%20service%20types%20that%20you%20use%20in%20a%20new%20declaration%20on%20the%20App%20content%20page%20(Policy%20%3E%20App%20content)%20in%20Play%20Console%20.)
- [X] **Enforcement of BLUETOOTH_CONNECT permission in BluetoothAdapter.** We do use the getProfileConnectionState() method that requires this permission.
- [X] **OpenJDK 17 update: changes to regular expressions.** We don't use any groups in our Matchers, so this doesn't apply.
- [X] **Open JDK 17 update: UUID handling.** Increases in the strictness of the UUID checks shouldn't cause issues since we use valid uuids for our podcasts and episodes. Tested on an account with a lot of subscriptions to verify no issues.
- [x] **Open JDK 17 update: ProGuard Issues with `ClassValue`.** I don't believe we have any issues here because we do not directly use `Class.forName(...)` or the `ClassValue::computeValue` methods. The Android system does seem to use `Class.forName(...)` though, and a library could use it, so leaving this item unchecked until we do some smoke-testing with a proguarded release build.
- [X] **JobScheduler reinforces callback and network behavior: onStartJob and onStopJob must return within a few seconds to avoid ANR.** We kick off other threads and return quickly when calling onStartJob and we don't do any work in onStopJob.
- [X] **JobScheduler reinforces callback and network behavior: declare the ACCESS_NETWORK_STATE permission if using setRequiredNetworkType or setRequiredNetwork constraint.** We declare this permission in the phone and wear apps. We don't declare this or any other permissions in the automotive app. I'm not really sure why that is but it seems to be working fine.
- [x] **Restrictions to implicit and pending intents.** It doesn't look like we're violating these restrictions, but it's hard to tell for certain solely by looking at the code. We need to test all the ways that intents can get sent to the app (Google Home, media notifications, new episode notifications) to make sure there are no regressions.
- [X] **Runtime-registered broadcasts receivers must specify export behavior.** The only things we do this for are for system broadcasts, and for those we should not specify export behavior [link](https://developer.android.com/about/versions/14/behavior-changes-14#system-broadcasts)
- [X] **Safer dynamic code loading.** I do not believe we dynamically load code anywhere in the app, so this does not affect us.
- [X] **Additional restrictions on starting activities from the background.** The only place we were trying to send a PendingIntent and start an activity in the background was not used and has been removed in https://github.com/Automattic/pocket-casts-android/pull/1489. The only place we're binding to a service is in our tests.
- [X] Grant partial access to photos and videos (this also comes up in the Play Store Policy Updates – Announcement October 25, 2023, internal ref: pdeCcb-3E5-p2) (N/A pdeCcb-3E5-p2#comment-2955)
- [X] **Zip path traversal.** We don't use ZipFile(String) and ZipInputStream.getNextEntry() in the app.
- [X] **User consent required for each MediaProjection capture session.** Our app does not use MediaProjection#createVirtualDisplay.
- [x] Smoke test release builds of all apps (automotive, phone, wear)

**Comment by notandyvee** [comment]
Heads up @mchowning . I am also investigating this on the WP side.

> Runtime-registered broadcasts receivers must specify export behavior. The only things we do this for are for system broadcasts, and for those we should not specify export behavior [link](https://developer.android.com/about/versions/14/behavior-changes-14#system-broadcasts)

My understanding is declaring them in the manifest also counts as an application register. See the [receiver docs](https://developer.android.com/guide/topics/manifest/receiver-element). So adding an export field in `<receiver android:name="au.com.shiftyjelly.pocketcasts.endofyear.ShareResultReceiver" />` would cover us. Tbh I am not sure if my understanding is correct. Figured starting the conversation and being corrected if I am wrong still helps!
