### ISSUE TITLE
Pixel headphones double/triple tapping to go forward/back does not work

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1578]
### Description

It doesn't seem that double/triple tapping to go forward and backward works like it should (at least on Pixel phones). I did some testing of that functionality on different phones and different apps to see where it worked/didn't-work and this is what I found.

|                  | Pixel 8 | Samsung A13 |
|---------------- | --------- | -------------|
| Pocket Casts ⏩  |   ❌    |     🟢      |
| Pocket Casts ⏪️️  |   ❌*    |     ❌      |
| YouTube Music ⏩️️ |   🟢    |     🟢      |
| YouTube Music ⏪️️ |   🟢    |     🟢      |
| Spotify ⏩️️       |   🟢    |     ❌      |
| Spotify ⏪️️       |   🟢    |     ❌      |
| Castbox ⏩       |   🟢    |     ❌      |
| Castbox ⏪       |   🟢    |     ❌      |
| Podbean ⏩       |   🟢    |     ❌      |
| Podbean ⏪       |   🟢    |     ❌      |

* I did notice that with Pocket Casts I would occasionally get a skip back to work, particularly if I just tapped the button a ton of times, but it basically never happened with normal use. It also looked like the playback might be updating it's position and then immediately jumped back to the previous playback position. If that's the case, we might be dealing with a race condition.

We do have some reports of this functionality working fine with Pixel Buds too, so not sure why it's working for some people and not others.

#### References
* [Pocket Casts Forums - Skip function from Bluetooth device not working properly – Beta 7.52-rc-2 (9162)](https://forums.pocketcasts.com/forums/topic/skip-function-from-bluetooth-device-not-working-properly-beta-7-52-rc-2-9162/?view=all#post-2099)
* 7382261-zd-a8c
* 7353758-zd-a8c

### Step-by-step reproduction instructions

1. Play an episode on pocket casts
2. Connect a pair of Pixel headphones (I was using wired, but we have quite a few reports from users having the issue with Bluetooth pixel buds)
3. Double tap to go forward
4. Observe the the audio pauses and unpauses but the playback position does not change
5. Triple tap to go backwards
6. 4. Observe the the audio pauses and unpauses but the playback position does not change

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung A13, Android 13, Pocket Casts 7.53 pre-release build
Pixel 8, Android 14, Pocket Casts 7.52-rc-4

**Comment by bgiesing** [comment]
Same issue here with 7.53-rc5 on Android 14 AP11.231020.016.A1 on Pixel 6a but oddly only with my Sony WH-1000XM4 headphones, my Pixel Buds A Series work perfectly fine.

The Pixel Buds always work while the Sony headphones very rarely work too but 95% of the time don't. Play/Pause doesn't work either, the headphones make a sound that it recognises the gesture but nothing happens.

**Comment by hmayer00** [comment]
Same issue with Pixel Buds A and Pixel 4A. Thanks for writing this up.

**Comment by rpardee** [comment]
Same--pixel buds A and pixel 6A. PocketCasts v7.52 (9168). Android version 14 w/November 2023 security update.

**Comment by hmayer00** [comment]
@mchowning Do you know if this likely to get fixed soon? It's frustrating enough that I'll likely sideload 7.51 if it's gonna be a while, but I'll just deal with it if it's expected to be fixed quickly. Thanks.

**Comment by mchowning** [comment]
👋 @hmayer00 

> Do you know if this likely to get fixed soon?

I'm planning to work on it this week.

>  It's frustrating enough that I'll likely sideload 7.51 if it's gonna be a while, but I'll just deal with it if it's expected to be fixed quickly. Thanks.

Are you saying this wasn't an issue in `7.51`? I didn't realize this was a recent-ish regression.

**Comment by rpardee** [comment]
FWIW, I've only noticed the issue for a couple of weeks. Thanks for looking into it.

**Comment by kylemckelvey16** [comment]
I have the same situation with Pixel buds A and a Pixel 7 and pocketcasts. Only having to switch to pocketcasts because Google is getting rid of Google podcasts which is so annoying

**Comment by mchowning** [comment]
We believe we have a fix for this in the [`7.54-rc-3` beta release](https://github.com/Automattic/pocket-casts-android/releases/tag/7.54-rc-3), which we've submitted to Google for review. If you get that version, please let me know if it fixes the issue for you.

**Comment by mchowning** [comment]
W're still working on getting `7.54-rc-3` approved by Google. 

Also, there is [a separate issue](https://github.com/Automattic/pocket-casts-android/pull/1620) that many apps seem to have where Pixel Buds cannot resume playback intermittently. When that is happening, the Pixel Buds also cannot skip forward or backward, although voice commands through the Pixel Buds to skip forward/backward seem to work even when that is happening.

**Comment by bgiesing** [comment]
7.54-rc-3 is still having the same issue for me on my Sony WH-1000XM4's, still working on Pixel Buds like it did before for me. Probably a separate issue for me then

**Comment by mebarbosa** [comment]
I am closing this one since we don't have more reports related to this issue. We believe this [PR](https://github.com/Automattic/pocket-casts-android/pull/1818) fixed it.

**Comment by rpardee** [comment]
Hasn't bothered me in months--thanks!
