### ISSUE TITLE
Bookmark added notification feedback

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1595]
When a `Bookmark added` notification is displayed, then
- on tapping the notification, display the bookmarks tab from the episode screen instead of the player screen 
- add an option to delete the bookmark from the notification

Feedback reported here:
https://pocketcastsbeta.slack.com/archives/C0GKY84CR/p1701786979207639
 
<img width=300 src="https://github.com/Automattic/pocket-casts-android/assets/1405144/32166aec-66b9-4869-801f-d6395219efc7"/>

### Steps to get the `Bookmark added` notification

1. Open the app 
2. Login with a paid account
3. Go to `Profile` -> `Settings` -> `Headphones controls`
4. Enable `Add bookmark` for `Previous` or `Next` action
5. Connect headphones with support for `Previous` or `Next` action
6. Play an episode
7. Minimize the app
8. Double or triple-tap the headphone (based on whether the `Previous` or `Next` action is enabled above)
9. Notice that Bookmark added notification is displayed
10. Notice `Change title` option is displayed <----- Add an option to delete a bookmark from the bookmark
11. Tap to view the bookmark
12. Notice that it goes to the `Player` screen -> `Bookmarks` tab of the currently playing episode <----- Change this behavior to open the `Bookmarks` tab from the `Episode` screen for the episode for which the bookmark is added

**Comment by mchowning** [comment]
Can this be closed @ashiagr ?

**Comment by ashiagr** [comment]
Yes, these should be available in v7.54-rc-4 currently in review by Google.
