### ISSUE TITLE
Display episode artwork in more places in the app

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1608]
In https://github.com/Automattic/pocket-casts-android/pull/1599 we added episode artwork to the full-screen player and the episode details screen, and we now want to use it in more places in the app. The current suggestion is to add it to the:

MiniPlayer | Bookmark row (Podcast screen) | Notification | Widget
---|----|---|---
![miniplayer](https://github.com/Automattic/pocket-casts-android/assets/1405144/0157b6a7-b0b7-41e6-863f-078970f00f02) | ![bookmark](https://github.com/Automattic/pocket-casts-android/assets/1405144/5af57e4d-ee6f-4978-abc6-7c626eb7ca27) | ![widget](https://github.com/Automattic/pocket-casts-android/assets/1405144/85f0ad6f-9298-48d8-9210-050f48ed805e) | ![widget1](https://github.com/Automattic/pocket-casts-android/assets/1405144/6835cf72-8849-46c5-8c51-0dd87e50a8d1)

@ashiagr  brought this up [here](https://github.com/Automattic/pocket-casts-android/pull/1599#pullrequestreview-1774364673), and @david-gonzalez-a8c shared his thoughts [here](https://github.com/Automattic/pocket-casts-android/pull/1599#issuecomment-1852267611). @b-aaron [said](https://github.com/Automattic/pocket-casts-android/pull/1599#issuecomment-1850851452) they would like to have a setting for whether to use the episode artwork in the notification.

**Comment by Mukuljangir372** [comment]
@mchowning @ashiagr Picking this one:)
