### ISSUE TITLE
Episode description display issue on localized screen

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#162]
4625833-zen:

> When the title of the podcast episode is so long, that it needs 3 rows for the title, the description text below gets pushed down and not all of the text is visible anymore, even when scrolling to the absolute bottom.
When the title only needs 2 lines, the bug doesn't happen.

@reginabally  was able to reproduce this when she changed the phone's language to German language (Deutsch).

Steps to reproduce:

1) Change the phone language to Deutsch.
2) Go to this podcast page in the app: https://pca.st/hv3N
3) Look for the episode "Magazin Spezial: Blockchain, NFTs und was zur Hölle soll das alles?" published on December 15, 2021.
4) Noticed the display of the episode description is incomplete and there's no way to scroll to view the bottom of the text.

Version: Android, 7.19.1 (7326)
Phone: Samsung Galaxy S20 Plus

<img width="350px" src="https://user-images.githubusercontent.com/40906847/150246022-d877c7e9-6c75-41c4-a261-d336ae10059f.jpg" />

**Comment by erricgunawan** [comment]
> I'm occasionally having cut-off podcast descriptions like in this screenshot:

<details>
  <summary>Screenshot:</summary>
  <br>
  
![img2](https://user-images.githubusercontent.com/1813857/195540003-94bb37be-275e-440c-ad38-5c3dd06b2c56.png)

  
</details>

> This happens with only some episodes from different podcasts, at different heights of the description. Unfortunately, I couldn't find a pattern to when this occurs.

> Android v7.24-rc-1 

5622057-zen

**Comment by erricgunawan** [comment]
> It's a great app (it realy is!), but it really needs...
>
> ...a fix when displaying the episode description. Sometimes it only shows the text for a very short time and then only a blank page. I've made a screen recording (see attachment).

<details>
  <summary>Screen Recording:</summary>
  <br>

https://user-images.githubusercontent.com/1813857/195796336-e28b6c52-8349-4af7-95f6-bf063f0e02f7.mp4


  
</details>

> Android  v7.23

5626166-zen
