### ISSUE TITLE
Incorrect playback speed shown on the media notification

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1648]
### Description

Playback speed shown on the media notification does not match with what is set inside the app.

### Step-by-step reproduction instructions

1. Play an episode
2. Open full-screen player
3. Tap the effects option on the bottom shelf
4. Change playback speed
5. ✅ Notice that media notification displays the correct playback speed
6. Force stop the app 
7. Reopen the app
8. Play the last episode
9. ❌ Notice that media notification displays incorrect playback speed. It defaults to 1. 

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/1405144/2b3d4641-9124-4feb-9077-b82f6d5e58a2

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 7, Android 14, v7.54-rc-4

7489526-zd-a8c
7485836-zd-a8c

**Comment by EnigmaSolved** [comment]
Grateful to see that a fix for this is forthcoming! :)
