### ISSUE TITLE
In landscape icons are not correctly aligned (on a Samsung Galaxy Tab S8)

### ISSUE THREAD

**Issue by matteozel** [Automattic/pocket-casts-android#1652]
### Description

When opening Pocket Cast on an Galaxy Tab S8 (One UI 6.0/Android 14) in landscape mode, the icons (both the 2 icons visualization options) are wrongly aligned, resulting in being cut on the top or the bottom. 
The only way to restore the correct allignement seems to me to reorder the podcast manually, but as soon the app is closed and reopened the issue will be there again. 
Having the app running in landscape but not in full screen resulta in a correct scaling of all th elements of the ui.

### Step-by-step reproduction instructions

1. Open Pocket Cast
2. Turn in landscape mode

### Screenshots or screen recording

![immagine](https://github.com/Automattic/pocket-casts-android/assets/3006006/4ec9e494-c34a-437d-8270-b484fd0ba1c1)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pocket Cast: 7.53 (9174)
Android 14
Samsung Galaxy Tab S8 One UI 6.0

**Comment by mebarbosa** [comment]
Thanks for reporting this issue! I can confirm this issue was fixed.

I've tested in 7.64
![Screenshot_20240529_100003](https://github.com/Automattic/pocket-casts-android/assets/42220351/08179f2f-ff1c-4028-88bf-5436ebde9577)
