### ISSUE TITLE
Flicker in folder sort order 

### ISSUE THREAD

**Issue by azollafox** [Automattic/pocket-casts-android#1661]
### Description

The folder order flickers when you switch between the `Podcasts` screen and any other screen

### Step-by-step reproduction instructions

1. Open `Podcasts` screen 
2. Add folders
3. Sort folders manually by dragging and dropping
4. Open another screen in the app
5. Return to the `podcast screen

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/7907292/e79eca36-d430-4f22-9005-ff255a08b20b

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Me: Google Pixel 6 Pocket Casts App version : 7.53 (9174)
User: Phone: Xiaomi - Smart TV - 22101320G - redwood Android version: 13 SDK 33 App version : 7.53 (9174)

**Comment by geekygecko** [comment]
It seems to load a different folder temporarily. 

https://github.com/Automattic/pocket-casts-android/assets/308331/7c60e258-4b67-4166-85fa-6497bbd5efd7

It starts as:
<img width="239" alt="Screenshot 2024-05-15 at 12 45 26 PM" src="https://github.com/Automattic/pocket-casts-android/assets/308331/752c6885-6617-4e1d-aa56-a9e3fb070fbb">

Then switches to this:
<img width="274" alt="Screenshot 2024-05-15 at 12 45 34 PM" src="https://github.com/Automattic/pocket-casts-android/assets/308331/5201272c-8076-4a4b-838f-c133f5fb7532">

And goes back to:
<img width="254" alt="Screenshot 2024-05-15 at 12 45 40 PM" src="https://github.com/Automattic/pocket-casts-android/assets/308331/4f710c15-1373-4eb2-a4b2-80da091e6ad6">

**Comment by ashiagr** [comment]
With the default `ViewCompositionStrategy.DisposeOnDetachedFromWindowOrReleasedFromPool` set for the folder compose view, the view seems to be reused on switching between tabs:

<img width="400" alt="folder flicker" src="https://github.com/Automattic/pocket-casts-android/assets/1405144/9bb110b1-508c-49f0-9d81-35db3007bb09">


Changing `ViewCompositionStrategy` to `DisposeOnDetachedFromWindow`  for the folder compose view fixes the flicker but can cause performance issues. As `FolderViewHolder` already uses compose views, it might be best to convert `PodcastViewHolder` also to `Compose` and remove this interoperability.

**Comment by ashiagr** [comment]
We're not ready yet to replace the entire RecyclerView with Compose because of the lack of in-built Compose drag-and-drop functionality for the lists. 

I temporarily changed the view composition strategy for folders to fix the issue in https://github.com/Automattic/pocket-casts-android/pull/2252. Folders used for grouping should be less in number and not cause performance issues.

**Comment by ashiagr** [comment]
A temporary fix is applied in #2252. I'm closing for now.
