### ISSUE TITLE
Hide Archived disabled when searching for podcast episodes

### ISSUE THREAD

**Issue by azollafox** [Automattic/pocket-casts-android#1663]
### Description

When searching for podcast episodes in the podcast page all episodes, including archived episodes always show. The usual spot where a user can hide/show archived episodes does not work. Hide episodes is always displayed here. 

### Step-by-step reproduction instructions

1. Archive some episodes on a podcast
2. Search on the podcast page for episodes that will match both archived and unarchived episodes
3. Try taping on the `hide archived` button

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/7907292/aadeb4f8-77e9-4249-81a9-41011677ae91

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6 Android 14 Pocket Casts 7.53

**Comment by CookieyedCodes** [comment]
In my own personal opinion I don't see this as a bug as I view the episode search as global, tbc tho if it is fixed I would prefer it to be an option 😅

**Comment by mebarbosa** [comment]
Thank you for taking your time reporting this. I've just confirmed with our team that this is an expected behavior, but we are going to keep your feedback tracked.
