### ISSUE TITLE
Add setting to toggle episode artwork from podcast feed

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1709]
### What problem does this address?

In pull request #1599, we began showing episode artwork from the podcast feed via show notes endpoint. This overrides podcast artwork and displays episode artwork if available in the podcast feed without giving an option that allows users to switch back to viewing the standard podcast artwork.

7595144-zd-a8c
https://forums.pocketcasts.com/forums/topic/disable-episode-artwork

### What is your proposed solution?

Add a setting to toggle between episode artwork from podcast feed and standard podcast artwork 

A similar setting is available for embedded artwork under `Profile` -> `Settings` -> `Appearance` that toggles between embedded artwork in the downloaded episode (if available - e.g. https://pca.st/7hesqiu3) and standard podcast artwork. The new setting can be added below it.

<img width=320 src="https://github.com/Automattic/pocket-casts-android/assets/1405144/994fb06f-e46a-4086-97f6-7d58106c83a5"/>

**Comment by CookieyedCodes** [comment]
To be clear the difference is MP3 artwork vs  RSS artwork, it might be nice to have an eye icon on the player icon if it has the other artwork & would allow a quick toggle if people are interested 🤔🤔

**Comment by owenlejeune** [comment]
This has bee driving me crazy! I didn't realize there were multiple sources for artwork and couldn't figure out why the embedded artwork toggle wasn't working. I just cloned this project again to look into this issue.
