### ISSUE TITLE
Horizontal artworks are cropped in the player view

### ISSUE THREAD

**Issue by MiSikora** [Automattic/pocket-casts-android#1719]
### Description

When a podcast episode has a horizontal artwork it is not displayed correctly. It is cropped instead of being fitted. I did some investigation and the bug was introduced with the fix in #1665. However, digging a little bit more it turns out that `coil.transform.RoundedCornersTransformation` is at fault. Commenting out this line fixes the issue.

https://github.com/Automattic/pocket-casts-android/blob/17d049450a9419d8aa6f9f84fabf67b6704e2b7c/modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt#L372

Supposedly we can fix it with a custom transformer mentioned here https://github.com/coil-kt/coil/issues/421#issuecomment-640133205. The linked implementation is no longer valid as the API changed but it can be probably used as an entry point for our implementation if I solve it this way.

I also tried updating Coil but that didn't help.

### Step-by-step reproduction instructions

1. Play [this episode](https://pca.st/episode/c7bc3a08-17b7-48c8-b5b9-dbdfd63211f4).
2. Open up the player.
3. You'll see a cropped artwork.

### Screenshots or screen recording

| With transformation | Without transformation |
| - | - |
| ![Screenshot_20240119-124053](https://github.com/Automattic/pocket-casts-android/assets/30936061/71d89d21-e92b-41cd-906e-5c1697da70bf) | ![Screenshot_20240119-124814](https://github.com/Automattic/pocket-casts-android/assets/30936061/4bf3864f-0417-473d-8142-8e75d7dd450d) |

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6, Android 13, Pocket Casts `7.55-rc-2 (9184)`

**Comment by Inrumpo** [comment]
Possibly connected to #1660 ?

**Comment by MiSikora** [comment]
> Possibly connected to https://github.com/Automattic/pocket-casts-android/issues/1660 ?

Yes, it looks like the same issue. Thanks!
