### ISSUE TITLE
Up next not closing when opening podcast through episode

### ISSUE THREAD

**Issue by b-aaron** [Automattic/pocket-casts-android#1730]
### Description

When opening a podcast's page through the up next page, the up next page doesn't close. The player, along with the up next page gets moved out of the way.
It isn't possible to reopen the player page through swiping and when clicking on the player bar, the up next page opens.

### Step-by-step reproduction instructions

1. Add episode to up next
2. Open player page
3. Open up next page (flinging or top right button)
4. Click on episode
5. Open podcast page
6. Try to open player page by swiping
7. Open player page by tapping
8. Up next page opens above player page

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/72910336/19beb4af-3c34-43ef-a0ca-3c65de3be597

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Galaxy S20 FE 5G
Android 13
OneUI 5.1
Pocket Casts 7.56-rc-1

**Comment by MiSikora** [comment]
Fix will be available with the `7.56-rc-2`.
