### ISSUE TITLE
Pressing "Play" from new episode notification overwrites currently playing episode if there are no other items in the playlist

### ISSUE THREAD

**Issue by rohandhruva** [Automattic/pocket-casts-android#1737]
### Description

For this bug, you should only have one podcast episode (say "A") currently playing, with nothing else in the playlist. Pause that episode. Then, if you get a notification about a new episode (say "B") released, and tap on "Play" in that notification's options, you'll see that the episode "A" is overwritten and "B" starts playing. I would instead expect "B" to start playing and "A" goes to the playlist to be played next.

This bug is not seen if you have other items in your playlist: "A" correctly goes to the top of the playlist when "B" starts playing. This bug is also not seen if you tap on "Play Next" from "B"'s notification. 

### Step-by-step reproduction instructions

Observed behavior:
1. Have one episode "A" playing, and "Up Next" playlist is empty
2. Pause it
3. See a new episode notification for episode "B"
4. Expand the notification, see "Play" and "Play Next"
5. Tap on "Play"
6. Episode "B" starts playing and "A" completely disappears

Expected behavior:
After step 5, "B" should start playing but "A" should be the next item in the playlist. 
This works correctly if you have items in the up next playlist. 

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 8 Pro, Pocket Casts v7.55 (9185). However, this bug has been around for as long as I can remember.

**Comment by geekygecko** [comment]
Thanks for reporting this but it's the expected behaviour. The idea is that you don't have to use the Up Next feature if you don't want to.
