### ISSUE TITLE
Bottom Controls Not in View - Must now Scroll Down

### ISSUE THREAD

**Issue by Scott8K** [Automattic/pocket-casts-android#1751]
### Description

The Bottom Controls are no longer in View.  If I want to Mark a current podcast 'As Played' by pressing the checkmark icon, I must now Scroll Down to bring the Bottom Controls containing the 'Checkmark Mark as Played' action control in view first before marking it.

### Step-by-step reproduction instructions

1. Open a podcast episode.
Bottom Controls are no longer in view on my phone (Samsung Galaxy JT320A).
In order bring Bottom Controls into view, must scroll down on every podcast episode.
This may be related to a recent previous Artwork Fix #1677.  Note that the artwork (podcast picture) fits fine within my screen, but now the Bottom Controls are no longer within initial view.  See attached Screen Shot. 

### Screenshots or screen recording

![Bottom Controls Not in View - Must now Scroll Down Example](https://github.com/Automattic/pocket-casts-android/assets/99505641/d306e53a-a114-40dc-bf1b-407db3f8db07)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung JT320A, Android 7.1.1, Pocket Casts 7.55 (9185)

**Comment by ashiagr** [comment]
👋 @Scott8K 

Thanks for reporting the issue. This should be fixed as part of https://github.com/Automattic/pocket-casts-android/pull/1742 in `7.56-rc-3`. It will be production in about a week, or you can join beta to check if it works for you.

**Comment by joashrajin** [comment]
+1 in 7626098-zd-a8c

**Comment by ashiagr** [comment]
7.56 with the fix is in production now.
