### ISSUE TITLE
Complete Advertising ID declaration for Android 13

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#178]
When releasing, the Google Play Store is telling us that we must complete the advertising ID declaration before we can release an app targeting Android 13.

![image](https://user-images.githubusercontent.com/4656348/181537226-6b96a8b1-abc9-4fa4-a0b9-541a287fb9ac.png)

**Comment by ashiagr** [comment]
Declaration updated and permission removed in: 
https://github.com/Automattic/pocket-casts-android/pull/312
https://github.com/Automattic/pocket-casts-android/pull/376
