### ISSUE TITLE
Deselecting Chapters

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1807]
Add the ability to deselect chapters and sync them between devices.

### Basics

- [x] Feature Flag (https://github.com/Automattic/pocket-casts-android/pull/1811)
- [x] Update the chapter UI to include way to choose which chapters to play (https://github.com/Automattic/pocket-casts-android/pull/1827)
- [x] While playing an episode and coming to the end of a chapter, skip to the next available chapter position (https://github.com/Automattic/pocket-casts-android/pull/1850)
- [x] Add skip chapters header (https://github.com/Automattic/pocket-casts-android/pull/1874)
- [x] Update design https://github.com/Automattic/pocket-casts-android/pull/1886

### Paid Feature

- [x] Add the locked UI if the feature is not available (https://github.com/Automattic/pocket-casts-android/pull/1880)
- [x] Show the upsell when tapped  (https://github.com/Automattic/pocket-casts-android/pull/1880)
- [x] Enable the feature for Patron under early access  (https://github.com/Automattic/pocket-casts-android/pull/1880)
- [x] Then Plus for full access  (https://github.com/Automattic/pocket-casts-android/pull/1880)

### Syncing

- [x] Send the selections to the server (https://github.com/Automattic/pocket-casts-android/pull/1916)
- [x] Apply incoming selections from the server (https://github.com/Automattic/pocket-casts-android/pull/1916)

### Watch

- ~~Skip deselected chapters on the watch when tapping the chapter next/previous buttons~~  - Chapter next/previous buttons not available in Wear OS app

### Other

- [x] Add What’s New (https://github.com/Automattic/pocket-casts-android/pull/1896) (need to update conditions)
- [x] Add the feature to the plus features list (https://github.com/Automattic/pocket-casts-android/pull/1895)
- [x] Tracks (https://github.com/Automattic/pocket-casts-android/pull/1887)
- [x] Disable for user files (https://github.com/Automattic/pocket-casts-android/pull/1939)

Feedback

- Our chapter titles in the player can be either 1 line or 2 lines which causes the content to jump. We also blink the skipped chapter artwork. (https://github.com/Automattic/pocket-casts-android/pull/1850#pullrequestreview-1884807457)

**Comment by CookieyedCodes** [comment]
Woop looking forward to this :), just a reminder I also would like RSS time tags to be converted to chapters as well under this project 😅, as I still find them more frequently used then RSS chapters & MP3 chapters 🤔

**Comment by CookieyedCodes** [comment]
I'll also add I am getting a irl friend to add a number of episodes sleep timer (code nearly their for android-I don't know a iOS dev unfortunately-, & David should be giving feedback on the UX soon 🤔https://github.com/Automattic/pocket-casts-android/discussions/1452 this links out to original discussion & my other niggles), a chapters sleep timer (few smaller niggles first 😅 *I can go into it if you want me to let me know on GitHub or the slack) & a few custom fields for user timers 😅

**Comment by ashiagr** [comment]
> I'll also add I am getting a irl friend to add a number of episodes sleep timer (code nearly their for android-I don't know a iOS dev unfortunately-, & David should be giving feedback on the UX soon 🤔https://github.com/Automattic/pocket-casts-android/discussions/1452 this links out to original discussion & my other niggles), a chapters sleep timer (few smaller niggles first 😅 *I can go into it if you want me to let me know on GitHub or the slack) & a few custom fields for user timers 😅

Let me ping @david-gonzalez-a8c for any design help. 🙇‍♀️  There might be a delay in response based on their current priorities.

**Comment by CookieyedCodes** [comment]
I have allready messaged him earlier in the week but thanks for the extra ping, the pr should be put in early next week regardless 👍
