### ISSUE TITLE
After upgrading an account to Plus, the confirmation screen says "Account Created"

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#182]
When upgrading an already existing free account to Plus, the confirmation screen says "Account Created". It feels like "Account Upgraded" would be more appropriate since this could be an extremely old account.

Would also be nice to fix the extra space above the close button at the top of the screen.

<img width="350px" src="https://user-images.githubusercontent.com/4656348/181626440-1553f12b-99de-4a7c-b65e-153c76098ec8.png" />

**Comment by owenlejeune** [comment]
I'd be happy to take a look at this
