### ISSUE TITLE
Widget uses custom Headphone controls instead of skipping

### ISSUE THREAD

**Issue by b-aaron** [Automattic/pocket-casts-android#1832]
### Description

When having custom headphone controls set up, such as adding a bookmark as the next action, pressing the skip button on the widget activates that.

### Step-by-step reproduction instructions

1. Go to Headphone Controls
2. Change Next action to Add Bookmark
3. Press Skip Forward on Pocket Casts widget
4. Notice a bookmark gets added and the podcast is not skipping ahead.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Galaxy S20 FE
Android 13 OneUI 5.1
Pocket Casts 7.57-rc-3

**Comment by mebarbosa** [comment]
Thank you for reporting this, @b-aaron! I've fixed it, and it will be addressed in the `7.85` version
