### ISSUE TITLE
The Details panel is not consistent

### ISSUE THREAD

**Issue by vivadavid** [Automattic/pocket-casts-android#1860]
### Description

The _Details_ panel provides different information depending on whether you access to it through the list of episodes of a podcast or through the playback of the episode.

### Step-by-step reproduction instructions

1. You go to a podcast, scroll down until you find an episode you like and tap on it.
2. You click on _Play_ to listen to the episode.
3. The panel is automatically minimized.
4. You tap to maximize it again.
5. Now the _Details_ panel contains different information. My main problem is that I can't find an icon to download the episode.

It's happened to me a couple of times: I start listening to an episode from a podcast and, at some point, I want to download it, but I can't unless I go back to the list of episodes of the podcast and find the specific episode I'm currently listening to.

The _Details_ panel should always stay the same. If there's some information that needs to be displayed only when the episode is being played, you could either combine all the information or just create a new panel.

### Screenshots or screen recording

The _Details_ panel when accessed through the list of episodes:

![details_panel_1](https://github.com/Automattic/pocket-casts-android/assets/9334287/4b8b3165-b0eb-4968-b063-db4eb2c9b495)

The _Details_ panel when the episode is being played:

![details_panel_2](https://github.com/Automattic/pocket-casts-android/assets/9334287/52e8e6f5-915a-480f-8bf8-beec3f916f08)

(For some reason, there's light mode in one screen and dark mode in the other one, but the screen modes on my phone don't always work well.)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Xiaomi mi 9T Pro, Android 11, Pocket Casts 7.57 (9193).

**Comment by vivadavid** [comment]
Hi,

I certainly value consistency: I don't understand how the same panel can look so different. In fact, it seems like a different panel despite the name.

Having said that, my main problem is the absence of a download button. It's happened to me a few times that I was listening to a podcast, I needed to download it and I was unable to do it unless I found again the episode on the list of the podcast.

The insertion of a download button would be extremely useful and time-saving.

**Comment by MiSikora** [comment]
The difference is there because part of `Details` in the episodes tab is in `Now Playing` of the player. Those are two different contexts.

cc: @david-gonzalez-a8c if you can weigh in on the design issue described here.

> The insertion of a download button would be extremely useful and time-saving.

I think the most reasonable solution without changing the design is to have download action as an option in the shelf items.

**Comment by david-gonzalez-a8c** [comment]
The refactoring of the episode and player views so they are more consistent (which I agree would be a good thing) would take a bigger design effort. In the meantime, I don't see a reason why we shouldn't add a "Download" action in the player "More actions" sheet.

I've prepared some [quick specs here](https://www.figma.com/file/hHFpI1RtnW4TRb448Q4Don/Player?type=design&node-id=1%3A2&mode=design&t=c2y0hm5AJYC4isZS-1) where you can grab the icon from. I suggest we add it before "Archive" on the list.

**Comment by vivadavid** [comment]
Hi,

On version 7.67, I've added the _Download_ button:

![IMG_20240709_131104](https://github.com/Automattic/pocket-casts-android/assets/9334287/2db043ee-d880-4543-bff8-b05bf574cb18)

And yet the _Download_ button doesn't appear anywhere on the bottom when I'm listening to my podcast:

![IMG_20240709_131146](https://github.com/Automattic/pocket-casts-android/assets/9334287/21052b87-ce6c-41fc-88c0-bac97706b710)

**Comment by vivadavid** [comment]
Hi,

I know that there are other issues to look into and I don't want to seem pushy, but it's been a while since the feature to download a podcast while you're listening to it was implemented and then removed. As nothing is mentioned in the changelog for version 7.70, I was wondering if there are plans to implement it again.

Thanks!

**Comment by CookieyedCodes** [comment]
@mebarbosa why was it removed again?

**Comment by MiSikora** [comment]
Because of https://github.com/Automattic/pocket-casts-android/issues/2477

**Comment by MiSikora** [comment]
@vivadavid I can download the episode while listening to it. Can you create a separate bug report for it?

@CookieyedCodes What do you mean by again? Was it removed at some point in the past?

**Comment by vivadavid** [comment]
@MiSikora , when I'm listening to an episode, I don't have a download button available at hand to download it. I have to go back to the podcast and find the episode.

**Comment by MiSikora** [comment]
Ah, yes. I didn't understand it at first. It is in our backlog as an open issue but we don't have immediate plans to implement.

**Comment by vivadavid** [comment]
> Ah, yes. I didn't understand it at first. It is in our backlog as an open issue but we don't have immediate plans to implement it.

Thanks! I keep my fingers crossed!

**Comment by CookieyedCodes** [comment]
Ya I think it was removed because it was taking up 3 spaces in the overflow menu or something like that (download, downloading & remove download)

Hopefully someday :)

**Comment by MiSikora** [comment]
Yes, it was due to this issue https://github.com/Automattic/pocket-casts-android/issues/2477

**Comment by CookieyedCodes** [comment]
Ah that's it 😉

**Comment by mebarbosa** [comment]
Hi @vivadavid @CookieyedCodes 👋🏽 

Thank you all for your patience. I am just letting you know that we added this feature [here](https://github.com/Automattic/pocket-casts-android/pull/3046) and it will be available in `7.76`

**Comment by vivadavid** [comment]
> Hi [@vivadavid](https://github.com/vivadavid) [@CookieyedCodes](https://github.com/CookieyedCodes) 👋🏽
> 
> Thank you all for your patience. I am just letting you know that we added this feature [here](https://github.com/Automattic/pocket-casts-android/pull/3046) and it will be available in `7.76`

Hi! Actually, I've just seen the notification for 7.75 rc 2 and I was wondering about my issue. I'm so happy to know that it's almost there. Thanks!
