### ISSUE TITLE
Playback Stops Before Episode Completion

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#1866]
### Description

This is not happening to every episode, but I noticed when I play the episode `Top 7 Grand European Journeys With Lucas Peters` from the podcast `Zero to travel podcast` with UUID: `be3072a9-e50e-4212-8a7b-e62817c78a9e` The playback is stopping a few seconds before the episode ends, typically around 10 seconds remaining.

### Step-by-step reproduction instructions

1. Go to  `Zero to travel podcast`
2. Add `Top 7 Grand European Journeys With Lucas Peters` to queue
3. Play the episode
4. Seek to the end of the episode. Let's say to 20 seconds remaining
5. Wait 
6. The playback is stopping before the episode ends

### Screenshots or screen recording

[unexpected playback stop call.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/f853dda4-4d42-4962-b4df-09a3a3ae6268)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pocket casts: `7.58-rc-1`

**Comment by MiSikora** [comment]
Can you check if you don't have `Skip last` setting set to 10 seconds for this podcast? In can see in the recording that you have 10 seconds set for `Skip first` so you might have it for `Skip last` as well.

**Comment by mebarbosa** [comment]
You are right! I missed this toggle 🫡

Thanks
