### ISSUE TITLE
Up Next: Multiselect: Removing episodes results in the wrong message being shown

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#1918]
### Description

If you use multiselect to remove episodes in bulk from the Up Next queue, it always says 0 removed no matter how many you remove

### Step-by-step reproduction instructions

1. Open you Up Next queue
2. Use Multiselect to choose some episodes you want to remove
3. Remove them, notice the popup on the screen mentioning 0 removed

### Screenshots or screen recording

![image](https://github.com/Automattic/pocket-casts-android/assets/16253818/fe783a8c-9f6d-487d-937d-e0e9827397d0)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Fold 4, Android 14, Pocket Casts 7.59-rc-1

**Comment by igotdes** [comment]
Google Play Store 2-star review:

> Up next section has a bug. If you remove episodes from here, a prompt will appear saying "0 episodes were removed from Up Next". The counter therefore isn't working. But removing is successful. Do you guys test the app before launching it?

I'm also still able to replicate this issue on 7.60-rc-2 (9202).
