### ISSUE TITLE
Unable to Scroll Down Details Screen

### ISSUE THREAD

**Issue by thabotswana** [Automattic/pocket-casts-android#1951]
### Description

When you swipe from the Now Playing screen to the Details screen, the app will not allow you to scroll down. You have to swipe to the next screen and then swipe back to get scrolling to work.

Reported by a user in https://forums.pocketcasts.com/forums/topic/issue-scrolling-in-podcast-details-screen/. I am able to reproduce this on my Samsung Galaxy S23.

### Step-by-step reproduction instructions

1. Go to the Now Playing screen
2. Left swipe to the Details screen
3. Observe that you cannot scroll the Details screen 
4. Left swipe to the next screen, then swipe back
5. Observe that you can now scroll the Details screen

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/35628116/1596b5af-bebb-4dd9-b072-4988230a362c

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 7a, Pocket Casts 7.58

**Comment by MiSikora** [comment]
This should be fixed in [`7.59`](https://github.com/Automattic/pocket-casts-android/blob/564dbf1a6eae0aeccc81a1bb54bde5588dda1fd7/CHANGELOG.md#759).

> Fixed an issue where bookmarks on description could become unresponsive. (https://github.com/Automattic/pocket-casts-android/pull/1873)

**Comment by MiSikora** [comment]
`7.59` is now released to 100%.
