### ISSUE TITLE
Podcast Standard Tags

### ISSUE THREAD

**Issue by MiSikora** [Automattic/pocket-casts-android#1955]
```[tasklist]
### Episode artwork
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1854
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1943
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1987
``` 

```[tasklist]
### Chapters
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1956
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1959
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1962
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1964
- [ ] https://github.com/Automattic/pocket-casts-android/pull/1965
```

```[tasklist]
### Transcripts
- [ ] https://github.com/Automattic/pocket-casts-android/issues/2398
``` 

```[tasklist]
### Funding
- [ ] TBD
```

**Comment by CookieyedCodes** [comment]
@MiSikora I know this is related to RSS tags but something to ask, how easy would it be to implement a local auto archive by word? (Originally going off tital but once an episode is auto downloaded it could check through the show notes for the word too)

Certain podcast networks like spamming new shows on their existing feeds when new stuff releases & I am not against that but I only want it to turn up once 😅 & I also have no interest in reruns, I might get a friend to implement it if PC dosen't want to do it but I'm interested in the complexity of such a task?

**Comment by MiSikora** [comment]
I can't tell. Off the top of my head it is neither trivial nor challenging.

I appreciate your eagerness, interest and involvement in Pocket Casts. Truly ❤️.  But I need to ask you to not use issues for random questions. Please use [Discussions](https://github.com/Automattic/pocket-casts-android/discussions), support channel, forums, or create a new issue if you have a concrete idea of how a feature should work.

**Comment by CookieyedCodes** [comment]
Coolio, Ya fair enough,

I actually have quite a few discussions 😅, but I'll do a more concerted effort in a few months :)

**Comment by TKramez** [comment]
Could handling the `<itunes:explicit>` tag be include in this issue?

**Comment by MiSikora** [comment]
Right now there are no plans to support this tag but I'll add your request to our internal board.
