### ISSUE TITLE
Plus Upgrade Page dialog dismisses on back to top scroll

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#197]
Scrolling the content in the "Plus Upgrade" page modal does not allow to scroll back to the top without dismissing the modal.

1. Launch the app and make sure you don't have plus active
2. Tap on the podcast tab
3. Tap on the new folder button
4. Notice that "Plus Upgrade" UI is shown 
5. Scroll the screen content (if the screen is not scrollable, switch to landscape mode)
6. Notice that it's not possible to scroll back to the top without dismissing the modal.

https://user-images.githubusercontent.com/1405144/182361021-08b3684b-51a6-40a6-801b-11f21849cb84.mp4

**Comment by mchowning** [comment]
This isn't an issue anymore since we switched to the new onboarding flow.
