### ISSUE TITLE
Embedded artwork: consolidate options into a single one

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/pocket-casts-android#1983]
## Goal

To have a single option for the user to opt-in to embedded artwork under Settings > Appearance.

Suggestion:

> Use episode artwork (off/on)
> Some shows have custom artwork for certain episodes. Enable this option and Pocket Casts will display them instead of the show’s artwork.

**Comment by MiSikora** [comment]
Which setting key should be used for syncing?

**Comment by leandroalonso** [comment]
@MiSikora `use_embedded_artwork_global` maybe makes more sense? I'm ok using any of them. :)

**Comment by MiSikora** [comment]
Sure, sounds fine 👍
