### ISSUE TITLE
Episode re-download issues

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1997]
### Description

Sometimes re-downloading an episode doesn't start downloading it, giving no error message. Restarting the app and clearing download errors doesn't help. 

### Step-by-step reproduction instructions

I wasn't able to reproduce it consistently. But here are the relevant logs when it happened:

```
I 01/4 11:50:27 Added episode to downloads. 07c532c0-130f-4efa-b3d2-940c806ed0a1 podcast: 4eb5b260-c933-0134-10da-25324e2a541d from: episode card
I 01/4 11:50:27 UpdateShowNotesTask - enqueued 07c532c0-130f-4efa-b3d2-940c806ed0a1
I 01/4 11:50:27 UpdateShowNotesTask (Worker ID: c445c758-d924-4f9c-8cae-818e13658cd5) - Worker started - podcast: 4eb5b260-c933-0134-10da-25324e2a541d
I 01/4 11:50:27 Episode From Serial: Season 4 - Guantánamo is archived in download task. Cancelling.
I 01/4 11:50:28 UpdateShowNotesTask (Worker ID: c445c758-d924-4f9c-8cae-818e13658cd5) - Worker completed - took 536 ms
```

After app restart:

```
I 01/4 11:51:47 App started. 7.60 (9206)
E 01/4 11:51:47 Workmanager knows about 07c532c0-130f-4efa-b3d2-940c806ed0a1 but it is marked as not downloaded.
```

This was also reported here and noticed similar logs shared via DM:

https://pocketcastsbeta.slack.com/archives/C013F9S9C2W/p1706099192189369?thread_ts=1705654797.569009&cid=C013F9S9C2W

Steps that helped me reproduce the issue:

1. Open a podcast episode
2. Tap `Download` button
3. Tap `Mark as played` button
4. Repeat steps 3 and 4 multiple times
5. Notice that after a point, tapping the download button doesn't do anything

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/1405144/0f2a14da-c238-4fcc-bc1c-a1e6e4e4880b

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pixel 7, Android 14, Pocket Casts 7.60 (can be reproduced on older versions as well)

**Comment by CookieyedCodes** [comment]
Thanks for continuing to look into it :)
