### ISSUE TITLE
Chapter Titles not showing in Player screen

### ISSUE THREAD

**Issue by b-aaron** [Automattic/pocket-casts-android#2000]
### Description

Previously, if chapter titles were available, they replaced the episode title in the Player screen. Recently, this behavior has changed to show the episode title. Is this behavior wanted, or is it a bug, that the chapter titles aren't showing?

### Step-by-step reproduction instructions

1. Play a podcast episode with chapter titles
2. Go to player screen
3. Notice episode title is being shown rather than the chapter title

### Screenshots or screen recording

![Screenshot_20240401_142837_Pocket Casts](https://github.com/Automattic/pocket-casts-android/assets/72910336/1d3272d2-e2f3-4df2-a855-05a25ee335db)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Galaxy S23 FE
Android 14 OneUI 6.0
Pocket Casts 7.61-rc-1

**Comment by CookieyedCodes** [comment]
Hmmmmmm do you know what type of chapters relay FM uses, because on 60 rc3 or 4 I did have it functioning, it might have been the new chapter types that wasn't coded as they didn't realise this functionality 🤔🤔

**Comment by b-aaron** [comment]
I had this happen in previous versions, too. So it isn't this, I assume.
@CookieyedCodes

**Comment by CookieyedCodes** [comment]
Hmmmmmm I definitely had it last last week 🤔🤔
