### ISSUE TITLE
Trim Silence: Next episode not playing automatically, hearing a clicking noise

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#2004]
### Description

Some users have reported a glitch where, upon an episode's conclusion, instead of advancing to the next episode in the "Up Next" queue, the player freezes and emits a buzzing or clicking noise. The episode timer anomalously continues beyond the episode's length. The issue can only be resolved by pressing the fast-forward button, which then proceeds to the next episode in the queue.

### Step-by-step reproduction instructions

1. Listen to a podcast like this: https://pca.st/bprwy2b9
2. Set the playback speed to 1.9x and set Trim Silence to Mad Max
3. Play the episode and notice at the end that it gets stuck at 0:00

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/16253818/3aed024c-4243-43fe-b4d8-73abaedcf175

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

App version : 7.61-rc-1
Android version: 14
Samsung Fold 4

**Comment by joashrajin** [comment]
7973252-zd-a8c

**Comment by joashrajin** [comment]
> I'm experiencing a bug that started in the last few weeks, sometimes when a podcast episodes ends, instead of going to the next one in Up Next, it freezes up and repeats a buzzing or clicking tone, while the timer continues to tick up - for example if the episode is 10:30 in length, the timer will show 10:31/10:30, 10:32/10:30, etc. the only way to stop the buzzing/clicking sound is to press the fast forward button, which immediately makes the player go to the Up Next episode. If the jump back button is pressed, one of two things happen: if the elapsed time since the end of the episode is less than the jump back time, then the episode starts playing from that time (e.g. 10:35/10:30, jump back 15 seconds, episode plays from 10:20/10:30). If the time since the end of the episode is greater than the jump back time, then the behavior is the same as pressing the jump forward button.
The buzzing/clicking sound sounds like it might be the last bit of audio from the episode playing on a very tight loop.

7970134-zd-a8c


```
App version : 7.59 (9200)
Phone: Google - husky - Pixel 8 Pro - husky
Android version: 14 SDK 34

```

**Comment by CookieyedCodes** [comment]
@joashrajin I think it's related to the exo player dependency update 🤔🤔

**Comment by CookieyedCodes** [comment]
I mentioned it did fix the android bugs with skipping back & forward on headphones tho at least(Sony's at least)😅, this bug also seems to happen is the speed is changed a few numbers in one go,

The only fix is skipping back and forth temporarily so at least it's fixable 😅 but ya might have to wait until google fixes it 🤔🤔

**Comment by joashrajin** [comment]
7921525-zd-a8c

**Comment by joashrajin** [comment]
@CookieyedCodes I did see that, but so far, we have not been able to replicate the issue. If you have any steps we should follow to replicate the problem, it would be much appreciated.

**Comment by joashrajin** [comment]
> Starting 1 - 2 weeks ago, the Android app has been getting stuck at the end of podcasts and not proceeding to the next podcast in the queue. You can hear a sound that's like a record skipping at the end. It's not every podcast, but it's most. Fast forwarding does nove to the next podcast and playback is normal until the end of the episode.

7974796-zd-a8c

**Comment by CookieyedCodes** [comment]
I am on android 12 on a one plus Nord so maby it's related to the android version 🤔

**Comment by joashrajin** [comment]
7893164-zd-a8c

**Comment by joashrajin** [comment]
7936857-zd-a8c

**Comment by joashrajin** [comment]
7935532-zd-a8c

**Comment by joashrajin** [comment]
7967781-zd-a8c

**Comment by ashiagr** [comment]
@joashrajin it appears to be related to `ExoPlayer`/ `Media3` update. I have raised an issue [here](https://github.com/androidx/media/issues/1244). 

Here are possible related issues from the library:
https://github.com/androidx/media/issues/538
https://github.com/google/ExoPlayer/issues/11267
