### ISSUE TITLE
Limit option for "newest X episodes" or "most recent X episodes" removed in most recent update

### ISSUE THREAD

**Issue by jxyzn** [Automattic/pocket-casts-android#2009]
### Description

I can no longer limit a feed or filter category to only the X most recent episodes. Filter allows limiting only by date (24 hours, 3 days, etc.)

Was this limit removed intentionally? Why?

### Step-by-step reproduction instructions

Tap and edit a filter and look for the limit to # newest episodes option.
Tap and edit a feed and look for the limit to # most recent episodes option.

### Screenshots or screen recording

![image](https://github.com/Automattic/pocket-casts-android/assets/245082/e3e75fa5-ccdc-413f-8623-029f56f41a8f)

Until this morning, that filter view would never contain more than 3 items as I had the "NPR News Now" feed limited to most-recent-2 and the "Up First" feed limited to most-recent-1.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pixel 6 XL, Android 14, 7.61-rc2 9209

**Comment by CookieyedCodes** [comment]
Was this ever like this? 🤔

**Comment by jxyzn** [comment]
I may be mis-recollecting how this feature worked, but it stopped in this updated release.

I had a filter containing the NPR hourly update feed and an NPR *daily* update feed. When I would go to the filter (until this morning) it had limits restricting the hourly feed to the latest-2-episodes, and the daily to the latest-1-episode.

Today, I see a dozen+ hourly episodes in that filter. I have made no changes to my subscriptions or filters in months.

**Comment by CookieyedCodes** [comment]
Hmmmm I wonder with the settings sync test yesterday it upset you auto archive limit episode functionality that might be what changed 🤔

**Comment by jxyzn** [comment]
Yes, I'm on the betas. And yes, it was the custom "Auto archive" setting for these podcast feeds that were lost. I have restored those. 

What was the settings sync test? Do you want to leave this open for tracking, open a new one, or just close it?

(I've noticed a few times recently that launching the idle app from the widget stops working and I have to delete and re-add the widget. Is this to be expected with the betas?)

**Comment by CookieyedCodes** [comment]
Gud gud, this is a tad expected then I suppose 

I actually don't work for automattic, just care deeply for pocketcasts, so it's up to them or you if you want to close it, the setting sync test was ended pretty quickly so their aware theirs issues (settings sync is practically everything in the app is going to be synced across devices which is going to be great) ,maby stay away from betas for a while 🤔, settings sync will be great but obviously it needs some work 😁

Their currently also redoing the widgits so while probably not related that probably won't be an issue soon either :)

**Comment by MiSikora** [comment]
Hey, @jxyzn. Sorry that you're experiencing this issue. However, I think you might be conflating podcast auto-archive settings with filters settings. You can limit how many episodes should not be marked as archived in the podcast settings. Those most likely got changed during our mentioned sync settings test.

![Screenshot_20240408-083919](https://github.com/Automattic/pocket-casts-android/assets/30936061/ab502b9b-52c4-43dc-a1ff-bbf0e1380d3b)
