### ISSUE TITLE
Save embedded chapters in the database

### ISSUE THREAD

**Issue by MiSikora** [Automattic/pocket-casts-android#2018]
Now that we have a table for storing chapters we can save embedded chapters in our database. This has two main benefits:

1. Single source of truth for chapters.
2. Improved offline handling. Once chapters are stored in the database we can access them without analyzing the media track for things like displaying in other places than player. It would still require for the file to be played at least once but it is an improvement.

Chapters should not be stored if the current chapters count for an episode is greater or equal to what we about to save.

**Comment by CookieyedCodes** [comment]
Will this also help provide a future for timetags chapters? 🤔🧐 😅

**Comment by CookieyedCodes** [comment]
Coolio, please consider it :)
