### ISSUE TITLE
All notification settings have been reset/deactivated

### ISSUE THREAD

**Issue by metzgore** [Automattic/pocket-casts-android#2021]
### Description

All my notification settings have been reset/deactivated. I just noticed randomly so I cannot say after which version update it might have happened.

### Step-by-step reproduction instructions

Just randomly noticed that the app probably did it by itself, so no user steps for reproduction

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 8 Pro with Android 14, Pocket Casts 7.61-rc-3 (9210)

**Comment by CookieyedCodes** [comment]
Their was a settings sync test last week, they probably got deactivated because of that, I would stay away from betas until they get this perfect, the team at pocketcasts is on it tho 🤔😅

**Comment by MiSikora** [comment]
We're aware of the issue that was caused on beta builds. As @CookieyedCodes mentioned it happened due to something going wrong with the test for syncing settings. I'll close this issue as there's nothing actionable on its own for this event.
