### ISSUE TITLE
Playback position resets when clicking on widget artwork

### ISSUE THREAD

**Issue by fuzzmz** [Automattic/pocket-casts-android#2073]
### Description

When clicking on the widget artwork to go to the podcast, the playback position resets to the beginning of the episode.

### Step-by-step reproduction instructions

1. Open app
2. Start playing episode
3. Pause playback
4. Go to homescreen
5. Tap on episode artwork from widget
6. Episode details tab opens
7. Play position resets to start of episode

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/1335181/10521a2f-a5b3-46ba-abe5-9c1ad769c1c5

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

OnePlus 5T
Android 10
Pocket Casts version 7.62-rc-2 (9215)

**Comment by MiSikora** [comment]
Thanks for the report. This was fixed with #2067
