### ISSUE TITLE
Auto Archive Played Episodes: Still occurring when setting is 'Never'

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#2083]
### Description

We have received a few reports from users on v7.61 mentioning that auto-archive is still occurring, even when that setting is set to 'Never' in the app. It seems to be just a few users affected. 

Internal Ref: p1713427004164729-slack-C02A333D8LQ

### Step-by-step reproduction instructions

1. Go to Settings > Auto Archive > Archive Played Episodes, and set it to 'Never'.
2. Finish an episode and check if the episode was archived or not

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pocket Casts v7.61, Pixel Tablet, Android version: 14 SDK 34

**Comment by joashrajin** [comment]
8045807-zd-a8c

**Comment by joashrajin** [comment]
7998858-zd-a8c

**Comment by joashrajin** [comment]
7994791-zd-a8c

**Comment by joashrajin** [comment]
8025453-zd-a8c

**Comment by joashrajin** [comment]
8024948-zd-a8c

**Comment by igotdes** [comment]
#8002885-zen

**Comment by igotdes** [comment]
> I just realized I’m getting the same thing. I don’t synchronizewith any other devices. I’m running Android 14 on a Pixel 5 with Pocket Casts version 7.61-rc-3.

https://forums.pocketcasts.com/forums/topic/played-downloaded-podcasts-now-automatically-getting-archived-and-deleted/?view=all#post-3488

**Comment by igotdes** [comment]
> I’m also affected. This is a fairly recent change, and adjusting the settings in the app (android, build 9210) doesn’t fix it. I had it set to 24 hours auto archiving, and now it’s off, but the episodes are still archived.

https://forums.pocketcasts.com/forums/topic/played-downloaded-podcasts-now-automatically-getting-archived-and-deleted/?view=all#post-3509

**Comment by igotdes** [comment]
> Yes I nnoticed I was having the same problem, but now I’ve also noticed for certain podcasts new episodes are getting archived before I’ve even played them. I’m not even receiving a notification that a new episode is available it’s like the episode is getting archived as soon as it’s available.

https://forums.pocketcasts.com/forums/topic/played-downloaded-podcasts-now-automatically-getting-archived-and-deleted/?view=all#post-3511

**Comment by igotdes** [comment]
> This is still happening in 7.62-rc-3 (9216).

https://forums.pocketcasts.com/forums/topic/played-downloaded-podcasts-now-automatically-getting-archived-and-deleted/?view=all#post-3601

**Comment by azollafox** [comment]
8066431-zen and 8124737-zen from the same user, with logs in 8124737

**Comment by MiSikora** [comment]
Fixed in #2194
