### ISSUE TITLE
Medium & large widgets not loading

### ISSUE THREAD

**Issue by fuzzmz** [Automattic/pocket-casts-android#2096]
### Description

Adding a medium or large widget doesn't work. When currently adding they state "Can't load widget". Tested on both the OnePlus Launcher and Nova Launcher.

### Step-by-step reproduction instructions

1. Add medium or large widget
2. The widget shows Can't load widget

### Screenshots or screen recording

![Screenshot_20240422-143252](https://github.com/Automattic/pocket-casts-android/assets/1335181/b4954a4d-d4c5-48c2-ab67-1476b24a810e)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

OnePlus 5T
Android 10
Pocket Casts 7.62-rc-3 (9216)

**Comment by fuzzmz** [comment]
AFAIK Jetpack Compose requires a minSdk of 21 or higher, per [API Levels](https://apilevels.com/), and Jetpack Glance was minSdk 21 as well, per the [blog post](https://android-developers.googleblog.com/2021/12/announcing-jetpack-glance-alpha-for-app.html) ages ago ("Note: while the minSDK is 21, we are currently only supporting compatibility till SDK v23.") so in theory it should work?

**Comment by MiSikora** [comment]
Glance does not compile to regular Compose. It compiles to regular widget elements so there's no compatibility issue there. Right now I don't know what the issue is. Maybe theming, maybe something else. We removed new widgets for now and will continue working on them. Thanks for the report though!
