### ISSUE TITLE
Links with position in them do not start from the shared position

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#21]
Test steps:

1. Share a link with position from the app
2. Close the app and wipe the app's data
3. Open the link
4. Observe that the web player has the podcast loaded to the proper position
5. Tap the button to open the podcast in the app
6. Begin playing the podcast within the app and observe that it does not start playing from the proper position

**Comment by joashrajin** [comment]
7787187-zd-a8c
