### ISSUE TITLE
The podcasts are taking too long to load when refreshing the Podcasts tab

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#2153]
### Description

We're experiencing infinite loading when refreshing podcasts in the Podcasts tab. I was only able to reproduce this issue after adding cloud files (videos) to my account, and I had around 100 podcast subscriptions.

I can't reproduce this consistently every time.

### Step-by-step reproduction instructions

1. Have an account with around 100 podcast subscriptions and some cloud videos uploaded to the account
2. Run the app
3. Go to Podcasts tab
4. Refresh the podcast list
5. The first refresh should work as expected
6. After finishes the refresh, try to refresh it again
7. ❌ You will notice the refresh gets stuck or takes loo long to finish

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/42220351/493cc360-c69e-4331-9574-0d4c976a8876

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pocket Casts `7.63-rc-3`

**Comment by mebarbosa** [comment]
Hey @MiSikora 👋🏽 

Do you think this PR https://github.com/Automattic/pocket-casts-android/pull/2082 is related to this issue? Should we revert it?

**Comment by MiSikora** [comment]
@mebarbosa I can't reproduce it all. Can you debug it to see where the app hangs?

* Do we not get the response from the server?
* Do we get the response but we do not push correct UI state?
* Maybe somewhere else?

Also, the description of cloud files is unclear to me. In your demo I see only local video files. None of them have the cloud indicator. Is this correct?

Before I revert #2082 can you check if you can replicate the issue with the changes from #2082 reverted? I'd do it myself but as I mentioned I cannot reproduce the issue at all.

**Comment by MiSikora** [comment]
Ok, I'm able to reproduce it. This isn't related to #2082 but I'll work on a fix.
