### ISSUE TITLE
Sleep timer gets randomly cancelled 

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#2219]
### Description

We have two users reporting that got sleep timer randomly cancelled

> Sleep timer rarely works. I set it to 25 minutes but it’s still playing after that time. I can’t rely on it.
8163546-zd-a8c

> i see it at least once per day maby more, it mostly seems random but & the thing is I have noticed it count down randomly throughout the episode but also few seconds before the timer ends (this happens more, the former happend randomly) and once the timer becomes bad the next autoplay timer also repeats the same problem so it's repeatable but also not trackable [...] Most likely in the background but I saw the visual countdown of the episodes happen in the foreground especially with it happening on an repeat timer (Clock timer is fine btw, tho less then 5 mins can be a tad inaccurate but I don't think much can be done with that) [...] Hmmmm I generally set the timer to 4 or 5 & it's good for the first 3+ times but then it gets caught & will randomly choose to count down in the last few seconds of the podcast I noticed (autoplay will repeat the behaviour hence why I noticed)-I think I noticed it happened more with episodes that have skip last but some is happening no problems -
It is at least twice a day+ tho what's interesting is tho is once the timer is bugged & cancled it will display and hold the set number but if I go into it and then cancel it to actually fix(because it's technically still bugged) the timer it actually goes back to 1 so maby that's playing into it
[Beta user](https://pocketcastsbeta.slack.com/archives/C013F9S9C2W/p1715336380969659?thread_ts=1714544495.220039&cid=C013F9S9C2W)

### Step-by-step reproduction instructions

I can't reproduce this issue. 

To be registered what I tried:
- I tried with 25 minutes custom time with the app in background and device locked and it worked as expected ✅
- Fixed time, remove the app from the list of opened apps and lock the device. It also worked as expected  ✅
- Tried with skip last and skip first episodes set and it worked as expected  ✅

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Report was from `7.62.2`, but maybe we had this issue before

**Comment by erricgunawan** [comment]
Possibly related:

> For some reason the sleep timer will reset itself. Checked the forum and others have the same issue. Not sure I can live with that and they don't seem interested in solving

8267770-zd-a8c ([3-star Android App Review](https://play.google.com/console/u/0/developers/7957760354032996428/app/4975504729640578607/user-feedback/review-details?reviewId=94447d22-84a5-4bf4-b06d-de42091a3afd))

**Comment by jinnypark** [comment]
https://forums.pocketcasts.com/forums/topic/sleep-timer-doesnt-stop/?view=all

> I’ve finally pinned this issue down a bit more. At night, I’ll turn a sleep timer on for 15-30 minutes. I’ll fall asleep. Hours later, I’ll wake up and the app is still playing. As soon as I turn my screen on, the “sleep timer” realizes what’s happened and pauses with a “sleep timer has paused” notification.

>I assume this is a battery optimization thing, but I have already followed all the other advice for fixing that. I have all the fancy sleep timer settings turned off. Phone battery optimization for the app is set to unrestricted. However, I’m running an ASUS Zenfone 10 and it’s probably set to “ultra durable” battery mode when this is happening.

** Android 14, app version 7.76 (9282).**

Sounds like it's a device-specific issue?

**Comment by erricgunawan** [comment]
https://forums.pocketcasts.com/forums/topic/sleep-timer-on-android-stopping-too-early/?view=all#post-6810

> Android 15, pixel 7 pro, app version 7.76. Sleep timer on app seems to be stopping playback too early. For example, i started a 1 hr 20min podcast. I set a timer for 1hr 10mins. Open the app the next day, playback position is at 50mins. All power saving options disabled for this app. Unlimited background usage.

> I do have that setting (Intelligent Playback Resumption) enabled and I always just use the phones speaker, while locked and charging after starting the podcast and the sleep timer. I haven’t tracked when the podcast stops, since I usually fall asleep by then. However, I do tend to generally set the timer a few mins short of the actual length of the podcast. I sometimes reuse the same one if its a slow release week. So, maybe the intelligent resumption IS rolling it back. It does seem to be inconsistent as to how much it rolls back. Sometimes significant, like on the order of 20 mins, sometimes not at all.

Probably related?
