### ISSUE TITLE
All downloads fail for some users after upgrading to 7.20.x

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#222]
Since the update to 7.20 we've had multiple reports of users not being able to download any podcast episodes.

> Since receiving the update earlier this morning, all podcast downloads are failing for me. I hit Download, it queues, then fails. This happens for all podcasts. I can play by streaming, but I almost always download before playing, so this is a major problem for me.

> today's update seems to have broken something. I haven't been able to download a single episode of anything all day - every attempted download fails. I've tried rebooting the app, restarting my phone, going on/off wifi, fiddling with the app settings; nothing helps.

> I've used Pocket Casts for years and love it. Suddenly, today, it won't download podcast episodes. Other things will download, and I checked permissions to make sure it has access to files. I reinstalled it but there was no change.

The logs from the first user don't show any red flags. Looks like there are a couple of downloads that failed because the URL didn't return a valid response, but it seemed like there were successful downloads in the logs.

It does seem like a  possibility that one or two podcast providers may have had an outage, and that's what is getting reported.

**Comment by ashiagr** [comment]
This is obsolete, marking closed.
