### ISSUE TITLE
Going to status page crashes the app

### ISSUE THREAD

**Issue by MiSikora** [Automattic/pocket-casts-android#2229]
### Description

When status page is opened the app crashes.

### Step-by-step reproduction instructions

1. Go to `Profile`.
2. Go to `Help & feedback`.
3. Tap on the status page icon in the top right corner.
4. App crashes.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6, Android 14, `7.64-rc-1`

**Comment by ashiagr** [comment]
Closed via https://github.com/Automattic/pocket-casts-android/pull/2231
