### ISSUE TITLE
Search: Requires 3 back gestures to exit

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#2243]
### Description

When you open the search bar but want to exit, it currently requires 3 back gestures instead of 2. The two should be (1) back gesture dismisses the keyboard (2) dismiss the search screen.

### Step-by-step reproduction instructions

1. Open the search bar on the podcasts page
2. Try to exit, notice you need to use the back gesture 3 times

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/16253818/1d187179-187c-4e79-9a90-46717973461e

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Fold 4, Android 14, Pocket Casts v7.64-rc-2

**Comment by ashiagr** [comment]
First swipe dismisses the keyboard.
Second swipe removes focus from the search view.
Last swipe dismisses the screen. 

I think it is fine to keep this behavior since we can dismiss the screen just by tapping it. Wdyt, @joashrajin?

**Comment by joashrajin** [comment]
Yes, sounds fine to me! I will close the report
