### ISSUE TITLE
Tweak play/pause button size in new mini player

### ISSUE THREAD

**Issue by david-gonzalez-a8c** [Automattic/pocket-casts-android#2245]
### Description

We are getting feedback about the size of the play button in the new mini player that I think makes total sense.

Let's bump it up from the current 32dp to 40dp, keeping the same margin we have now to the forward and back buttons:

<img width="598" alt="image" src="https://github.com/Automattic/pocket-casts-android/assets/92024441/4190345e-7963-47d9-93b5-a18ea0fa99aa">

[Updated Figma specs](https://www.figma.com/design/G60UqxPhTynbalo0Vfr1NC/Playground?node-id=1556-15899&m=dev)

### Step-by-step reproduction instructions

...

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by ashiagr** [comment]
Closed via https://github.com/Automattic/pocket-casts-android/pull/2250

Fix will be included in the next beta.
