### ISSUE TITLE
The podcast grid padding is added after the page load

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#2248]
### Description

After the app has been killed when you open the app the side padding gets added.

### Step-by-step reproduction instructions

1. Go to the podcasts page
2. Kill the app
3. Open the app

### Screenshots or screen recording

| Start | End |
| --- | --- |
| <img width="512" alt="Screenshot 2024-05-17 at 10 18 18 AM" src="https://github.com/Automattic/pocket-casts-android/assets/308331/aebd3684-46cd-478b-81bf-b813cc374d4d"> | <img width="512" alt="Screenshot 2024-05-17 at 10 18 27 AM" src="https://github.com/Automattic/pocket-casts-android/assets/308331/a2119692-159f-4fa0-8b7f-cd7003ccd732"> | 

https://github.com/Automattic/pocket-casts-android/assets/308331/c3a85a29-b669-4bcd-a09a-bd9dee816976

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Fold5, 7.64-rc-2

**Comment by ashiagr** [comment]
Closed via https://github.com/Automattic/pocket-casts-android/pull/2251
