### ISSUE TITLE
Sleep timer end of an episode is not pausing before right before the end

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#2266]
### Description

> Hello, I believe playing until the end of an episode is not working. It used to stop right before the end so that if you fall asleep you're still in the right episode. But it's the second night in a row that when I wake up, it has gone passed the end and on to the next episode and stopped itself. I have to go history to find my episode that I've missed the end. Temporary bug or has the okay to end changed?

p1716191666785669-slack-C02A333D8LQ

### Step-by-step reproduction instructions

1. Set sleep timer to end of episode
2. ❌ The sleep timer will stop at the end of the episode and will go to the next epsiode

The expected behavior is to stop right before the end of the episode so the user can see what was the last listened episode

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by CookieyedCodes** [comment]
I noticed this too, wasn't the case pre rc4 🤔
