### ISSUE TITLE
Talkback: add podcast title on the artwork

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#2294]
### Description

Talkback on the podcasts tab isn't working with the podcast artwork. 

### Step-by-step reproduction instructions

1. Open the system settings
2. Search for Talkback and turn it on
3. Using [the shortcuts](https://support.google.com/accessibility/android/answer/6151827?hl=en#zippy=%2Cversion-up) navigate to the Pocket Casts app
4. Open the podcasts tab
5. Drag your finger over the podcast artwork
It should say the podcast title but instead it says Unlabelled

### Screenshots or screen recording

<img width="327" alt="Screenshot 2024-06-01 at 11 33 58 AM" src="https://github.com/Automattic/pocket-casts-android/assets/308331/9ec91f48-c013-42e1-b006-7adc179eead9">

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6, 7.65-rc-2

**Comment by joashrajin** [comment]
> There is a major accessibilty issue with the new version of Pocket Casts on Android. I use the latest version of Google Talkback on A google Pixel 8 Pro wih the latest Android update. Recently my pocket cast version updated and it no longer speaks the name of the podcasts on the main podcasts window that hsows what podcasts I'm subscribed to. It was working fine before the update. Now it just says "unlabeled" when you press one of the podcasts.

8261650-zd-a8c

**Comment by mebarbosa** [comment]
Fixed by https://github.com/Automattic/pocket-casts-android/pull/2297
