### ISSUE TITLE
Add "Open Player Automatically" setting

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#23]
iOS has the option to "Open Player Automatically" under the "General" settings. Turning this on means that tapping to play an episode from, for example, an episode screen or from an episode list will automatically open the full screen player. Let's add this setting to Android to be consistent.

---------------

#### Here's the feature on iOS:

https://user-images.githubusercontent.com/4656348/176771469-c0490719-d084-4c9f-8b34-1633c2aa6e2d.mov

**Comment by ksog66** [comment]
Hey @mchowning, may I try implementing this.

**Comment by ksog66** [comment]
Hey @mchowning 
What should be the summary for this option.
I thought of this 
> If on, tapping on play on podcast items will expand the media player.

**Comment by mchowning** [comment]
> What should be the summary for this option.
> I thought of this
> 
> > If on, tapping on play on podcast items will expand the media player.

Good question. 🤔 

The "on play on" portion feels just a bit awkward to me. Could remove the first "on".  I might go with something like:

> If on, the full-screen player will open when you start playing a podcast episode.

I think either of those works. Feel free to go with whichever you prefer.
