### ISSUE TITLE
Search Term gets cleared when scrolled off-screen

### ISSUE THREAD

**Issue by aurarora** [Automattic/pocket-casts-android#2352]
### Description

While searching for an episode within a Podcast Feed, if the search has enough results, it is possible to scroll the search box off-screen. This results in the search term being cleared, and every Episode reappearing. This makes it impossible to view every search result.

### Step-by-step reproduction instructions

1. Go to a Podcast with enough Episodes (I used 'The Daily')
2. Input a Search Term that has enough results to scroll down (best, if some Episodes at the top aren't included, to see the Bug. I used 'Test')
3. Scroll down, until the Search Box is off-screen.
4. Notice all Episodes reappear.
5. Notice the Search Box is empty, when scrolling back up.

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/72910336/63455ae3-44be-47c8-aa26-9010bf17fd9e

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Galaxy S23FE
Android 14 OneUI 6.1
Pocket Casts 7.66-rc-1

**Comment by geekygecko** [comment]
I believe this has been fixed as I can't repeat it.
