### ISSUE TITLE
Up Next - Not tracking up_next_shown when tapping from navigation bottom bar 

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#2364]
### Description

See: p1718725092247959-slack-C06EHRAPW12

### Step-by-step reproduction instructions

Tap on Up next navigation bottom bar and see the event is not being tracked

Note: We need to track this event only once like we are doing for Discover tab

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by MiSikora** [comment]
Is it the same as #2363 or am I missing something?

**Comment by mebarbosa** [comment]
> Isn't it the same as #2363 or am I missing something?

Omg. I am getting crazy today 🤣  Yes. I will close this one

Thanks @MiSikora
