### ISSUE TITLE
While driving I have to tap the playback speed button 18 times to change from 1.2x to 1x speed

### ISSUE THREAD

**Issue by TylerCarberry** [Automattic/pocket-casts-android#2403]
### Description

Can you remove some playback speed options from the notification button

Do you have analytics on what playback speeds users set? Do people notice the difference between 2.6 and 2.8x for example

### Step-by-step reproduction instructions

https://github.com/Automattic/pocket-casts-android/pull/1645

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Version 7.66 (9245)

**Comment by MiSikora** [comment]
Fixed in #2439
