### ISSUE TITLE
Playback Speed: Add 1.0x to the options when clicking on the speed

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#2427]
### Description

If you click on the playback speed (without clicking on the '+' or '-' icons), 1.0x is missing, and 1.5x is the lowest it goes. You need to manually use the '-' icon to get it down to 1.0x

### Step-by-step reproduction instructions

1. Play an episode and attempt to adjust the playback speed
2. Click on the speed itself to have it adjusted by 0.5 increments
3. Notice that once you go past 4.0x, it reverts to the lowest being 1.5x

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/16253818/726a2a68-569d-407a-afca-6f5d8e506368

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Fold 4, Android 14, Pocket Casts v7.67-rc-2

**Comment by joashrajin** [comment]
https://forums.pocketcasts.com/forums/topic/please-reincorporate-the-middle-click-playback-speed-1-0-function

**Comment by joashrajin** [comment]
8405492-zd-a8c

**Comment by joashrajin** [comment]
8404063-zd-a8c

**Comment by azollafox** [comment]
8416866-zen

**Comment by azollafox** [comment]
8420154-zen

**Comment by mdrockwell** [comment]
8407169-zd-a8c
