### ISSUE TITLE
Download shelf action is broken

### ISSUE THREAD

**Issue by MiSikora** [Automattic/pocket-casts-android#2477]
### Description

The download action added in #2325 doesn't work correctly. It can be displayed as 2 separate actions - `Downloads` and `Downloading` and isn't displayed in the shelf.

### Step-by-step reproduction instructions

1. Play any episode.
2. Open player.
3. Tap on more actions in the shelf.
4. Notice that there are two download actions - `Download` and `Downloading`.
5. Move these action to the `Shortcut on player` section.
6. Actions aren't displayed in the shelf.

### Screenshots or screen recording

| Actions | Shelf |
| - | - |
| ![Screenshot_20240709-133529](https://github.com/Automattic/pocket-casts-android/assets/30936061/bc9d13ba-6a8b-414e-b153-c0160eb140dd) | ![Screenshot_20240709-133117](https://github.com/Automattic/pocket-casts-android/assets/30936061/2f2644c9-9bb3-4205-9176-365c376f59b7) |

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6, Android 14, 1d4cde0e245aee33f2fb4a6a9b82c97b250d9d35

**Comment by vivadavid** [comment]
Same issue on my Xiaomi mi 9T Pro running Android 11.
