### ISSUE TITLE
Google TalkBack: Unlabeled sections

### ISSUE THREAD

**Issue by igotdes** [Automattic/pocket-casts-android#2484]
### Description

When using Google TalkBack, there are sections of the app that are read as "Unlabeled."

This may be related to the following open issues:
- https://github.com/Automattic/pocket-casts-android/issues/2264
- https://github.com/Automattic/pocket-casts-android/issues/748

### Step-by-step reproduction instructions

1. Go to your phone's settings and enable Google TalkBack
2. Go to the Pocket Casts app
3. Play an episode
4. Expand the full-screen player
5. Swipe right until the podcast/episode artwork is highlighted
6. Google TalkBack will say "Unlabeled"
7. Go to a podcast's page in the app
8. Double tap on an episode to show its details
9. Swipe right until the podcast/episode artwork is highlighted
10. Google TalkBack will read out some information, and then say "Unlabeled" at some point

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Replicated on:

- Samsung S23 Ultra
- Android 14
- Pocket Casts 7.67

**Comment by ashiagr** [comment]
Closed via https://github.com/Automattic/pocket-casts-android/pull/2712/commits/19a1f9b83e9111cca1d5a9d4f1abaf42d7f35855
