### ISSUE TITLE
Investigate: Order of multi-select action bar is not retained

### ISSUE THREAD

**Issue by igotdes** [Automattic/pocket-casts-android#2492]
### Description

[Forum user](https://forums.pocketcasts.com/forums/topic/shortcuts-in-toolbar-changes-positions/?view=all#post-3632) reports that their custom order of the multi-select action bar is not retained:

> The shortcuts in the toolbar resets after some time (like a couple of weeks or so) to their standard positions and I then have to rearrange them again the way I want. Why won’t they stay the in their new positions?

### Step-by-step reproduction instructions

We haven't been able to replicate the issue so far. I've only just tried, although the user says it can take weeks for the order to revert.

### Screenshots or screen recording

> See attached screenshots marked with “1” as standard positions and screenshots marked with “2” as new positions. I have cleared data and cache and even reinstalled the app without any luck. I’ve got a Samsung Galaxy S21 with android 14, One UI 6.0. The app version is 7.61.1

<details>
<summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/151e7d0c-54fd-411b-8fab-7aa6cde170e9)

![image](https://github.com/user-attachments/assets/df84675c-67a2-4627-aa16-d7d67f6cf734)

![image](https://github.com/user-attachments/assets/4d037f9f-00a8-4057-8368-11bc4018e78d)

![image](https://github.com/user-attachments/assets/100685ae-39d4-4155-b3bb-6a39d93cdaea)

</details>

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

User's device and app details now:

- Samsung Galaxy S21
- Android 14, One UI 6.1
- Pocket Casts 7.67 (9249)

[Another forum user](https://forums.pocketcasts.com/forums/topic/shortcuts-in-toolbar-changes-positions/?view=all#post-4551) reports experiencing the same issue, but they haven't confirmed their device and app details yet.

**Comment by CookieyedCodes** [comment]
I have this every time the app updates

**Comment by igotdes** [comment]
Also reported by [another forum user](https://forums.pocketcasts.com/forums/topic/shortcuts-in-toolbar-changes-positions/?view=all#post-4753):

> i am currently using version 7.67 (9249), and I use the app on my Google Pixel 8 Pro (though I was also experiencing this issue on my previous phone, which was a Galaxy S23 Ultra).
> 
> This issue has definitely occured more than just now, I would say at least 5 times, if not more, in the last ~1 year.
