### ISSUE TITLE
Give Ratings: after closing the status bar is the wrong color

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#2568]
### Description

After submitting a rating and returning to the podcast page the status bar is the wrong color.

### Step-by-step reproduction instructions

1. Go to a podcast
2. Tap the "Rate" button
3. Submit a rating

See that the podcast page status bar is the incorrect color.

### Screenshots or screen recording

| Before | After |
| --- | --- |
|  ![Screenshot_20240802_225513](https://github.com/user-attachments/assets/4a84b3b5-5a5a-4029-a500-952213c0182d) | ![Screenshot_20240802_225523](https://github.com/user-attachments/assets/47154948-cb57-408e-886f-8ad70259b0eb) | 

https://github.com/user-attachments/assets/7529381b-e47b-4afe-a400-b3f4304f3d99

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Fold5 Android 14, Pocket Casts 7.69-rc-3

**Comment by mebarbosa** [comment]
Fixed by: https://github.com/Automattic/pocket-casts-android/pull/2582
