### ISSUE TITLE
Ratings Overlay reappears when swiped down

### ISSUE THREAD

**Issue by aurarora** [Automattic/pocket-casts-android#2577]
### Description

After swiping down to dismiss the Ratings Overlay, when closing an reopening the app (without fully closing), the overlay reappears. This does not happen, when dismissing it by pressing the X button.
Every instance of the overlay reappears, meaning that multiple overlays appear, when multiple ones have been dismissed by swiping down.
Those reappeared overlays cannot be dismissed by pressing the X button, meaning the app has to be fully closed to stop them from reappearing.

### Step-by-step reproduction instructions

Situation 1:
1. Open the Rating menu of any podcast 
2. Dismiss the overlay by swiping it down
3. Top steps may be done multiple times
4. Leave the app (do not fully close)
5. Reopen the app
6. Every overlay that was dismissed by swiping downwards reappears
7. Try dismissing the overlay by pressing the X button
8. Notice it doesn't get dismissed

Situation 2:
1. Open the rating menu of any podcast
2. Dismiss the overlay by pressing the X button
3. Leave the app (do not fully close)
4. Reopen the app
5. Notice the overlay does not reappear

### Screenshots or screen recording

https://github.com/user-attachments/assets/fa61640d-ab89-4079-9616-172e78fbdbe1

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Galaxy S23 FE
OneUI 6.1 Android 14
Pocket Casts v7.70-rc-1

**Comment by mebarbosa** [comment]
Thank you @aurarora for taking your time to report this issue! I've started working on it
