### ISSUE TITLE
Change avatar text is no longer left aligned

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#2621]
### Description

There's an issue with the change avatar button text alignment. 

### Step-by-step reproduction instructions

1. Tap on the Profile tab
2. Make sure signed into a Pocket Casts account 
3. Tap the Account button 

Notice that the "Change avatar" button text is no longer left aligned. 

### Screenshots or screen recording

<img  width="300" src="https://github.com/user-attachments/assets/0117306d-71ad-43a4-853f-f2949fc8d076" /> 

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Fold5, Pocket Casts 7.70-rc-2

**Comment by mebarbosa** [comment]
Just to add more details, I think this issue is Samsung Fold only. I tried to reproduce in others devices but it's working as expected

**Comment by geekygecko** [comment]
I think it's related to whether you are signed in with Google or email and password. Hopefully, my fix works.
