### ISSUE TITLE
Missing margin for Bottom Player Bar within Search Screens

### ISSUE THREAD

**Issue by aurarora** [Automattic/pocket-casts-android#2648]
### Description

All the Search Screens (Search, All Podcasts, All Episodes) are missing a bottom margin for when the Bottom Player is showing. This hides some of the search results and makes them hard to click.

### Step-by-step reproduction instructions

1. Start playing an Episode to show the Bottom Player Bar
2. Go to the search screen and make a search
3. Scroll down 
4. The Bottom Bar is in front of the last search result
5. Repeat with the All Podcasts / All Episodes screens

### Screenshots or screen recording

https://github.com/user-attachments/assets/3fa0f9fe-3e31-434f-a3c9-ec7b8b3ac889

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Galaxy S23FE
Android 14 OneUI 6.1
Pocket Casts 7.70-rc-4 (Issue not recently introduced)

**Comment by geekygecko** [comment]
Thanks for reporting this issue! I have a fix coming soon.
