### ISSUE TITLE
Ratings improvements

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#2656]
### Description

Two things that might be improved with the ratings UI that were [reported here](https://github.com/Automattic/pocket-casts-android/pull/2653#pullrequestreview-2242056448).

1. After I give the rating and try to rate again tapping on the stars is a bit janky. It doesn't recognize always the tap action and I have to tap multiple time. Drag gesture on the other hand works always.
2. It would be nice if the Submit button when re-rating the podcast had some simple fade animation instead of suddenly changing visibility.

### Step-by-step reproduction instructions

1. Open a podcast
2. Tap the rate button

**Comment by mebarbosa** [comment]
I've put this [PR](https://github.com/Automattic/pocket-casts-android/pull/2824) to add the animation for the submit button. For the stars issue reported here I can't reproduce it

**Comment by MiSikora** [comment]
I can no longer replicate the 1st issue.
