### ISSUE TITLE
Showing Played Episodes in Android Automotive

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#271]
I can't see how to tell what episodes I've played (i.e., marked as played) from within Android Automotive. Is there a way to find this that I'm just missing?

A user brought this up [on Twitter](https://twitter.com/jchampeau/status/1564356395633369088): 
![image](https://user-images.githubusercontent.com/4656348/187324573-e17929cd-f4ae-4f70-971a-1dd2a4ed1498.png)

**Comment by geekygecko** [comment]
I missed this issue and have created a duplicate. As I added some more implementation ideas on the other issue, I will close this one. 

https://github.com/Automattic/pocket-casts-android/issues/379
