### ISSUE TITLE
Can't upload the common audiobook M4B file format.

### ISSUE THREAD

**Issue by OutshineIssue** [Automattic/pocket-casts-android#2741]
### Description

PocketCasts Pro's files feature is really useful for keeping up with my audiobooks, but audiobooks come in all sorts of formats, right now I'm having trouble with M4B files. It might be because M4B can be used for video and "PocketCasts files" is not intended for video, but there's nothing I can do about it, my audiobook is in that format, I could maybe convert it to mp3, but it would probably lose all the chapter metadata, and I'm not even sure there's a free tool to do that on a 6 hour file.

It would be useful to know what file formats are currently supported when dropping a file, only the file size limitation is displayed. Needless to say, all popular audio book file formats should be supported.

### Step-by-step reproduction instructions

1. Go to files
2. Upload a .m4b file
3. The message "Unable to upload, as we're unable to determine the content type of this file." shows up.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Web Player Version 4.5.0 - Desktop Version 2.0.4 (Windows)

**Comment by CookieyedCodes** [comment]
From my understanding m4b is a proprietary format owned by apple so I think it's unlikely to happen on Android 

I am pushing for m4a chapters support on Android tho and I think that is now possible:)
https://github.com/AntennaPod/AntennaPod/pull/7159

**Comment by geekygecko** [comment]
I just tested using the Web Player. I was able to upload a 350 MB m4b audio file and play it. It would be good to figure out what is happening in your case. Is the file you are uploading a video m4b file? Have you tried with an audio m4b? Do those work?

**Comment by OutshineIssue** [comment]
> Is the file you are uploading a video m4b file? 

I'm pretty sure it's an audio m4b file, my media player properties have it's cover set as embedded not hardcoded. And the size is pretty similar, 339mb, AAC codec, 125kbps.

**Comment by geekygecko** [comment]
> not sure what other info I can give you

I would like to figure out why this isn't working for you. Would you be open to sending me a file to test with? I will delete the file once we have finished. You could send a link to our support email, support@pocketcasts.com, and mention it was for me to test with.

**Comment by OutshineIssue** [comment]
Done. Would you mind sharing what file formats PocketCasts currently supports?

**Comment by geekygecko** [comment]
I have successfully uploaded the m4b file you sent from my Mac app, Mac web browser, and Android emulator. This might be an issue with the Windows app, I will let the team know. Thanks for sending through the file for me to test with.

**Comment by justinshreve** [comment]
@OutshineIssue I tested with 2.0.4 of the Windows App and the test file you provided. I was able to successfully upload it and play it back. 

Do you get the same issue when using a web browser at https://play.pocketcasts.com/? If so, could you open the developer console in your browser (https://support.pocketcasts.com/knowledge-base/obtaining-a-console-log/) and see if there are any errors?

**Comment by OutshineIssue** [comment]
I ended up uploading it through my phone and it worked. I finished the book already and deleted it, so I don't have a way to test it anymore, sorry.

**Comment by OutshineIssue** [comment]
![image](https://github.com/user-attachments/assets/fe509a49-636f-4d55-9eae-92400a40058c)

OK, I gave it another shot. This is what I got on Firefox. Do you need any specific tab info?
