### ISSUE TITLE
Update sleep timer layout

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#2931]
Needs to update sleep timer to match with figma design. See: hHFpI1RtnW4TRb448Q4Don-fi-4613_33187

- [ ] Color of sleep timer text
- [ ] Size of minus buttons
- [ ] Size of plus buttons
- [ ] Dividers don't have margin
- [ ] Verify font type and color of row items

**Comment by geekygecko** [comment]
What needs to change about the sleep timer layout? It matches the other action bottom sheets, so I don't believe it's a good idea to make it match the design.

**Comment by mebarbosa** [comment]
> What needs to change about the sleep timer layout? It matches the other action bottom sheets, so I don't believe it's a good idea to make it match the design.

@geekygecko The font sizes, color of the tittle, the size of the plus and minus buttons are different and also in figma has the dividers between items that we don't have in the current implementation.

I can close this issue if you wanted

**Comment by geekygecko** [comment]
I will close this issue for now, as I believe there are more important issues we can spend time on that will help our users. We should consider this in the future. When we do, we should talk with our designers to make sure the designs aren't for iOS, as other existing screens in the same area look different on Android.
