### ISSUE TITLE
"Something went wrong" when installing on Pixel 9 Pro / Android 14

### ISSUE THREAD

**Issue by michel-slm** [Automattic/pocket-casts-android#2982]
### Description

I can't install Pocket Casts from Google Play Store, both while enrolled in the beta program and the normal version.

If I sideload it from apkmirror.com it works but then Android Auto support is missing, which is expected.

This happens last year too on a different phone (my Samsung S22 IIRC) and got eventually resolved, not sure what the underlying issue is.

Once the app is installed it works fine and generally updates can be installed just fine.

### Step-by-step reproduction instructions

Install from Play Store

### Screenshots or screen recording

![Image](https://github.com/user-attachments/assets/0d5afa30-76d7-4d5f-b3e4-66bd1c77a49c)

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

**Comment by geekygecko** [comment]
Does it work if you install it from our releases page on GitHub [https://github.com/Automattic/pocket-casts-android/releases](https://github.com/Automattic/pocket-casts-android/releases)? 
This seems to be a [common Google Play store issue](https://support.google.com/android/thread/259149015/error-when-downloading-apps-from-the-play-store-something-went-wrong-on-our-end-please-try-again?hl=en). I don't believe there is anything we can do about this in our code so I will close this issue.

**Comment by michel-slm** [comment]
It works when installing the APK by hand, whether from here or from apkmirror. However the signature will be different and thus Android Auto won't work.

I do suspect it's mostly a Google Play Store issue, but what's weird is that it kept happening with Pocket Casts (twice on two devices) whereas I don't recall ever having this issue with other apps

Let's see if this eventually resolves itself as last time

**Comment by michel-slm** [comment]
@geekygecko which downloads do I need? I verified installing both the app and automotive apks don't work for allowing Android Auto to work, I suspect because the signatures are wrong

**Comment by geekygecko** [comment]
For Android Auto, you only need the mobile app, which works by sending the screens from the phone. The Automotive APK is only needed if you use the Android Automotive OS, it's installed in the car and not on the phone. 

Unfortunately, I don't own a car that supports Android Auto. It works for the developer simulator but like you say Google might only be showing apps they have resigned. Sorry, I'm unsure how to help if the signed version we send to Google doesn't work.

**Comment by michel-slm** [comment]
I expect that, like last time, some future Pocket Casts version will somehow just work. Obviously I'm not expecting you to release one just to potentially fix installation on my phone 😅

I tried installing an older release from GitHub then upgrading on play store and got the same error, so it does seem to be that somehow both the current stable and beta version somehow won't install on my Pixel 9 Pro (and it's still on Android 14 too, which is weird - it's not an issue with Android 15).

**Comment by michel-slm** [comment]
Ended up adding my backup Google account, installing Pocket Casts from it, switching back to my main account and then uninstalling, and looks like now I can install from my main account again.

This experience is quite frustrating, sorry for the bother. Hopefully the next person who experiences this issue might find this useful.

**Comment by geekygecko** [comment]
Thanks for letting us and everyone else how you solved it.
