### ISSUE TITLE
Unable to permanently change "Skip back time" settings

### ISSUE THREAD

**Issue by ezebecke** [Automattic/pocket-casts-android#303]
I'm grouping a few recent reports of users on Android not being able to permanently save the skip settings. 

I haven't been able to replicate this on my end. 

[5516359-zd](https://woothemes.zendesk.com/agent/tickets/5516359)

App version : 7.21.0
Phone: samsung - Galaxy S8 - SM-G950U 
Android version: 9 SDK 28

> In the screenshots below, you can see where I changed the "skip back time" from 12 seconds to 25 seconds. I've tried making the change at least 10-15 times now, and restarted my phone, and it always reverts back.

[5534334-zd](https://woothemes.zendesk.com/agent/tickets/5534334)

App version : 7.20.3 
Phone: samsung - Galaxy Z Fold3 5G - SM-F926U1 
Android version: 12 SDK 31

> I keep changing the Skip backward from 30 sec to 15 and it isn't saving. Keeps going back to 30 as soon as I switch apps and it runs in the background.

[5539341-zd](https://woothemes.zendesk.com/agent/tickets/5539341)

App version : 7.21.0
Phone: Google - Pixel 4a - Pixel 4a 
Android version: 13 SDK 33

> The skip control settings, keep resetting to 30 forwards and 30 backwards after the phone screen is off for a few minutes.
I tried to set it to 30 forwards, and 15 backwards.

**Comment by erricgunawan** [comment]
Another report from 5627146-zen

> Trying to change my skip forward from 10 seconds. It keeps reverting back to 10 after an episode or two.

> It lasted about 4 episodes in my playlist

> App version : 7.23 (9031)
> Phone: Google - Pixel 3a XL - Pixel 3a XL - bonito
Kernel: 4.9.292-gab4493f31457-ab8272301 - abfarm-01355
Android version: 12 SDK 32

**Comment by thabotswana** [comment]
Another report in 5634046-zen

>Whenever I change the skip forward or back time, they go right back to what they were before everytime the app refreshes.

App version : 7.24-rc-4 (9038)
Phone: samsung - Galaxy S20 5G - SM-G981U - x1q
Android version: 12 SDK 31

**Comment by thabotswana** [comment]
Another report in 5634528-zen

>Whenever I change the skip forward and skip backward time settings, it is reverted automatically after a few minutes or so. I have attached a screenshot to clarify what I am referring to. I have tried to restart the app and my phone to no avail.

![Screenshot_20221016-100349__01](https://user-images.githubusercontent.com/35628116/197189093-277b3a46-c582-423a-951a-7efd5be15459.jpg)

App version : 7.23 (9031)
Phone: OnePlus - OnePlus 7T - HD1903 - OnePlus7T
Android version: 11 SDK 30

**Comment by Number6174** [comment]
I was experiencing this issue as well, but found a workaround that might help diagnose the actual problem.

I'm a Pocket Casts Plus subscriber. Normally I use the Android app, but I frequently have the web app open to monitor new releases on my desktop.

I had the reported issue of changing the skip forward and skip backwards time being reset. The reset happened when I changed the setting in the Android app. But when I tried changing it in the web app, not only did the change stick, the changes propagated to the Android app after I refreshed (ie checked for new podcasts, but it is possible that timing is coincidental, I haven't looked precisely when/how settings sync).

**Comment by erricgunawan** [comment]
5638864-zen:

> I keep setting the skip forward button to 30 seconds in the main general settings menu but it keeps resetting to 90 seconds every time I check, is there a way to make it stay to 30 seconds?

> App version : 7.24-rc-4 (9038)
Phone: samsung - Galaxy Note20 Ultra 5G - SM-N986U - c2q
Android version: 12 SDK 31

**Comment by VGJohn** [comment]
Just to note, this fix  #425 may help address this issue 😄

**Comment by erricgunawan** [comment]
5728695-zen:

> Whenever I'm trying to change forward seek seconds from the default 10...it goes back to 10.
The backwards seek is working fine, it remembers my setting.

**Comment by erricgunawan** [comment]
5736251-zen:

> Lately adjusting the skip back interval to 30 sec is becoming a game for me as pocket casts keeps randomly switching it back to 10.
>
> I initially thought there might be individual per podcast intervals that I am overlooking here.
>
> But I just found out that by just monitoring the player setting page with skip back interval set to 30 and can wait and see how the app is switching it back within a few minutes time.
>
> Can be reproduced on different android devices but it keeps resetting to the 10sec default.

App version : 7.25 (9044)
Phone: samsung - gta4xlvewifi - SM-P613 - gta4xlvewifi
Kernel: 4.14.190-perf-25030023-abP613XXS1AVJ5 - SWDK6311
Android version: 12 SDK 32

**Comment by erricgunawan** [comment]
5715215-zen:

> When I set the rewind to 30 sec from the default 15 sec, it works. But after a while, or restarting the phone the rewind time goes back to 15 sec. Then I've to keep setting it to 30 sec. Then it goes back to 15 sec again after some point.

Android v7.25

**Comment by darnelldibbles** [comment]
Another report here: https://twitter.com/DeuceGort/status/1599225663734456320

**Comment by mchowning** [comment]
@VGJohn's [possible fix](https://github.com/Automattic/pocket-casts-android/issues/303#issuecomment-1296120324) was included in 7.26. Are any of these reports are from users on that version (or later).

**Comment by erricgunawan** [comment]
5764707-zen:

> Hey I've been trying to change the amount of skip forward time but every time I do a reverts back to the old setting. I'm currently only signed in on two phones and I change it on both log in log out I do whatever I think I can and it always reverts back

Asked the user's version to see if they're on 7.26 or not.

**Comment by erricgunawan** [comment]
5753344-zen:

> I'm trying to change the skip control, the skip back duration. I tried to change the skip back duration from 30 seconds to 15 seconds.
>
> After 2 minutes, my skip back duration "reverts" back to 30 seconds again.
> 
> Note that this happens when I'm logged in to my pocket cast account. This issue does now happen when I'm not logged into my pocket cast account

> App version : 7.26 (9049)
Phone: Google - Pixel 4a - Pixel 4a - sunfish
Kernel: 4.14.276-g6ef255005cea-ab9062920 - abfarm-release-rbe-64-00044
Android version: 13 SDK 33
