### ISSUE TITLE
Remaining time stops being adjusted, when scrubbing while paused

### ISSUE THREAD

**Issue by aurarora** [Automattic/pocket-casts-android#3057]
### Description

The 'Adjust remaining time' feature (#2955) has a problem with scrubbing through the episode while paused. When paused, changing the position of the current playback, using the forward/back buttons or the playback bar, leads to the time remaining to not be adjusted anymore

### Step-by-step reproduction instructions

1. Enable 'Adjust remaining time' in settings
2. Play Episode with altered playback speed
3. Remaining time is adjusted
4. Press forward/back while playing
5. Notice the remaining time stays adjusted 
6. Pause playback 
7. Press forward/back or use playback bar to change position
8. Remaining time is not adjusted anymore

### Screenshots or screen recording

https://github.com/user-attachments/assets/584acd55-21a9-4c3a-850d-9acb0e8810e6

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung S23FE
Android 14 OneUI 6.1
Pocket Casts v7.75-rc-2

**Comment by geekygecko** [comment]
Thanks for reporting this bug!
