### ISSUE TITLE
Please add Greek translation

### ISSUE THREAD

**Issue by trlef19** [Automattic/pocket-casts-android#3071]
### Description

I'd like to help with it

### Did you search for existing list?

- [x] I have searched for existing issues.

**Comment by MiSikora** [comment]
Hi! Pocket Casts app is translated publicly on GlotPress. If you'd like to contribute you should start there. Here's the link: https://translate.wordpress.com/projects/pocket-casts/

**Comment by trlef19** [comment]
Yeah, I know but there is no option for Greek translation:(

**Comment by MiSikora** [comment]
@trlef19 Greek language is now available on GlotPress for Pocket Casts Android project.
