### ISSUE TITLE
Playback effects are disabled when skipping backward/forward, and playback is paused

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#3148]
### Description

See: 8972945-zd-a8c

### Step-by-step reproduction instructions

1. Play an episode
2. Change playback speed
3. Ensure you see the playback effects icon enabled
4. Pause the episode
5. Tap to skip 
6. ❌ See the icon gets disabled

### Screenshots or screen recording

https://github.com/user-attachments/assets/24c94ebb-139d-4c4e-9685-d986d3933dff

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

7.76-rc-1

**Comment by MiSikora** [comment]
Duplicate of #3057
