### ISSUE TITLE
Playback 24 tweaks

### ISSUE THREAD

**Issue by david-gonzalez-a8c** [Automattic/pocket-casts-android#3169]
### Description

Nice job with Playback! Here are some tweaks we can do:

- [x] In the [what's new sheet](https://www.figma.com/design/lH66LwxxgG8btQ8NrM0ldx/Playback?node-id=3089-20982&t=fglMq3JryXUDJ2jk-1) that announces the feature let's add a link to the image and not just the CTA

- [x] Like I suggested for iOS, let's add 3s to the amount of time each story persists before jumping to the next one.

- [x] The scrolling animation in the first story is not at a constant speed to me, it slows down or speeds up in a random way. Hard to reproduce (checking on my Pixel 7a)

https://github.com/user-attachments/assets/79b59025-9ee3-409c-80b5-68149d92e8c4

- [x] We should speed up the animation in the second story (number of shows and episodes) a little bit, like a 50% faster

- [x] In this screen, I'm realising that values like these (which should be common) look a bit dumb. To make it better, I'm suggesting we change the logic to show anything that's below 100 hours in hours (for example, this would be "41 hours") and anything greater in days/hours. Can we add the number of minutes too?

![Image](https://github.com/user-attachments/assets/07eb40be-41bb-43b9-818a-ff83991f0725)

- [x] In this screen I believe we made a change to add the title of the show to the paragraph instead of the heading so it scales better

![Image](https://github.com/user-attachments/assets/85520d30-a80e-4a9f-9855-9e9aa41afb56)

- [x] Can we animate this screen in a similar way to the ratings screen? (the bars animating from the bottom up)

![Image](https://github.com/user-attachments/assets/4fff7fec-0b7d-4f30-a46a-8572490d1bda)

- [x] I'm not sure what's happening here with the sphere sizes, since 2024 is supposedly more than 500% higher than 2023. Is the number wrong or the sphere size wrong?

![Image](https://github.com/user-attachments/assets/ab670551-1103-4cdf-b452-f3dc7aea833d)

### Step-by-step reproduction instructions

...

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 7a

**Comment by stic** [comment]
@MiSikora @david-gonzalez-a8c would it be possible to close / remove Playback 2024 (if you insist after first play)?

Takes quite a lot of prominent space and in my case (I remove listing history as it's just a hog) and no value.
