### ISSUE TITLE
Add new episodes to UpNext and trigger download after (not before) sync

### ISSUE THREAD

**Issue by stic** [Automattic/pocket-casts-android#3211]
### Description

Having two phones (devices probably too?) I have the first is setup to keep adding to UpNext (on top, and last, with 20 episodes limit), whilst I occasionally tick off the list items listening on the second device as well as listening to new episodes as these catch my attention (some are setup for UpNext on the 1st device).
On refresh (background disabled) I see update of podcast happening first, so episodes already listen to on 2nd device get added to UpNext (sometimes removing from the back of the list), manage to download, only to disappear a while later when sync happens.

I'd like to improve behaviour by adding to UpNext after the sync (which might actually bring some elements already)

### Did you search for existing list?

- [x] I have searched for existing issues.

**Comment by ashiagr** [comment]
@stic 👋 

I browsed through your PR and appreciate your approach to prevent adding new episodes (that have already been finished on another device) to up next before the sync process is complete.

Is it also to prevent auto-downloading of such episodes? It appears that episodes are added to auto-download queue only after the sync is complete:

https://github.com/Automattic/pocket-casts-android/blob/1585aad387eb28883f61ba8d48224c81883e3080/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt#L214-L226

I'm just trying to weigh in on any side effects, possibly up next not getting refreshed instantly for most users 🤔

**Comment by stic** [comment]
Thanks for reviewing the PR @ashiagr 
The auto-download seems to be internally checked for archived episodes, so as it happens post sync() new updates shouldn't be unnecessarily downloaded.

Indeed, a user needs to wait for sync to finish before items are added to UpNext. Personally, I'd rather have that to happen (small delay) than see episodes come and disappear (after all, the global state of me is that I've listened to these already 😉).

It's a quick fix approach, as I'm new to the project, I'm yet to see previous attempts at rationalising update & sync. 
I'd suggest syncing first, building list of episodes that aren't know yet (pre-update). Then update with latest list of podcast (some might have been deleted, some removed). And put back episodes where these should be.
The major issue I couldn't resolve quickly with such approach is to fetch these 'unknow' episodes on UpNext, history etc. I've come up with 'isSyncing' state, but give up after about 7 files of changes trying to reflect new state throughout the app 😬

**Comment by CookieyedCodes** [comment]
@stic Do you think it will fix my issue https://github.com/Automattic/pocket-casts-android/issues/628

**Comment by stic** [comment]
> @stic Do you think it will fix my issue https://github.com/Automattic/pocket-casts-android/issues/628

Nope @CookieyedCodes as that seems to be to order of items synced, if archived sync before starred and there is some dependency down the chain it would need a separate fix. Will have a look if no one picked that issue and it's possible to replicate (personally don't I don't star too much so haven't seen it).

Side note, is there a common approach to complex scenarios testing like this? Looked around but haven't seen anything taking sync for spin?

**Comment by CookieyedCodes** [comment]
Ya fair enough, the sync is more so on the iOS side of things anyways, 

I think most people don't touch sync because they don't want to upset users 😅

**Comment by stic** [comment]
> Ya fair enough, the sync is more so on the iOS side of things anyways,
> I think most people don't touch sync because they don't want to upset users 😅
It's rather that the code is quite complicated (vs. complex) in this area, let me take my findings to appropriate issue ok?

**Comment by CookieyedCodes** [comment]
Hmmm I might suggest you put it under a toggle under advanced settings then because if it does make an issue it minimizes the risk to people who do want it 🤔🤔

**Comment by stic** [comment]
> Hmmm I might suggest you put it under a toggle under advanced settings then because if it does make an issue it minimizes the risk to people who do want it 🤔🤔

Well I haven't seen many toogles in that part of the code, I still think that best solution would be to rethink sync / update order i.e. sync and only update post sync (as now we have sync potentially removing / adding podcasts which update running before it won't cover). Anyways, that's not trivial - here the main impact will be to wait for sync to finish to see latest episodes popping on the UpNext list, let's see if anyone notices..

**Comment by CookieyedCodes** [comment]
Fair enough, what I mean by a toggle is create a if statement for your new code vs the old code, just to keep both options possible and if it goes well they can have the default toggled on 😉
