### ISSUE TITLE
Incorrect Shuffle Button Color After Signing Out of Paid Account

### ISSUE THREAD

**Issue by mebarbosa** [Automattic/pocket-casts-android#3281]
### Description

The following issue was found during the beta test for 7.77.  

> I was signed in with a paid account and I signed out. Without closing the app I went to the Up Next queue. The button worked as expected and showed the upsell flow but it wasn’t golden colored. After reopening the app it went back to the golden color. 

Internal reference pdeCcb-7BG-p2

### Step-by-step reproduction instructions

1.  Have a paid account logged
2. Open up next and see the shuffle button painted as grey color
3. Sign out without closing the app
4. Open up next
5. See the shuffle button is not painted as gold color ❌

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

7.77 - Beta

**Comment by MiSikora** [comment]
No, I can't replicate it now.
