### ISSUE TITLE
Improve Up Next clear all icon

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#3313]
### Description

There's feedback that the new clear all episodes in the Up Next button is confusing. [Reddit](https://www.reddit.com/r/pocketcasts/comments/1gpsp5h/clear_queue_option_disappeared/) 
Can we please get some design feedback?

Instead of a trash can, some other material icons might be a good alternative. 

<img  width="200" src="https://github.com/user-attachments/assets/382d2968-429f-4ff4-ab08-67aa102a43be" /> 

<img  width="200" src="https://github.com/user-attachments/assets/c1513ce0-c3c7-42f1-96cc-784462948804" /> 

It might also be confusing that the clear queue button is also above the now playing episode but that doesn't get removed.

### Screenshots or screen recording

<img  width="300" src="https://github.com/user-attachments/assets/22d35564-08ec-4bfc-aade-5cdf5ed1f41e" /> 

### Did you search for existing list?

- [x] I have searched for existing issues.

**Comment by david-gonzalez-a8c** [comment]
We already use the following icon in the confirmation modal, so I suggest we use the same in the top bar. What do you think?

![Image](https://github.com/user-attachments/assets/09789396-5d05-472f-ad34-e3e7c57feb0d)

This is the [Figma link](https://www.figma.com/design/fs6qvDgcorsbCMUNyhGpd3uI/%F0%9F%9B%A0-Pocket-Casts-Design-System?node-id=2-73&t=dz201l6Brn2hHy0b-1) to the icon in the Design System.

**Comment by CookieyedCodes** [comment]
Maby with just a mention that it won't delete episodes of include an option to archive all episodes too 🤔🤔

**Comment by geekygecko** [comment]
Thanks for finding a better icon @david-gonzalez-a8c 

Just an idea but as the icons only relate to the episodes below the now playing episode, would it be better to move them down next to the shuffle icon or does that look too cluttered? 

<img  width="300" src="https://github.com/user-attachments/assets/c60796e2-1092-438d-85f5-d2e5876ee955" />
