### ISSUE TITLE
Sleep timer stops podcast **after** given time

### ISSUE THREAD

**Issue by wzieba** [Automattic/pocket-casts-android#3355]
### Description

From the user report:

> Hello,
the sleep timer is not working for me anymore correctly. 
The sleep timer turns the volume after the defined time down but doesn't Pause the Podcast. 
The Podcast only pauses after double the defined time. 
Example:
> - Sleep Timer is defined for 5 minutes
> - the volumes gets muted after 5 minutes but the episode does not Pause
> - the episode pauses after 10 minutes

I can confirm this behaviour happen with 1 minute interval.

### Step-by-step reproduction instructions

1. Open a podcast
2. Set sleep timer to 1 minute
3. See that after 1 minute, podcast volume is 0, but it's still in a state of `play` (progress + pause button visible)
4. In my case, the `play` state moved to `paused` after 1m 47s

### Screenshots or screen recording

https://github.com/user-attachments/assets/19c8c6a4-92d8-426c-b35f-389214d8187f

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 8a, Android 15, Pocket Casts 7.78

**Comment by igotdes** [comment]
Also reported by user in #9155806-zen

**Comment by danjjohnson** [comment]
Also reported in 9250217-zd-a8c - I let them know a fix is coming.

**Comment by mebarbosa** [comment]
This issue will be fixed in `7.80`
