### ISSUE TITLE
Filters "Downloaded" and "Starred" not working as expected

### ISSUE THREAD

**Issue by Remiol** [Automattic/pocket-casts-android#3368]
### Description

The filters “downloaded status (>downloaded)” and "starred" do not work as expected for all podcasts to which I'm not subscribed, but which have been downloaded or starred.

I do see above podcasts when I click on Downloads and Starred in Profile.

Is this a bug?

### Step-by-step reproduction instructions

1. Go to Filters
2. Create Filter
3. Download Status >> Downloaded
  or Starred
4. Download or Star a podcast you do not follow (are not subscribed to).

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Android 9, Pocket Casts 7.78 (9292)

**Comment by geekygecko** [comment]
This is how the app is intended to work. The filters section only shows episodes for podcasts you follow. This could be changed to include downloaded and starred episodes into this list for podcasts you don't follow. Thanks for the suggestion. I will add it to our internal ideas list.
