### ISSUE TITLE
Local files getting removed from up next queue when syncing

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#356]
If you're using two Android devices and one of them has a local file in the up next queue, then syncing the account on a different android device will remove the downloaded episode from the up next queue on both devices.

1. Device 1
    1. Add a local file to the up next queue
    1. Sync the device with the server
2. Device 2 
    1. Log into the same account as Device 1
    2.  Sync with the server
    3. Observe that the Up Next queue does not have the downloaded episode
    4. Sync with the server again
3. Device 1
    1. Sync with the server
    2. Observe that the downloaded episode has disappeared from the Up Next queue

### Actual Behavior
Syncing Up Next queues with local files with other Android devices removes the local files from the queue for all devices

### Expected Behavior
The local file should remain in the queue. 

#### Web

On the web, the local file looks like this:

![image](https://user-images.githubusercontent.com/4656348/193331819-ae5f06b7-bdfb-41a1-94d2-1cee4b3ec7eb.png)

And if you try to play the file you get this

![image](https://user-images.githubusercontent.com/4656348/193331863-e78f8f02-5277-4056-af1a-c2d497c12896.png)

#### iOS

iOS looks similar (although [it crashed](https://github.com/Automattic/pocket-casts-ios/issues/331) when I tried to play the file instead of playing an error).

<img width="350px" src="https://user-images.githubusercontent.com/4656348/193333363-bfc936b0-387c-4bd3-9c31-01134ea81046.png" />

**Comment by ashiagr** [comment]
Tried reproducing the issue and got this error in Step 2 (iv) after syncing on Device 2: 

```
E  BgTask: UpNextSyncJob - failed - 1175 ms
 E  retrofit2.HttpException: HTTP 401 
 E  	at au.com.shiftyjelly.pocketcasts.repositories.sync.SyncManagerImpl.getUserEpisode$lambda-7(SyncManagerImpl.kt:309)
 E  	at au.com.shiftyjelly.pocketcasts.repositories.sync.SyncManagerImpl.$r8$lambda$19fKT2aPVSSUhri1TzrtGYtEuQw(Unknown Source:0)
 E  	at au.com.shiftyjelly.pocketcasts.repositories.sync.SyncManagerImpl$$ExternalSyntheticLambda8.apply(Unknown Source:2)
 E  	at io.reactivex.internal.operators.single.SingleFlatMapMaybe$FlatMapSingleObserver.onSuccess(SingleFlatMapMaybe.java:81)
 E  	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65)
 E  	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
 E  	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
 E  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:52)
 E  	at io.reactivex.Observable.subscribe(Observable.java:12284)
 E  	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
 E  	at io.reactivex.Single.subscribe(Single.java:3666)
 E  	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
 E  	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
 E  	at kotlinx.coroutines.rx2.RxSingleCoroutine.onCompleted(RxSingle.kt:45)
 E  	at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal(AbstractCoroutine.kt:93)
 E  	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
 E  	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:859)
 E  	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
 E  	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
 E  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 E  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 E  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
 E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
 E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
 E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by CookieyedCodes** [comment]
Ya iOS to watch & watch to web will put a placeholder file found but not uploaded, it seems android to android doesn't have this except if the file is uploaded hence the removal, it would great if this was fixed :)
