### ISSUE TITLE
First swipe to open Up Next queue doesn't work

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#371]
### Description

I've noticed that when opening the app, the first time I swipe up from the full screen player to open the Up Next queue doesn't  work. It just peeks the up next queue and then the queue animates back closed. After that though opening the Up Next queue works just fine.

### Step-by-step reproduction instructions

1. Make sure the app isn't running. Swipe it away from recent if it is.
2. Open the app and go to the full screen player
3. Swipe up to open the Up Next queue
4. 🔴 Observe that the Up Next queue doesn't open
5. Do a second swipe to open the Up Next queue
6. 🟢 Observe that the up Next Queue opens

### Screenshots or screen recording

https://user-images.githubusercontent.com/4656348/194156431-b71f4e7d-60dd-4173-b27a-5d0a2d9905c9.mp4

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6, Android 13, 7.24-rc-1
Google Pixel 3, Android 12, 7.24-rc-1

**Comment by MiSikora** [comment]
I cannot reproduce this issue. The queue opens with the initial motion.
