### ISSUE TITLE
Files episode list play/pause icon gets stuck

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#397]
### Description

When playing a local file, the file's listing in the Files list gets a pause icon that persists even after the file has finished playing. Tapping that icon pauses playback of whatever got loaded from the up next queue, but the icon does not update to reflect the new status (should update to be a play icon).

### Step-by-step reproduction instructions

1. Add a very short local file
2. Make sure you an episode in the Up Next queue
3. Go to Profile tab -> Files
4. Tap on the row for the short local file
5. Tap on the play button
6. Let the local file complete playing in the full screen player so that the next episode is loaded from the Up Next queue
7. Back out of the full screen player
8. 🔴  Observe that the local file row has a pause icon even though the local file is not playing
9. Tap the local file's pause button
10. 🔴 Observe that playback is stopped (even though it wasn't the local file that was playing)
11. 🔴  Observe that even though playback has stopped, the local file still has a pause button (that doesn't seem to do anything)

### Screenshots or screen recording

https://user-images.githubusercontent.com/4656348/195361420-4f906139-08ea-4f6f-bff0-3d76c3be3675.mp4

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pixel 3, Android 12, Pocket Casts `7.24-rc-1`

**Comment by jmorton138** [comment]
I'm a first time contributor. Can I work on this?

**Comment by mchowning** [comment]
That would be great @jmorton138 . I'll assign the issue to you. Thanks!
