### ISSUE TITLE
Toggle for Notifications Disabled in v7.24-rc-4

### ISSUE THREAD

**Issue by thabotswana** [Automattic/pocket-casts-android#430]
### Description

We've gotten reports that notifications for Pocket Casts have been disabled and can not be toggled on. It seems to be happening on Android 13 devices. 

One of the reports is in 5636232-zen.

### Step-by-step reproduction instructions

I don't have Android 13 but you should be able to go to the phone's Settings for notifications for the Pocket Casts app.

### Screenshots or screen recording

![Screenshot_20221017-134247](https://user-images.githubusercontent.com/35628116/196963812-250e4c1f-a24b-4d88-a29f-4b7b4926bda6.png)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Phone: Google - raven - Pixel 6 Pro - raven
Android version: 13 SDK 33
App version : 7.24-rc-4 (9038)

**Comment by erricgunawan** [comment]
+1 from 5632643-zen

> There's a bug --- notifications are disabled on beta for Android 13. Ported everything over from my new phone and can't toggle notification. After wiping data, leaving beta, and reinstalling I'm prompted for notification permissions and it works, but if I update via the beta notifications are locked again

**Comment by mchowning** [comment]
This should be fixed in the `7.24.2` release which has now been fully released to production.
