### ISSUE TITLE
Clean up old Java code

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#44]
There is still some Java code in the project. It would be good to check if it's still needed and convert it over to Kotlin.

- [x] [EpisodeManagerTest.java](https://github.com/Automattic/pocket-casts-android/blob/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerTest.java)
- [x] [FileStorage.java](https://github.com/Automattic/pocket-casts-android/blob/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/FileStorage.java)
- [x] [FileUtil.java](https://github.com/Automattic/pocket-casts-android/blob/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtil.java)
- [x] [OldDataOpenHelper.java](https://github.com/Automattic/pocket-casts-android/blob/61fe9bf02411dbb158ec838d2fc4834099e99a4b/app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/OldDataOpenHelper.java)
- [x] [PCBottomSheetBehavior.java](https://github.com/Automattic/pocket-casts-android/blob/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/helper/PCBottomSheetBehavior.java)
- [x] [ShiftyCustomAudio.java](https://github.com/Automattic/pocket-casts-android/blob/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyCustomAudio.java)
- [x] [ShiftyTrimSilenceProcessor.java](https://github.com/Automattic/pocket-casts-android/blob/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyTrimSilenceProcessor.java)
- [x] [StringUtil.java](https://github.com/Automattic/pocket-casts-android/blob/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/StringUtil.java)
- [x] ~There are also proto generated files in [this directory](https://github.com/Automattic/pocket-casts-android/tree/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/services/protobuf/src/main/java/com/pocketcasts/service/api) but they can be removed in favor of linking proto generation with Java/Kotlin compilation tasks.~ -> This isn't currently feasible. See [this comment](https://github.com/Automattic/pocket-casts-android/issues/44#issuecomment-1878584701).

**Comment by MiSikora** [comment]
> There are also proto generated files in [this directory](https://github.com/Automattic/pocket-casts-android/tree/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/services/protobuf/src/main/java/com/pocketcasts/service/api) but they can be removed in favor of linking proto generation with Java/Kotlin compilation tasks.

From Slack convo.

> Since the source of the generated code isn't in this repo it seems a bit tricky to generate it in a gradle task. Particularly for open source contributors since the repo is private.

So this probably won't happen any time soon. I'm marking this check point as "done".

**Comment by MiSikora** [comment]
Managed to removed generated proto classes in #1831.
