### ISSUE TITLE
Opening PocketCasts share URLs in native mobile app

### ISSUE THREAD

**Issue by markcellus** [Automattic/pocket-casts-android#478]
### What problem does this address?

Currently, if you open a shared Pocket Casts URL (e.g. https://pca.st/yaoi883d), it opens a page showing an option to "Open in Pocket Casts". But it would be nice to able to have these URLs automatically open in the Pocket Casts Android app.

### What is your proposed solution?

Android already allows opening supported links in applications via "App Info" -> "Allow app to open supported links". But I can't seem to add links that begin with `https://pca.st/*`. Maybe the solution is just allowing the `https://pca.st/*` to be added in the supported links option? 

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by owenlejeune** [comment]
@mchowning I'd be happy to take a look at this if this a feature you want to support.

**Comment by markcellus** [comment]
Let me know if I can help at all! Thank you so much.

**Comment by owenlejeune** [comment]
@mchowning It appears that episode share links with time stamps are not currently supported by **_pktc_** links so those are not supported by this new implementation either. In those cases, the behaviour will be identical to opening the corresponding episode share link without a time stamp.
