### ISSUE TITLE
Support Podlove Simple Chapters (PSC)

### ISSUE THREAD

**Issue by Inrumpo** [Automattic/pocket-casts-android#489]
### What problem does this address?

As of now, chapter support in Pocket Casts is very limited. Pocket Casts only supports .mp3 chapters on Android (plus .m4a chapters on iOS and none with the web-based player).

**Podlove Simple Chapters** (short: **PSC**) would be a nice and simple addition to that (short) list of supported chapter types. Other than .mp3 or .m4a chapters, PSC are located in and read from the podcast RSS feed itself. This makes them easy to parse, easy to edit and file type independent. This would even allow chapter support for the Pocket Casts web player, addressing #615. 

### What is your proposed solution?

Podlove Simple Chapters (PSC) are fully specified over here:
https://podlove.org/podlove-simple-chapters/

The following example is taken from the PSC specification page. PSC information in the RSS feed does look like this:

```
<psc:chapters version="1.2" xmlns:psc="http://podlove.org/simple-chapters">
<psc:chapter start="0" title="Welcome" />
<psc:chapter start="3:07" title="Introducing Podlove" href="http://podlove.org/" />
<psc:chapter start="8:26.250" title="Podlove WordPress Plugin" href="http://podlove.org/podlove-podcast-publisher" />
<psc:chapter start="12:42" title="Resumée" />
</psc:chapters>
```

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by Inrumpo** [comment]
The Pocket Casts web player release `3.6.14` has introduced support for _Podlove Simple Chapters_ (and _Podcasting 2.0_ JSON chapters). This is a great addition to what is already a very good web player.

Hopefully support for _Podlove Simple Chapters_ (PSC) in the Pocket Casts smartphone apps is not far off.

**Comment by CookieyedCodes** [comment]
From what I've heard hopefully 😉, now hopefully RSS timetags will also be converted to chapters 😉

**Comment by Inrumpo** [comment]
At last! Version `7.61` of Pocket Casts was released today (for Android and iOS). It supports Podlove Simple Chapters (PSC).
