### ISSUE TITLE
Mediastyle Notification: Allow customization of actions

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#499]
### What problem does this address?

We've had a couple of reports of users who want to re-order or remove actions from the list, such as removing the star episode button or moving the skip backwards button next to the skip forwards button

7.23 vs 7.24: 
<img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/198034237-69279583-8f81-41f2-8b68-29a3c37ad43b.png"><img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/198034525-939c418a-1c2e-403d-a313-290d146a2946.png">

### What is your proposed solution?

Allow users to re-order the actions or remove actions not needed. 

Requests for this so far:

#5658000-zen
#5654342-zen

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by mchowning** [comment]
[Tweet](https://twitter.com/SrWapo/status/1585245154843455488) wanting to remove buttons from this notification.

> I'm not a fan of the new Android media player. The star and the playback speed eat up a lot of space for controls that I don't need in my notifications and I find myself changing the playback speed on accident without even unlocking my phone.

**Comment by geekygecko** [comment]
How about this for an implementation?

In the Settings -> General page add another setting under Defaults.

Title: Media notification controls
Summary: Choose two actions to be displayed in the Android 13 playback notification, Android Auto, and other places the custom media controls are available. (Please help me with this text)

That could open a dialog with checkbox options of the following and only allow the user to pick two options.
[ ] Archive 
[ ] Mark as played
[ ] Play next
[ ] Playback speed
[ ] Star


The media session actions are adding in [MediaSessionManager.addCustomActions](https://github.com/Automattic/pocket-casts-android/blob/main/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt#L320).

<img  width="300" src="https://user-images.githubusercontent.com/308331/198146385-1ea8a154-f5c1-4ed9-9c36-66304b43b0ae.jpg" />

**Comment by ksog66** [comment]
Hey @geekygecko, can I work on this implementation?

**Comment by mchowning** [comment]
> ...can I work on this implementation?

Absolutely @ksog66 , that would be great! 🙇

**Comment by geekygecko** [comment]
Thanks @ksog66 🎉

**Comment by ksog66** [comment]
Hey @geekygecko, I have made the remaining changes and PR is open for review. and one more thing do I have to run the buildKite tests or will it be run by reviewers? I am new to open source contribution, so don't have any idea about this.

**Comment by mchowning** [comment]
Thanks for the PR @ksog66 ! 🙇 

> do I have to run the buildKite tests or will it be run by reviewers?

There's nothing you need to do to start the BuildKite jobs. We'll take care of that when we review the PR. 👍

**Comment by csonnek** [comment]
https://twitter.com/ameetpadte/status/1592207049697394691

> Can you make the forward/backward buttons on the Android notification panel larger? It is very easy to accidentally hit the progress bar and jump to the end (video in linked Tweet)

**Comment by geekygecko** [comment]
@csonnek unfortunately we don't build the UI for the notification panel, we just pass the actions and events to the system to build it.
