### ISSUE TITLE
Tapping the play button flickers back to a pause icon

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#52]
The episode play button changes to a play icon, back to a pause icon, and then quickly back to a play icon again.

**Steps to repeat**
1. Open a podcast page
2. Tap an episode play button

https://user-images.githubusercontent.com/308331/177546412-5a1c30b2-4895-4bd4-b7e8-3e0e263980fc.mov

**Comment by ezebecke** [comment]
https://user-images.githubusercontent.com/24919469/194363026-a373baae-b4c4-47fb-9b9c-8edd31a492f4.mp4

Same issue but tapping play on the mini player. 

Reported on 5558791-zd

**Comment by AdamGEmerson** [comment]
I don't seem to be able to reproduce this issue on my device.  Is it possible that it has been resolved by the changes in #523?

**Comment by ashiagr** [comment]
This does seem to be resolved by the changes in https://github.com/Automattic/pocket-casts-android/issues/523.

I'll mark it as closed.
