### ISSUE TITLE
Show Artwork episode from rss feed

### ISSUE THREAD

**Issue by mksnsz** [Automattic/pocket-casts-android#528]
### What problem does this address?

Currently, pocket casts only show the artwork episode if they are embed in the audio file.

### What is your proposed solution?

It would be great if there was an option to see the artwork of the episodes that are in the rss feed of our podcasts. Thank you and sorry for the bad english

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by CookieyedCodes** [comment]
I would be all for it but from my understanding it's removed during the parceing mainly to save the user space & other stuff that the parceing dose & I kind of believe them at least in the regards of storage.

I had podcast addict installed as a backup for pockectcasts subscriptions + had the rss artwork toggle on and it took 20 gbs from my phone even tho I had no Downloads (only for 1280+ podcast subs  aprox) & if pockecasts were to store even more then that on their end I'd say oof tho they could pass it through & maby force an embedded 🤔, to be clear I do want it but I get if it's not a priority 🤔🤔 😉
