### ISSUE TITLE
Audio ducking not working

### ISSUE THREAD

**Issue by larena1** [Automattic/pocket-casts-android#529]
### Description

I would expect Pocket Casts to duck its audio as in lowering its own volume while a notification sound is playing. I know this from Spotify and it's working great there so I always wondered why Pocket Casts doesn't have it.

There's a switch in settings to control what happens on notifications. Turning it off will make Pocket Casts pause playback while a notification sound is playing. Turning it will make Pocket Casts just continue playback while the notification plays but not lower its volume.

There seems to be code in place that by the looks of it should be handing that but somehow it's not working as it should. 

### Step-by-step reproduction instructions

Turn on the switch in the settings
Start a podcast
Receive a notification

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Android 13 but was the same on Android 10 and 11
Pocket Casts 7.24

**Comment by larena1** [comment]
@ashiagr @geekygecko @mchowning

Thank you for looking into this. Can you confirm this issue?

**Comment by geekygecko** [comment]
That seems like a good idea to me. So by default, podcasts pause so in cases such as Google Maps telling you navigation directions you don't miss any of your podcast, which is already the case. But if you turn on the Settings -> Notifications -> 'Play over notifications' it would duck the volume when the notification audio is playing. 

The only reason I can think that this isn't the case is that we received support emails requesting it to not be this way, as it kept ducking for notifications. Maybe we can change it to duck instead and if we get support requests, then we could add an additional setting. Something like 'Play over notification' with the values 'Off', 'Full Volume', or 'Duck Volume'.

**Comment by mchowning** [comment]
> Maybe we can change it to duck instead and if we get support requests, then we could add an additional setting. Something like 'Play over notification' with the values 'Off', 'Full Volume', or 'Duck Volume'.

FWIW, my inclination would be to go straight to the three settings. That way we're not changing the behavior for all users who currently have turned that toggle on.

**Comment by larena1** [comment]
https://github.com/Automattic/pocket-casts-android/blob/main/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/LocalPlayer.kt#L17
https://github.com/Automattic/pocket-casts-android/blob/main/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt#L1192

Currently, Pocket Casts will just pretend to be ducking but keep the audio volume at 1.0f.
Seems to be as simple as changing the settings option and then depending on user's choice, set volume to either 0.5f or 1.0f.

**Comment by larena1** [comment]
@mchowning @geekygecko do you think this can be implemented? Seems like an easy fix.

**Comment by mchowning** [comment]
> do you think this can be implemented?

Seems like a nice improvement, it's just a matter of us or an OS contributor finding the time to do it. 🙂

**Comment by larena1** [comment]
For an expert like you who knows probably most of the codebase by heart, it shouldn't be more than half an hour including testing, right? 😊
