### ISSUE TITLE
Changing your device language resets the Auto Archive settings

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#54]
When you change your device language, the archive settings in Pocket Casts resets. So if a user initially had podcasts set to never archive, that gets cleared when you change the device language.

It seems specific to the Auto Archive settings and doesn't affect other settings.

Screen Recording:

https://user-images.githubusercontent.com/308331/177548504-babdc614-2020-4c95-a854-e5c5ab4c9b20.mp4

**Comment by thabotswana** [comment]
Another report in 5859563-zen

![Screenshot_20230118-161939](https://user-images.githubusercontent.com/35628116/213160225-8e5a8150-b64a-4da5-aa89-62016202d951.png)




![Screenshot_20230118-161947](https://user-images.githubusercontent.com/35628116/213160248-192a56b4-ad4a-4140-adfd-209b2e9b61fd.png)

**Comment by mchowning** [comment]
This was fixed by https://github.com/Automattic/pocket-casts-android/pull/1234
