### ISSUE TITLE
Go to Podcast Icon not showing correctly on Large Screens/Landscape Mode

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#55]
When using Landscape Mode, the 'Go to Podcast' icon is very small. It shows correctly in Portrait Mode.

![image](https://user-images.githubusercontent.com/308331/177554812-0672de20-0aa5-4a9e-bffe-7e681ded61e9.png)

**Comment by es0329** [comment]
Is this issue still valid? I see the _Sleep Timer_ as that button in `v7.26.rc-2`.

![221102_pocketcasts_v7 26 rc-2](https://user-images.githubusercontent.com/819901/199644495-33451ab3-c655-4321-be65-8ca07e348192.png)

**Comment by mchowning** [comment]
👋  @es0329! 

>  I see the Sleep Timer as that button in v7.26.rc-2.

If you click on the three dot overflow menu, and then tap on the pencil icon, you can change which icons show up by default. That's how the Go to Podcast icon can get displayed on the front screen.

I'd actually used Pocket Casts for around 8 years and had no idea about this option until I started working on Pocket Casts. This setting was really easy for me to overlook and, now that I know it's there, it seems really obvious. 🤣 

> Is this issue still valid?

I just tested, and I'm still seeing it.

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/4656348/199705467-c029ee47-b12d-4b1f-b31b-26da14123d53.png)

</details>
