### ISSUE TITLE
Specific podcast new episodes are not updating

### ISSUE THREAD

**Issue by ramfree17** [Automattic/pocket-casts-android#568]
One of the podcasts I listen to has stopped its new episodes from being shown in the Android app. I already went through https://support.pocketcasts.com/article/missing-new-episodes/ and unfortunately the issue is only manifesting in pocketcast. I already tried other audio cast players and they can see the episodes just fine. It is just in pocketcast that is only able to view up to the September 12, 2022 episode. I have also tried to clear the cache and reinstall pocket cast; as well as installing it in a different device that pulled information from a different network. All instances yielded the same result that the new episodes are not showing up.

Podcast link: https://podcastnetwork.asia/show/machong-chismisan/ ; https://anchor.fm/machong-chismisan
Last Episode recognized:  Sept 12, 2022 (Season 15 Episode 10)
Pocket Cast version: v 7.25 (9044)
Platform  - Android

**Comment by CookieyedCodes** [comment]
Contact support on Twitter or email they will fix it right up, weird that the feed fell asleep when it's active tho 🤔🤔
