### ISSUE TITLE
Add support for new media notification controls configuration to support 3 icons (if room).

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#590]
### Description

Recently the ability to [configure your media notification controls](https://github.com/Automattic/pocket-casts-android/pull/540) was added. Unfortunately, it changed the notification from three to two controls, so user's have mentioned they have lost the mark as played control.

<img  width="300" src="https://user-images.githubusercontent.com/308331/202375262-bdbddcb2-2005-4d3f-9b2a-7956363d043d.png" />

We used to offer three controls, playback speed, star, and mark as played. The Android playback notification only shows two controls but Android Auto uses three controls. 

Before
<img width="912" alt="Screenshot 2022-11-17 at 4 00 23 pm" src="https://user-images.githubusercontent.com/308331/202375541-53f0692c-c88c-40b8-a104-afb382d1e3e5.png">

After
<img width="912" alt="Screenshot 2022-11-17 at 4 58 52 pm" src="https://user-images.githubusercontent.com/308331/202375506-3be5881a-9f62-4054-8254-b45874cdd6f6.png">

It would be good to support three controls but it might be more difficult to implement the configuration page as we might want to let the user choose the positions so the user's least favourite control is removed.

<img  width="300" src="https://user-images.githubusercontent.com/308331/202375950-fe40c289-a7b9-4b6a-a413-5f70da5e53ac.png" />

### Step-by-step reproduction instructions

1. Follow the steps to set up an Android Auto emulator https://developer.android.com/training/cars/testing#test-auto
2. Deploy the app to a phone
3. Connect the phone using USB
4. Play an episode
5. Open the full screen playing screen

The mark as played control will be missing.

**Comment by ksog66** [comment]
Hey @geekygecko,
We can provide the user to choose 3 options and give a sorting option using up and down arrow to choose the position.
like in this image
![image](https://user-images.githubusercontent.com/70816971/204342375-658f9aeb-4cc6-4237-913a-3560b8f81740.png)

and we can also provide something like preview for mobile notif and android auto notif.( while choosing the position and media control)

**Comment by geekygecko** [comment]
@ksog66 I wasn't sure the best way for the user to give us their preference, but this looks like a great solution! Thanks for sharing your thoughts on this.

**Comment by npaladin2000** [comment]
The icons are being hidden on Android 12 as well, and we are not being shown the menu to manually change which icons we get.  On a Galaxy Z Fold 4 myself here. Really need my Mark as Played button...

**Comment by ksog66** [comment]
@geekygecko, If this solution looks good, then i would like to give it a try or if there is some UX engineer who can give some feedback then it would be good.

**Comment by mchowning** [comment]
I wonder if we could simplify that a bit by dropping the checkboxes so that this is just an option for prioritizing the order in which the buttons will be displayed. We'd just need to inform the user that generally only the top 2 to 3 options will be visible. That might set us up well for handling it if Android changes the media notifications or Android Auto to make more buttons visible in the future. That's just me thinking out loud though, I don't feel strongly and anything that gets the Mark as Played button back for Android Auto users will be a great step in the right direction (we've gotten quite a few complaints about losing the mark as played button on Android Auto).

Also, when updating this, I think we should open up this option for users who are below Android 13 since this still affects Android Auto on those devices.

I'll ping @adamzelinski in case he has any UI/UX feedback, but I don't think we need to wait for him to chime in. We can keep iterating on this if we need to, so 👍 to going ahead with your proposed solution @ksog66 .

**Comment by ksog66** [comment]
How about changing the summary to..
Summary -> Arrange the order of actions to be displayed in the Android 13 playback notification, Android Auto, and other places the custom media controls are available.

**Comment by mchowning** [comment]
Sounds pretty good to me. I would shorten it up a bit along these lines, but I don't feel strongly:

Summary -> Customize the buttons displayed in Android 13 playback notifications and Android Auto.

**Comment by joashrajin** [comment]
Not sure if this is in the scope of this bug report, but a user reported this today: 

> I received an update today, it removed the options I have selected for media notification controls. I have selected mark as played and play next as my options yet after the update when I click the 3 dots in Android auto I get a grid icon and a cast icon.

```
App version : 7.28-rc-1 (9054)
Phone: Google - cheetah - Pixel 7 Pro - cheetah
Android version: 13 SDK 33

```


5756473-zd-woothemes

**Comment by adamzelinski** [comment]
Hey everyone, sorry for the late reply on this. This solution looks good. However, I wonder if instead, we should make it look more like our custom player menu. That way we could lose the checkboxes and also the up/down arrows and just allow listeners to drag the ones they want up into the top section. You could have 3 slots but have a subheading saying depending on Android auto you may see 2 or 3 icons. 
![IMG_1171](https://user-images.githubusercontent.com/74938219/205212623-da70d428-781b-4371-8719-0a0adabfed80.PNG)

**Comment by erricgunawan** [comment]
Just wanted to add a report from 5761987-zen:

> I noticed today that you can't mark a podcast as listened to in android auto any more. That's something I use all the time and really don't want to have to keep track of everything I listened to in the car and mark it as complete when my trip ends. 

> App version : 7.27.1 (9055)
Phone: samsung - Galaxy Note10+ - SM-N975W - d2q
Kernel: 4.14.190-24304207-abN975WVLU7HVH5 - 21DK7A06
Android version: 12 SDK 31

**Comment by mdrockwell** [comment]
> Hi, I regularly use the app with Android auto and about a week ago the "mark as played" button disappeared from the Android auto interface, is there any way to get this back? I use it regularly.

5765550-zen

**Comment by erricgunawan** [comment]
Not sure if it's the same with Android Auto but it sounds like it:

> That's more relates to Microsoft sync on the Ford Transit connect.
> Apparently in the last hatch you removed the mark as played button on the head controls for Sync.

> App version : 7.27.1 (9055)
Phone: Google - Pixel 5a 5G - Pixel 5a - barbet
Kernel: 4.19.239-g248fa42a73b2-ab9062766 - abfarm-release-rbe-64-00008
Android version: 13 SDK 33

5767154-zen

**Comment by erricgunawan** [comment]
> When using Pocket Cast on Android Auto, of which I am a paid subscriber, your app no longer offers mark as played from the three dot menu. :-(

> App version : 7.27.1 (9055)
Phone: Google - bluejay - Pixel 6a - bluejay
Kernel: 5.10.107-android13-4-00038-ga6f610f1f1e6-ab9083768 - abfarm-release-2004-0112
Android version: 13 SDK 33

5768320-zen

**Comment by sophiegyo** [comment]
From Twitter:

>I still can't mark a podcast as played in the car due to the latest update which is quite annoying to have to stop the podcast then pull it up on the phone to mark it as played. Not everyone listens to a podcast to 100% completion.

**Comment by joashrajin** [comment]
+1 at 5771105-zd-woothemes

**Comment by ksog66** [comment]
Hey @mchowning, can you please help with better title and subheading.
![media_action_light](https://user-images.githubusercontent.com/70816971/206227806-fd25a036-379b-434e-82b7-2c4d3ed0bec1.jpeg)
![media_action_dark](https://user-images.githubusercontent.com/70816971/206227819-54e8ed7a-f8fc-4220-b118-be1c8f815c42.jpeg)

**Comment by IggyBathers** [comment]
I am also missing the mark played button. I view this as a safety issue, as now I have to press the skip forward button many many times until I can get to the end of the podcast, and during this time I have to look at the screen to make sure my finger is still on the skip forward button.

**Comment by igotdes** [comment]
Also reported in #5773171-zen:

> In version 7.27 the "Mark as played" in Android Auto has disappeared on my device.

**Comment by mchowning** [comment]
👋  @ksog66 ! That's looking great! Thanks so much for working on this. There are a lot of Android Auto users who are going to be very happy to see this fix.

> better title and subheading

That is a tricky one. 🤔  I might go with something like:

Heading: Prioritize your notification actions
Subheading: Your top actions will be available in your media notification and Android Auto

I'm not committed to that wording at all, so feel free to play with it and come up with something better. 🙂 For example, I'd like to have a more user friendly term than "media notification" to describe the media notification (feels like "media notification" is more of a developer term), but nothing is coming to mind for me.

**Comment by ksog66** [comment]
How about
Heading -> Action on notification player.
SubHeading ->Your top actions will be available in your notification and Android Auto player.

**Comment by ashiagr** [comment]
The subheading looks good, @ksog66. We can keep the heading suggested by @mchowning as we're actually prioritizing the actions. Let's discuss more in the PR. 🙌

**Comment by joashrajin** [comment]
+1 5772375-zd-woothemes

**Comment by joashrajin** [comment]
+1 5770724-zd-woothemes

**Comment by erricgunawan** [comment]
5758876-zen:

>  I use Pocket Casts in my car with Android auto. Today I was driving and noticed the mark As played button was replaced by a star. I have no idea how to mark a podcast episode as played so I can move on to the next episode. 

> App version : 7.27 (9053)
Phone: samsung - Galaxy S21 5G - SM-G991U1 - o1q
Kernel: 5.4.147-qgki-24900553-abG991U1UES5CVI8 - 21DKG923
Android version: 12 SDK 31

**Comment by joashrajin** [comment]
@ashiagr & @mchowning, we have had a complaint about the new drag and drop system. It forces users to pick 3 actions, whereas the previous system allowed users to tick the ones they wanted. 

Any way we can remove the 3-action limit?

5790103-zd-woothemes

**Comment by mchowning** [comment]
> we have had a complaint about the new drag-and-drop system. It forces users to pick three actions, whereas the previous system allows users to tick the ones they want.

It's certainly possible, but I think it would complicate the UX a fair bit to allow users to both select which items to show and to order them (at least I'm having trouble thinking of a good UX, maybe someone else has a good idea here). I'd like to wait and see if many users request this before we consider trying to add that ability.

**Comment by CookieyedCodes** [comment]
@mchowning their was a few on Reddit who also wanted the ability to just turn an icon off so they could get a full scrub bar on Android 13 notification, I personally would say allowing the ability to get icons to stick to the other media options would make people happy gets the best of both worlds  🤔🤔

**Comment by ashiagr** [comment]
> so they could get a full scrub bar on Android 13 notification

If it's only about getting a full scrub bar, we could add a toggle to override the settings and hide all actions. With the existing implementation, it might be simpler to make this change. Pinging @adamzelinski in case he has a better suggestion.

https://user-images.githubusercontent.com/1405144/208058828-8556c41a-a050-495a-90b7-9349553c0e04.mp4
