### ISSUE TITLE
Add chapters in the web browser version.

### ISSUE THREAD

**Issue by jeroenrotty** [Automattic/pocket-casts-android#615]
### What problem does this address?

The mobile app has chapter support, but it seems that the web interface doesn't.

### What is your proposed solution?

Please add the feature to the web app.

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by CookieyedCodes** [comment]
From my understanding it's not possible because web browsers don't allow cacheing of a file in a browser mainly because of security reasons  -dont want files to get bad stuff incerted into files as they are being cached-(same reason why trim scilence isn't possible)
Maby it will be possible someday tho 🤔🤔
Intresting factoid tho the Mac app actually dose have chapter support 😉

**Comment by jeroenrotty** [comment]
Oh sweet that you mentioned a Mac App, didn't even know that they had that! I'll use that more often than the web version instead! I'll try it out now!

**Comment by CookieyedCodes** [comment]
No bothers happy to help 😉

**Comment by geekygecko** [comment]
Thanks for responding @CookieyedCodes That is the reason. 
A great future feature would be to save these chapters to the server and share them with the web app in JSON format so they are still accessible.

**Comment by jeroenrotty** [comment]
Yeah, would love to see it happen one day though just for users not using the mac app so it works everywhere.

Offtopic, app works very well on Mac, happy!

**Comment by Inrumpo** [comment]
It is possible to show chapter marks in a web player environment.

The question is: _Where do those chapters come from?_ Traditional chapters are embedded in the audio file. Displaying those without a full download is hard. 
However, solving issue #489 would allow displaying (some) chapters on the web as well. 

How?
They key is supporting **Podlove Simple Chapters** (PSC). Those are embedded in the RSS feed an not in the audio file. They are audio file independent. One of their many advantages is allowing chapters support for web players.

Podlove Simple Chapters (PSC) are fully specified over here:
https://podlove.org/podlove-simple-chapters/

Fun fact: They are even part of the Spotify spec (probably for that very reason). But Spotify never implemented them, even though it should be fairly easy.

**Comment by Inrumpo** [comment]
Starting with release 3.6.14, the Pocket Casts web player supports _Podlove Simple Chapters_ (PSC) (Spotify started doing this a few months ago) and _Podcasting 2.0_ JSON chapters.
This issue is solved – to a degree.

**Comment by geekygecko** [comment]
I'm closing this issue as it's paritally solved on the Web Player using Podlove and Podcast 2.0 chapters. For other Web Player feature requests, please use the forums we have set up. https://forums.pocketcasts.com
