### ISSUE TITLE
Sync between app and web browser is unfortunately not accurate

### ISSUE THREAD

**Issue by jeroenrotty** [Automattic/pocket-casts-android#616]
### Description

I'm a vivid user of PocketCasts, both on mobile and in the web interface when at my PC. However, when I stop or pauze listening to a specific podcast somewhere in between. I'd expect that this would sync automatically to the second so I can listen back to this on the mobile website, which it doesn't seem to do accurately (or at all?)

I'd like to see this improved as a paid customer of the service.

### Step-by-step reproduction instructions

1. Listen to a podcast in the mobile app.
2. Pauze the podcast.
3. Go to the website and try to listen again to that podcast and see where it starts ...

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by CookieyedCodes** [comment]
I find it veryyyyyy accurate but you have to force a sync under profile before you switch devices, might be interesting to hear the reason why PC dosen't do a sync on pause? 🤔

**Comment by jeroenrotty** [comment]
Where is that "force sync" to be honest, can't find it and never did something like this. I just feel like it ain't syncing as I would like it to.

**Comment by CookieyedCodes** [comment]
Scroll to the bottom of the profile screen, obviously make sure your logged in(dragging on the podcast screen also refreshes but I prefer the profile screen as it tell the user 🤔 😉

**Comment by mchowning** [comment]
The last few days I've noticed my podcasts getting out of sync from Android → Web (i.e., playback on Android does not get reflected when I load up the podcast later on the web so I have to fast-forward the web player to get to where I am on my phone). 

Checking the support logs on my device, I see a fair number of `Could not sync episode progress. java.util.NoSuchElementException` errors, which might be related.

**Comment by mchowning** [comment]
> maybe we should change this line so we get the full stack track.

Just to follow-up on that, I think I've addressed the `NoSuchElementException` in https://github.com/Automattic/pocket-casts-android/pull/711, which will hopefully 🤞 significantly improve the sync from Android. I think there are still sync issues to be fixed though (i.e., [Android app doesn't sync after an episode has been paused](https://github.com/Automattic/pocket-casts-android/issues/123)).

**Comment by mchowning** [comment]
In light of the improvement that #711 did for this and the other, more specific, issue we have in [Android app doesn't sync after an episode has been pause](https://github.com/Automattic/pocket-casts-android/issues/123), I'll go ahead and close this issue. But feel free to reopen or open a new issue if you think there's still an outstanding problem here not covered by the other issue.
