### ISSUE TITLE
End of Year Review: Keeps popping up when opening the app

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#622]
### Description

If you aren't logged into a Pocket Casts account, each 2nd time you open the app, you are prompted to view the 'Your Year in Podcasts' page. Pressing 'Not Now' only temporarily hides it until you open the app again. This does not happen when you are signed into an account

### Step-by-step reproduction instructions

1. Sign out of your Pocket Casts account
2. Close the app
3. Re-open it and notice the pop-up
4. Press 'Not Now'
5. Close the app
6. Re-open the app, close it again
7. Notice on the second time you re-open the app, the Pop-up is back

### Screenshots or screen recording

https://user-images.githubusercontent.com/16253818/205007370-16ae526a-0eb3-426a-9e47-bf8a16066d2e.mp4

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung S21 FE, Android 12, Pocket Casts v7.27-rc-3

**Comment by joashrajin** [comment]
5743759-zd-woothemes

**Comment by ashiagr** [comment]
Fix is included in `v7.27.1`, just submitted for Google review.
