### ISSUE TITLE
Spacing off on Add File screen header

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#63]
The save button on the add file header is too close to the right side of the screen. 

Also, the header leaves room for the top system bar, but it covers up that bar, so there is too much blank space at the top of the screen.

<img width="400px" src="https://user-images.githubusercontent.com/4656348/177610667-212dab53-dfec-4781-a786-f185b2b4872c.png" />

**Comment by ashiagr** [comment]
https://github.com/Automattic/pocket-casts-android/pull/1175 partially fixes this issue.

This part still remains:
> Also, the header leaves room for the top system bar, but it covers up that bar, so there is too much blank space at the top of the screen.

**Comment by neeldoshii** [comment]
@mchowning 
Also, the header leaves room for the top system bar, but it covers up that bar, so there is too much blank space at the top of the screen.

Can you elaborate this?

**Comment by mchowning** [comment]
I'm not seeing the issue anymore on my device. Maybe this is fixed now. wdyt @ashiagr ?

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/f257b214-8783-48b0-81ea-e97f04ae7752)

**Comment by mchowning** [comment]
Closing as fixed.
