### ISSUE TITLE
Categories only in alphabetized order in English

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#673]
### Description

The Categories at the bottom of the Discover tab are ordered alphabetically, but only in English. Their order for a device set to another language appears random (but it's actually still alphabetical based on the categories' English titles).

It would be good to order these alphabetically in the device's language instead of always ordering them based on English.

### Step-by-step reproduction instructions

1. Change the language on your phoen to be English
2. Open the Discover tab and scroll down to the list of categories
3. Observe that the categories are listed in alphabetical order
4. Change the language on your device to a non-English language (i.e., French)
2. Open the Discover tab and scroll down to the list of categories
5. Observe that the categories are listed in the same order as they were in English, meaning that they may no longer be listed in alphabetical order with the new language.

### Screenshots or screen recording

<img width="350px" src="https://user-images.githubusercontent.com/4656348/210612787-151974a2-549e-481f-8f8c-0ae95d4013cd.png" />

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung A13, Android 12, Pocket Casts 7.29 beta build

**Comment by utkarshxf** [comment]
I'd like to help out with this issue.

**Comment by geekygecko** [comment]
@utkarshxf thanks, that would be great!
