### ISSUE TITLE
Upgrading to Plus by tapping a theme should switch to the theme

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#68]
If you go through the upgrade process to plus having selected the electricity theme, when you come back it's selected, but not actually active.

**Comment by mchowning** [comment]
Just tested in `7.51` and this now works:
1. Logged into a free account
2. Tapped on the Electricity Plus theme
3. Completed the upgrade flow to purchase Plus
4. ✅ When I completed the upgrade flow I was taken back to the appearance settings screen. The Electricity theme was selected **and active**.
