### ISSUE TITLE
Share URLs don't open episode in native app

### ISSUE THREAD

**Issue by markcellus** [Automattic/pocket-casts-android#700]
### Description

This is a bug that seems to be introduced in https://github.com/Automattic/pocket-casts-android/pull/526. Clicking share URLs do open in the native app now. But it does not go to directly to the episode. Instead, it goes to the Podcast listing of _all_ episodes.

### Step-by-step reproduction instructions

1. Paste and go to an episode's share link into the mobile browser of your Android device (e.g. https://pca.st/yaoi883d)
3. Watch it open in the native app
4. Verify it opens the podcast listing and does not open the actual podcast episode

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

OS: Android 13
Pocket Casts app version: 7.29.1

**Comment by markcellus** [comment]
Just bumping since this is still an issue. If someone can point me to where in the code this change can be made, I'm willing to open a PR. Thanks!

**Comment by CookieyedCodes** [comment]
I am having this too, I told a Dev yesterday & he gave it a kick, seems like after it goes down its only from that point 🤔🤔

**Comment by geekygecko** [comment]
I tested this with a recent build, and it works now. Close this issue.
