### ISSUE TITLE
X to clear search on Podcast Page overlaps text for RTL languages

### ISSUE THREAD

**Issue by azollafox** [Automattic/pocket-casts-android#720]
### Description

When I enable a RTL language in my keyboard, then enter content in the episode search bar on a podcast page, the x button to clear the search overlaps my text

### Step-by-step reproduction instructions

1. Open a podcast page
2. Tap into the search bar
3. Set a RTL language and start typing

### Screenshots or screen recording

![Screenshot_20230106_195143_Pocket Casts](https://user-images.githubusercontent.com/7907292/213516218-d6af2a94-f829-4395-8621-7f6f9f7cea0e.jpg)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

HE reproduced Pixel 6, Android 13, Pocket Casts 7.30

Reported 
Phone: samsung - r0q - SM-S901E - r0q
Kernel: 5.10.81-android12-9-25490797-abS901EXXU2BVKM - 21DKGA14
Android version: 13 SDK 
App version : 7.29 (9063)

**Comment by neeldoshii** [comment]
Hello @mchowning can you close this issue as this issue is now fixed so no new comer will try to again fix it thanks.
