### ISSUE TITLE
Notifications Blocked on Android 13

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#723]
### Description

I noticed on Android 13 that notifications seem to be blocked by default. This is impacting our notifications feature, so even if you have notifications enabled for a podcast, you won't receive them unless you manually unblock notifications via Settings > Apps > Pocket Casts > Notifications. 

I wonder if this is an Android 13 bug or something we can force enable when notifications are switched on within the app

### Step-by-step reproduction instructions

1. Install Pocket Casts on a device running Android 13
2. Go to 'Settings > Apps > Pocket Casts > Notifications' and check what it is set to

### Screenshots or screen recording

Pixel 6 using Android 12, and Pixel 7 using Android 13: 

<img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/213694235-b51de7c7-44ac-4f67-8745-1d964945fbd9.png"> <img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/213694409-e97c0f8f-13a0-4038-bf18-9ae983075ea5.png">

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 7, Android 13, Pocket Casts v7.30-rc-3 + Samsung S21 FE, Android 13, Pocket Casts v7.30-rc-3

**Comment by xenom34** [comment]
Please note that this is not a bug in Android 13, but rather a new feature that restricts notification sending. By default, sending is not possible, and this has become the standard. Therefore, prior authorization from the user must always be requested (unfortunately, I don't think you have a choice 🤷‍♂️). My pull request #757 does the job if you want.
