### ISSUE TITLE
App Crashes When Opening Links without Browser Access

### ISSUE THREAD

**Issue by igotdes** [Automattic/pocket-casts-android#762]
### Description

A user has reported a crash in Android when attempting to open links from the app when no browser can be used, such as when there is a device filter that blocks browser access.

The user suggested we display a pop-up notification similar to what WhatsApp does here:

<details>
<summary>Details</summary>

![Screenshot_20230203_164007_WhatsApp](https://user-images.githubusercontent.com/74066241/217462105-380bae04-297c-43f8-92b9-ba94ce9f7c79.jpg)

</details>

### Step-by-step reproduction instructions

1. Disable browser access for the device using a filter or similar
2. Click on a link in the app, such as one in an episode's notes
3. The app will crash

### Screenshots or screen recording

<details>
<summary>Details</summary>

https://user-images.githubusercontent.com/74066241/217461665-84dff4a4-b1e0-4ffa-ac34-91f11dcbcbde.mp4

</details>

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Reported on:

* App version : 7.30 (9070)
* Phone: samsung - b0q - SM-S908U1 - b0q
* Android version: 13 SDK 33

**Comment by mchowning** [comment]
Fixed by https://github.com/Automattic/pocket-casts-android/pull/772
