### ISSUE TITLE
Upload the mobile APK as an artifact in GitHub actions

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#80]
As part of the 'Release to Internal' GitHub action upload the mobile APK. This will help if we need to test something on a specific version.

We already do this for the Automotive APK.

<img width="1195" alt="Screen Shot 2022-07-11 at 10 07 26 am" src="https://user-images.githubusercontent.com/308331/178168931-76186e10-bc81-402a-ab4e-b81fc8566df4.png">

It would be good to also include the app version name and code. For example: pocket-casts-7.20.0-58141.apk

**Comment by mchowning** [comment]
Closing this since we moved to using buildkite for handling our APKs.
