### ISSUE TITLE
matchIsInUrl catches non url cases

### ISSUE THREAD

**Issue by grant0417** [Automattic/pocket-casts-android#814]
### Description

matchIsInUrl returns true even if it is not in a URL, this causes timeskips to not be parsed correctly

https://github.com/Automattic/pocket-casts-android/blob/0795b5017942d4a31e6805f2c01d54ef52cefb5e/modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ShowNotesHelper.kt#L17-L20

### Step-by-step reproduction instructions

```html
<p>Example 00:00 <a href="https://example.com">Link</a></p>
```

In the example above the matcher will start at the `00:00` and scan for any pattern like an end tag, despite not being in an `a` tag the first endtag is the `a` endtag so the `matchIsInUrl` function will return true.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by rodrigoborgesdeoliveira** [comment]
I'd like to give this issue a try. I'll try to submit a PR later today.
