### ISSUE TITLE
Automotive: Sign out and clear data

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#815]
### Description

The Automotive app is often a shared device so it would be good to offer the ability for the user to clear their data when they sign out. This will give users the ability to sign into their own Pocket Casts account and the data such as listening history won't be merged with the previous account.

### Step-by-step reproduction instructions

1. Load the Automotive app into an Automotive emulator
2. Tap the settings cog
3. Sign into the account
4. Go back to the settings back
5. Tap the "Signed in as" option
6. Tap "Sign out"
Here would be a good place to ask if the user wants to clear their data. Maybe it could be a yes or no option rather than always clearing their data.

### Screenshots

![Screenshot_20230307_103649](https://user-images.githubusercontent.com/308331/223285151-60a3819f-4809-4815-92e2-5c1254c02288.png)

![Screenshot_20230307_103657](https://user-images.githubusercontent.com/308331/223285159-e484d83a-5606-427a-a159-53f620195b92.png)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Automotive

**Comment by mchowning** [comment]
> Tap "Sign out"
> Here would be a good place to ask if the user wants to clear their data. Maybe it could be a yes or no option rather than always clearing their data.

Do you think giving the pop-up three options instead of two would work @geekygecko ? Something like "Cancel", "Sign out", and "Sign out and clear data"

**Comment by geekygecko** [comment]
As users pressing logout is rare and this is only on Automotive, your two alert boxes idea is fine. Thanks again for your help.
