### ISSUE TITLE
Update Interval configuration

### ISSUE THREAD

**Issue by gyund** [Automattic/pocket-casts-android#858]
### What problem does this address?

A [discussion](https://github.com/Automattic/pocket-casts-android/discussions/738#discussioncomment-4819705) about APIs made reference to control server costs. #839 is making improvements to task scheduling for work manager to reduce data use for users without having to disable background data manually on android app preferences, but it also has the side effect that it will cut the number of requests down for each user that prefers **not** to be updated while on a metered network. Work manager currently runs the update task on an hourly basis.

This of course has the economies of scale. Assuming 100k users current mechanics would trigger 2.4M requests per day.

Additionally some users could be fine with being updated once a day at a specific time or just after they wake up or go to work. There's a huge potential for savings on being more efficient about polling.

### What is your proposed solution?

The [PeriodicWorkRequest](https://developer.android.com/reference/androidx/work/PeriodicWorkRequest) supports [constraints ](https://developer.android.com/reference/androidx/work/Constraints), both of which get used by current tasking mechanisms. 

### Approach 1 - inexact alarms 

Android also supports [inexact alarms](https://developer.android.com/training/scheduling/alarms#inexact), which would allow for a window for these updates to occur. The idea is that for cases where users typically wake up in the morning, want to get their podcasts updated just before they go to work, inexact alarms would help trigger this. So how do we configure it?

A straight forward approach would be to have a setting the user could specify that the background update should happen "once a day" and give it a time. With android 12+ the window size is 10 minutes. So when provided the time, the inexact alarm could be scheduled for `time - 10 minutes` with a window size of 10 at a bare minimum. This could be made wider using the same approach.

This would eliminate the need for polling all day/night long and could cut down on the API requests the most. Alarms do require an additional permission to be declared in the manifest. There's also a side benefit of being slightly more efficient on the user side, but I think a bigger benefit would be in cutting down on server costs. Generally speaking, I think 90% of the time, the background task to update has nothing to update.

### Approach 2 - push to update

There's also another approach, but it would require server side processing and push notifications to trigger tasks to update on the client side. Given that Automattic knows which podcasts users are subscribed to, when updates to feeds are detected, they send a push notification to subscribers to trigger the app to pull down updates. The client then no longer needs to poll. This also assumes reliable but not necessarily immediate delivery of push notifications. This, however, may increase compute cost for processing and sending push notifications. You also likely want to avoid sending to subscribers that haven't been running the app recently and there's differences between platforms, iOS and Android. The idea though is the less polling is involved in the process and more event driven, the more efficient the use of resources will be.

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by mchowning** [comment]
> Android also supports [inexact alarms](https://developer.android.com/training/scheduling/alarms#inexact), which would allow for a window for these updates to occur. The idea is that for cases where users typically wake up in the morning, want to get their podcasts updated just before they go to work, inexact alarms would help trigger this.

Is the suggestion here to essentially give users the ability to schedule when/how-often the app fetches the latest podcast info? I wonder if many user would want to sync less often, and then how many of those users would want to do it on a schedule. The one other request I know of that was similar to this was a user who wanted to sync more frequently.

> push to update

This would definitely be a nice improvement, but it's not on our immediate roadmap at this point.

**Comment by gyund** [comment]
Yes, just something I noticed when looking through the code. Users that update once a day are probably 9-5ers. You have 10-20 hours of podcasts in the queue, maybe you only listen on your commute to and from work. Every night you get home and just top off your list so you don't run out.

Unless you have lots of free time, I suspect most folks have too many podcasts to listen to, so it's more about prioritizing and curating a list from the backlog without turning your phone into a local data center. So current events is more likely something you want sooner. Podcasts with series, downloading now or later is largely irrelevant...especially for podcast number 40 on your up-next queue. You could download it now, but it'll be a few weeks before you get to it and hopefully you've gone home between then to sync up. 

I wouldn't doubt there's a subset of folks that want more frequent updates, but I suspect the number of folks that don't care is a lot larger. It's hard to poll that audience though because they don't care 😜. 

Just my thoughts tho when I noticed the data center costs mentioned in the discussion. It'd be interesting to run the numbers if all users were opted into daily updates by default how much that would save on compute costs. I think that's probably more of what would drive the priority of this feature. I'm addicted to efficiency problems 😀

**Comment by gyund** [comment]
I might try taking a crack at an implementation for this using the [time picker dialog](https://developer.android.com/reference/android/app/TimePickerDialog).

Basically I think it needs:

- A setting by background updates to "perform updates daily" (default: false)
- when enabled above, a setting to select the time will appear below the switch
- when daily updates are configured, it will replace the workmanager with the inexact alarms

**Comment by mchowning** [comment]
👋 @gyund ! Thanks for sharing your plans. 🙇 

>  I think it needs:
> 
> * A setting by background updates to "perform updates daily" (default: false)
> * when enabled above, a setting to select the time will appear below the switch
> * when daily updates are configured, it will replace the workmanager with the inexact alarms

This seems reasonable to me. I like how this setting is pretty straightforward. I don't think users would have much trouble understanding what it does. 

> As it relates to https://github.com/Automattic/pocket-casts-android/issues/839, the option to "Warn before using data" would be replaced by an option to "Don't sync on metered networks".

I do not think we should replace the "Warn before using data" setting. I feel it serves a distinct purpose that is separate from what you're working on.

I'm a bit skeptical that these new settings would be useful to a significant portion of our users, but that's just my intuition, and I could be wrong.

I've been toying with the idea of having a section of "advanced" settings that users would have to opt into to see. My thinking is that settings we're a bit unsure about could go there and they wouldn't complicate the user experience for most of our users. Users could still access them if they really wanted to though, and if it turns out that one of the "advanced" settings is popular, we could "graduate" it out of the advanced section. The two settings you're describing might end up being good candidates for starting that section. 🤔

**Comment by gyund** [comment]
🤔 @mchowning So for advanced settings, are you thinking a menu entry on the "settings" page. Right above "Help & Feedback"? And corresponding to these settings, the typical statistics to track their use?

**Comment by gyund** [comment]
Closing after further evaluation in PR notes on #885 since I think the fix for #839 will do a sufficient job and avoid the potential of missing updates beyond 24 hrs.
