### ISSUE TITLE
Group listening history by date

### ISSUE THREAD

**Issue by slasherly** [Automattic/pocket-casts-android#884]
### What problem does this address?

Currently, Pocket Casts shows the listening history as a list with no easy way to go to a particular day and view the episodes.

### What is your proposed solution?

I love the history section of Spotify and their implementation of stacking episodes for the date they are played on. Pocket Casts can do something similar to that.

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by CookieyedCodes** [comment]
I personally would have loved something like this like the iOS app but their must be some reason why it's not possible tho🤔
