### ISSUE TITLE
Keyboard shows up late when creating or renaming Folder

### ISSUE THREAD

**Issue by b-aaron** [Automattic/pocket-casts-android#906]
### Description

When trying to rename a folder, the keyboard doesn't show up after clicking on the text box. It only shows up after closing the screen.

### Step-by-step reproduction instructions

1. Go to folder
2. Go to Edit Folder
3. Click on Text Box to rename Folder
4. Keyboard doesn't open
5. Close Edit Folder Window
6. Keyboard appears

### Screenshots or screen recording

https://user-images.githubusercontent.com/72910336/234121425-ed2dd7f9-9c70-40d9-8014-52b446b0b6f0.mp4

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Galaxy S20 FE 5G
Android 13
OneUI 5.1
Pocket Casts v7.37-rv-3

**Comment by igotdes** [comment]
Reported in #6248179-zen.

There is also a similar issue during folder creation:

https://user-images.githubusercontent.com/74066241/235589472-7e5f07ef-9719-460b-a1b6-de18d5e5e8f0.mp4

@mchowning Would a separate issue be necessary?

**Comment by mchowning** [comment]
> Would a separate issue be necessary?

Reporting that here is perfect. 👍  Thanks @igotdes !

I did update the issue name to be a bit broader.

**Comment by igotdes** [comment]
+1 in #6256221-zen:

> There seems to be a but when trying to name a new folder using the app on my Z Fold 4. The keyboard isn't invoked and I can't paste into the field either. This happens whether I select podcasts on the previous page or not.
[...]
this behavior persists in portrait/landscape. Folded and unfolded

In the meantime, I'm asking them to manage folders from the web app.

**Comment by igotdes** [comment]
#6262998-zen:

> I can't rename or create a name for folders because no keyboard appears like it's supposed to.

**Comment by b-aaron** [comment]
> In the meantime, I'm asking them to create/manage folders from the web app.

Additionally, one can write the name into somewhere else (e.g. search bar) and then copy it from there and paste it into the folder name.

**Comment by ashiagr** [comment]
Fix is included in [7.38-rc-3](https://github.com/Automattic/pocket-casts-android/releases/tag/7.38-rc-3) beta release. H/t @mchowning.
