### ISSUE TITLE
Issues with the 'Extra Dark' theme

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#929]
### Description

The Extra Dark theme does not render properly on the following settings pages: General, Storage & data use, Auto add to Up Next, Advanced, and About.

It renders properly on the rest of the pages.

### Step-by-step reproduction instructions

1. Open the Pocket Casts App
2. Go to your Profile
3. Go to Settings
4. Go to Appearance
5. Select the “Extra Dark” theme
6. Go back to Settings
7. Go to General: its theme should be Extra Dark, but it is not; it is Dark.
8. Go back to Settings
9. Go to Notifications: its theme is Extra Dark, which is what it should be. OK.
10. Repeat the above for all sections of the Settings. You will see that the following are wrong, they should be in Extra Dark, but they are not; they are just Dark: General, Storage & data use, Auto add to Up Next, Advanced, and About.

### Screenshots or screen recording

<img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/236213967-9d2c972e-b551-4196-b15f-1fbc5808a61f.png"> <img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/236214110-3c6785d5-9843-4940-b727-d0d733facfc3.png">

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung S21 FE, Android 13, Pocket Casts v7.37

**Comment by mohitoshM** [comment]
my OCD made me switch from extra-dark to dark just for this reason
