### ISSUE TITLE
Keyboard does not open when trying to edit Folder Name

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#954]
### Description

When you try to edit the name of an existing Folder, the keyboard no longer opens. When you press the back button, then it opens

### Step-by-step reproduction instructions

1. Go to a Folder
2. Click the 3 dots at the top right
3. Click 'Edit Folder'
4. Notice the keyboard never opens, even if you place your cursor on the text

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/16253818/467814e8-4bb1-42f7-93a4-eda79e9d2c20

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung S21 FE, Android 13, Pocket Casts v7.37.1

**Comment by mchowning** [comment]
This should be fixed in `7.38` by https://github.com/Automattic/pocket-casts-android/pull/946.
