### ISSUE TITLE
Show episode notes are slow to load

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#96]
Episode notes load slower on `Android` as compared to `iOS`. 

~~It seems `Android` is downloading images within the notes but `iOS` might not be doing it.~~

EDIT: I was testing `Android` and `iOS` builds on `staging` and `prod` env respectively. The `staging` one returned an image while `prod` did not so the issue is somewhere else.

Android | iOS
--------|-----
![android](https://user-images.githubusercontent.com/1405144/178417389-2093f774-7c3a-4dce-b010-7bb02e3159db.png) | ![iphone](https://user-images.githubusercontent.com/1405144/178417415-fe1b407e-803d-4da7-a01b-5d0622dff09f.png)

See p1657582874426189-slack-C02A333D8LQ for more details.

**Comment by mchowning** [comment]
> Unable to reproduce it so far. Found notes loading time almost the same on both platforms.

I just tested this, and that was my observation as well. Do you think we're fine to close this @ashiagr ?

**Comment by MiSikora** [comment]
I'll close this one. I'm not experiencing this issue either. I think it was the issue with staging/prod were staging in general is much slower. Feel free to re-open if you still experience this.
