### ISSUE TITLE
New profile header text is very small on Android Automotive

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#966]
### Description

The profile header added in https://github.com/Automattic/pocket-casts-android/pull/926 uses text that I think is too small on the Android Automotive app. My concern is that it would be hard for someone driving in a car to read and could cause driver distraction.

It looks like the [official guidance](https://developers.google.com/cars/design/android-auto/design-system/typography#:~:text=While%20the%20smallest%20body%20text,24dp%20can%20be%20used%20sparingly.) regarding font size on auto is:

> While the smallest body text size for Android Auto is 24dp, subtext type sizes below 24dp can be used sparingly. Because this subtext size is not easily glanceable, it should be reserved for non-crucial information, such as status bar content.

It looks like it is currently using an H4 font style, which has a 15sp size.

### Step-by-step reproduction instructions

View the profile header on a fresh install of the Android Automotive app by tapping the ⚙️ icon when you open the app.

### Screenshots or screen recording

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/c6a58b29-1008-4409-b0e5-edff3bfacf18)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Android Automotive emulator running 7.39-rc-1.

**Comment by geekygecko** [comment]
Thanks for raising this, I also noticed it. Next time I will remember to raise an issue. When someone is looking at this issue, could they also please try to make the background colors match.
