### ISSUE TITLE
Keep Track of Back/Forward Skips in Rapid Succession

### ISSUE THREAD

**Issue by leoherzog** [Automattic/pocket-casts-android#969]
### What problem does this address?

If a user skips ahead 30 seconds with a button press, then immediately skips backwards 15 seconds, the "time saved skipping forward" that's recorded is 30 seconds saved. Or, if a user skips forward 30 seconds and immediately skips backwards 30 seconds, that's recorded as 30 seconds saved.

### What is your proposed solution?

We should keep track of backward and forward skips within a two second window in `PlaybackManager.kt` and only send the difference to `statsManager`

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by MiSikora** [comment]
Thank you for the suggestion but we decided not go with it. Stats aren't meant to be extremely precise and are rather a fun feature that give an overview of how one uses the app.
