### ISSUE TITLE
Add validation to email/password in wear app

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#983]
### Description

Currently, the wear app does not do any validation of the email and password—it just sends off whatever the use enters to the server. If there is an error, it presents the server error or [defaults to](https://github.com/Automattic/pocket-casts-android/blob/989c3237d4e83be8b9cdb2d56b031ab309dd41d9/wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginWithEmailScreen.kt#L82) "Unable to login to you sync account, sorry. Try again later."

<img width="350px" src="https://github.com/Automattic/pocket-casts-android/assets/4656348/dfe6d33d-2f0a-4d6a-aa7c-94195fb29424" />

It would be better to validate that we have a valid email and a password that is long enough and present more relevant error messages like we do on the phone app.

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/d3e2011a-af4a-4248-9150-088f489f6816)

h/t to @geekygecko for [noting this](https://github.com/Automattic/pocket-casts-android/pull/981#pullrequestreview-1433681964)

### Step-by-step reproduction instructions

1. Log into the watch app with an invalid email or password
2. Observe the generic error message

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Watch emulator running pre-release 7.30 pre-release build

**Comment by atharv028** [comment]
The validations were added but the message was not displayed in the app, this PR fixes that. 

### Screenshots

|                                                               Credentials                                                              |                                                                 Screens                                                                |
|:--------------------------------------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------------------------------------------------------------------------:|
| ![Screenshot_20230606_190607](https://github.com/Automattic/pocket-casts-android/assets/89896473/26346e0c-b9e7-46b7-8204-09195ad3571f) | ![Screenshot_20230606_190618](https://github.com/Automattic/pocket-casts-android/assets/89896473/06a4c171-9a57-490d-8e71-c650027f5df5) |
| ![Screenshot_20230606_190707](https://github.com/Automattic/pocket-casts-android/assets/89896473/2b584d7a-a02c-4c1c-9bd9-3f70ed7e9a8c) | ![Screenshot_20230606_190714](https://github.com/Automattic/pocket-casts-android/assets/89896473/e6211bc3-5bf0-4917-8279-2f1ee9504a75) |
